//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Google.Apis.Discovery.v1.Data {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    
    
    public class DirectoryList : Google.Apis.Requests.IDirectResponseSchema {
        
        private IList<DirectoryList.ItemsData> items;
        
        private string kind;
        
        private Google.Apis.Requests.RequestError error;
        
        private string eTag;
        
        /// <summary>The individual directory entries. One entry per api/version pair.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("items")]
        public virtual IList<DirectoryList.ItemsData> Items {
            get {
                return this.items;
            }
            set {
                this.items = value;
            }
        }
        
        /// <summary>The kind for this response.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind {
            get {
                return this.kind;
            }
            set {
                this.kind = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("error")]
        public virtual Google.Apis.Requests.RequestError Error {
            get {
                return this.error;
            }
            set {
                this.error = value;
            }
        }
        
        public virtual string ETag {
            get {
                return this.eTag;
            }
            set {
                this.eTag = value;
            }
        }
        
        public class ItemsData {
            
            private string description;
            
            private string discoveryLink;
            
            private string documentationLink;
            
            private ItemsData.IconsData icons;
            
            private string id;
            
            private string kind;
            
            private IList<System.String> labels;
            
            private string name;
            
            private System.Nullable<bool> preferred;
            
            private string title;
            
            private string version;
            
            /// <summary>The description of this API.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("description")]
            public virtual string Description {
                get {
                    return this.description;
                }
                set {
                    this.description = value;
                }
            }
            
            /// <summary>A link to the discovery document.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("discoveryLink")]
            public virtual string DiscoveryLink {
                get {
                    return this.discoveryLink;
                }
                set {
                    this.discoveryLink = value;
                }
            }
            
            /// <summary>A link to human readable documentation for the API.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("documentationLink")]
            public virtual string DocumentationLink {
                get {
                    return this.documentationLink;
                }
                set {
                    this.documentationLink = value;
                }
            }
            
            /// <summary>Links to 16x16 and 32x32 icons representing the API.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("icons")]
            public virtual ItemsData.IconsData Icons {
                get {
                    return this.icons;
                }
                set {
                    this.icons = value;
                }
            }
            
            /// <summary>The id of this API.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("id")]
            public virtual string Id {
                get {
                    return this.id;
                }
                set {
                    this.id = value;
                }
            }
            
            /// <summary>The kind for this response.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("kind")]
            public virtual string Kind {
                get {
                    return this.kind;
                }
                set {
                    this.kind = value;
                }
            }
            
            /// <summary>Labels for the status of this API, such as labs or deprecated.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("labels")]
            public virtual IList<System.String> Labels {
                get {
                    return this.labels;
                }
                set {
                    this.labels = value;
                }
            }
            
            /// <summary>The name of the API.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("name")]
            public virtual string Name {
                get {
                    return this.name;
                }
                set {
                    this.name = value;
                }
            }
            
            /// <summary>True if this version is the preferred version to use.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("preferred")]
            public virtual System.Nullable<bool> Preferred {
                get {
                    return this.preferred;
                }
                set {
                    this.preferred = value;
                }
            }
            
            /// <summary>The title of this API.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("title")]
            public virtual string Title {
                get {
                    return this.title;
                }
                set {
                    this.title = value;
                }
            }
            
            /// <summary>The version of the API.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("version")]
            public virtual string Version {
                get {
                    return this.version;
                }
                set {
                    this.version = value;
                }
            }
            
            /// <summary>Links to 16x16 and 32x32 icons representing the API.</summary>
            public class IconsData {
                
                private string x16;
                
                private string x32;
                
                /// <summary>The url of the 16x16 icon.</summary>
                [Newtonsoft.Json.JsonPropertyAttribute("x16")]
                public virtual string X16 {
                    get {
                        return this.x16;
                    }
                    set {
                        this.x16 = value;
                    }
                }
                
                /// <summary>The url of the 32x32 icon.</summary>
                [Newtonsoft.Json.JsonPropertyAttribute("x32")]
                public virtual string X32 {
                    get {
                        return this.x32;
                    }
                    set {
                        this.x32 = value;
                    }
                }
            }
        }
    }
    
    public class Jsonschema {
        
        private string refValue;
        
        private Jsonschema additionalProperties;
        
        private string defaultValue;
        
        private string description;
        
        private IList<System.String> enumValue;
        
        private IList<System.String> enumDescriptions;
        
        private string format;
        
        private string id;
        
        private Jsonschema items;
        
        private string location;
        
        private string maximum;
        
        private string minimum;
        
        private string pattern;
        
        private Jsonschema.PropertiesData properties;
        
        private System.Nullable<bool> repeated;
        
        private System.Nullable<bool> required;
        
        private string type;
        
        /// <summary>A reference to another schema. The value of this property is the &quot;id&quot; of another schema.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("$ref")]
        public virtual string Ref {
            get {
                return this.refValue;
            }
            set {
                this.refValue = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("additionalProperties")]
        public virtual Jsonschema AdditionalProperties {
            get {
                return this.additionalProperties;
            }
            set {
                this.additionalProperties = value;
            }
        }
        
        /// <summary>The default value of this property (if one exists).</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("default")]
        public virtual string Default {
            get {
                return this.defaultValue;
            }
            set {
                this.defaultValue = value;
            }
        }
        
        /// <summary>A description of this object.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("description")]
        public virtual string Description {
            get {
                return this.description;
            }
            set {
                this.description = value;
            }
        }
        
        /// <summary>Values this parameter may take (if it is an enum).</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("enum")]
        public virtual IList<System.String> Enum {
            get {
                return this.enumValue;
            }
            set {
                this.enumValue = value;
            }
        }
        
        /// <summary>The descriptions for the enums. Each position maps to the corresponding value in the &quot;enum&quot; array.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("enumDescriptions")]
        public virtual IList<System.String> EnumDescriptions {
            get {
                return this.enumDescriptions;
            }
            set {
                this.enumDescriptions = value;
            }
        }
        
        /// <summary>An additional regular expression or key that helps constrain the value. For more details see: http://tools.ietf.org/html/draft-zyp-json-schema-03#section-5.23</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("format")]
        public virtual string Format {
            get {
                return this.format;
            }
            set {
                this.format = value;
            }
        }
        
        /// <summary>Unique identifier for this schema.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("id")]
        public virtual string Id {
            get {
                return this.id;
            }
            set {
                this.id = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("items")]
        public virtual Jsonschema Items {
            get {
                return this.items;
            }
            set {
                this.items = value;
            }
        }
        
        /// <summary>Whether this parameter goes in the query or the path for REST requests.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("location")]
        public virtual string Location {
            get {
                return this.location;
            }
            set {
                this.location = value;
            }
        }
        
        /// <summary>The maximum value of this parameter.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("maximum")]
        public virtual string Maximum {
            get {
                return this.maximum;
            }
            set {
                this.maximum = value;
            }
        }
        
        /// <summary>The minimum value of this parameter.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("minimum")]
        public virtual string Minimum {
            get {
                return this.minimum;
            }
            set {
                this.minimum = value;
            }
        }
        
        /// <summary>The regular expression this parameter must conform to.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("pattern")]
        public virtual string Pattern {
            get {
                return this.pattern;
            }
            set {
                this.pattern = value;
            }
        }
        
        /// <summary>If this is a schema for an object, list the schema for each property of this object.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("properties")]
        public virtual Jsonschema.PropertiesData Properties {
            get {
                return this.properties;
            }
            set {
                this.properties = value;
            }
        }
        
        /// <summary>Whether this parameter may appear multiple times.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("repeated")]
        public virtual System.Nullable<bool> Repeated {
            get {
                return this.repeated;
            }
            set {
                this.repeated = value;
            }
        }
        
        /// <summary>Whether the parameter is required.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("required")]
        public virtual System.Nullable<bool> Required {
            get {
                return this.required;
            }
            set {
                this.required = value;
            }
        }
        
        /// <summary>The value type for this schema. A list of values can be found here: http://tools.ietf.org/html/draft-zyp-json-schema-03#section-5.1</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("type")]
        public virtual string Type {
            get {
                return this.type;
            }
            set {
                this.type = value;
            }
        }
        
        /// <summary>If this is a schema for an object, list the schema for each property of this object.</summary>
        public class PropertiesData : System.Collections.Generic.Dictionary<string, Jsonschema> {
        }
    }
    
    public class RestDescription : Google.Apis.Requests.IDirectResponseSchema {
        
        private RestDescription.AuthData auth;
        
        private string basePath;
        
        private string description;
        
        private string documentationLink;
        
        private IList<System.String> features;
        
        private RestDescription.IconsData icons;
        
        private string id;
        
        private string kind;
        
        private IList<System.String> labels;
        
        private RestDescription.MethodsData methods;
        
        private string name;
        
        private RestDescription.ParametersData parameters;
        
        private string protocol;
        
        private RestDescription.ResourcesData resources;
        
        private RestDescription.SchemasData schemas;
        
        private string title;
        
        private string version;
        
        private Google.Apis.Requests.RequestError error;
        
        private string eTag;
        
        /// <summary>Authentication information.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("auth")]
        public virtual RestDescription.AuthData Auth {
            get {
                return this.auth;
            }
            set {
                this.auth = value;
            }
        }
        
        /// <summary>The base URI path for REST requests.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("basePath")]
        public virtual string BasePath {
            get {
                return this.basePath;
            }
            set {
                this.basePath = value;
            }
        }
        
        /// <summary>The description of this API.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("description")]
        public virtual string Description {
            get {
                return this.description;
            }
            set {
                this.description = value;
            }
        }
        
        /// <summary>A link to human readable documentation for the API.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("documentationLink")]
        public virtual string DocumentationLink {
            get {
                return this.documentationLink;
            }
            set {
                this.documentationLink = value;
            }
        }
        
        /// <summary>A list of supported features for this API.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("features")]
        public virtual IList<System.String> Features {
            get {
                return this.features;
            }
            set {
                this.features = value;
            }
        }
        
        /// <summary>Links to 16x16 and 32x32 icons representing the API.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("icons")]
        public virtual RestDescription.IconsData Icons {
            get {
                return this.icons;
            }
            set {
                this.icons = value;
            }
        }
        
        /// <summary>The id of this API.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("id")]
        public virtual string Id {
            get {
                return this.id;
            }
            set {
                this.id = value;
            }
        }
        
        /// <summary>The kind for this response.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind {
            get {
                return this.kind;
            }
            set {
                this.kind = value;
            }
        }
        
        /// <summary>Labels for the status of this API, such as labs or deprecated.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("labels")]
        public virtual IList<System.String> Labels {
            get {
                return this.labels;
            }
            set {
                this.labels = value;
            }
        }
        
        /// <summary>API-level methods for this API.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("methods")]
        public virtual RestDescription.MethodsData Methods {
            get {
                return this.methods;
            }
            set {
                this.methods = value;
            }
        }
        
        /// <summary>The name of this API.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("name")]
        public virtual string Name {
            get {
                return this.name;
            }
            set {
                this.name = value;
            }
        }
        
        /// <summary>Common parameters that apply across all apis.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("parameters")]
        public virtual RestDescription.ParametersData Parameters {
            get {
                return this.parameters;
            }
            set {
                this.parameters = value;
            }
        }
        
        /// <summary>The protocol described by this document.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("protocol")]
        public virtual string Protocol {
            get {
                return this.protocol;
            }
            set {
                this.protocol = value;
            }
        }
        
        /// <summary>The resources in this API.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("resources")]
        public virtual RestDescription.ResourcesData Resources {
            get {
                return this.resources;
            }
            set {
                this.resources = value;
            }
        }
        
        /// <summary>The schemas for this API.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("schemas")]
        public virtual RestDescription.SchemasData Schemas {
            get {
                return this.schemas;
            }
            set {
                this.schemas = value;
            }
        }
        
        /// <summary>The title of this API.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("title")]
        public virtual string Title {
            get {
                return this.title;
            }
            set {
                this.title = value;
            }
        }
        
        /// <summary>The version of this API.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("version")]
        public virtual string Version {
            get {
                return this.version;
            }
            set {
                this.version = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("error")]
        public virtual Google.Apis.Requests.RequestError Error {
            get {
                return this.error;
            }
            set {
                this.error = value;
            }
        }
        
        public virtual string ETag {
            get {
                return this.eTag;
            }
            set {
                this.eTag = value;
            }
        }
        
        /// <summary>Authentication information.</summary>
        public class AuthData {
            
            private AuthData.Oauth2Data oauth2;
            
            /// <summary>OAuth 2.0 authentication information.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("oauth2")]
            public virtual AuthData.Oauth2Data Oauth2 {
                get {
                    return this.oauth2;
                }
                set {
                    this.oauth2 = value;
                }
            }
            
            /// <summary>OAuth 2.0 authentication information.</summary>
            public class Oauth2Data {
                
                private Oauth2Data.ScopesData scopes;
                
                /// <summary>Available OAuth 2.0 scopes.</summary>
                [Newtonsoft.Json.JsonPropertyAttribute("scopes")]
                public virtual Oauth2Data.ScopesData Scopes {
                    get {
                        return this.scopes;
                    }
                    set {
                        this.scopes = value;
                    }
                }
                
                /// <summary>Available OAuth 2.0 scopes.</summary>
                public class ScopesData : System.Collections.Generic.Dictionary<string, ScopesData.ScopesDataSchema> {
                    
                    /// <summary>The scope value.</summary>
                    public class ScopesDataSchema {
                        
                        private string description;
                        
                        /// <summary>Description of scope.</summary>
                        [Newtonsoft.Json.JsonPropertyAttribute("description")]
                        public virtual string Description {
                            get {
                                return this.description;
                            }
                            set {
                                this.description = value;
                            }
                        }
                    }
                }
            }
        }
        
        /// <summary>Links to 16x16 and 32x32 icons representing the API.</summary>
        public class IconsData {
            
            private string x16;
            
            private string x32;
            
            /// <summary>The url of the 16x16 icon.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("x16")]
            public virtual string X16 {
                get {
                    return this.x16;
                }
                set {
                    this.x16 = value;
                }
            }
            
            /// <summary>The url of the 32x32 icon.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("x32")]
            public virtual string X32 {
                get {
                    return this.x32;
                }
                set {
                    this.x32 = value;
                }
            }
        }
        
        /// <summary>API-level methods for this API.</summary>
        public class MethodsData : System.Collections.Generic.Dictionary<string, Restmethod> {
        }
        
        /// <summary>Common parameters that apply across all apis.</summary>
        public class ParametersData : System.Collections.Generic.Dictionary<string, Jsonschema> {
        }
        
        /// <summary>The resources in this API.</summary>
        public class ResourcesData : System.Collections.Generic.Dictionary<string, Restresource> {
        }
        
        /// <summary>The schemas for this API.</summary>
        public class SchemasData : System.Collections.Generic.Dictionary<string, Jsonschema> {
        }
    }
    
    public class Restmethod {
        
        private string description;
        
        private string httpMethod;
        
        private string id;
        
        private Restmethod.MediaUploadData mediaUpload;
        
        private IList<System.String> parameterOrder;
        
        private Restmethod.ParametersData parameters;
        
        private string path;
        
        private Restmethod.RequestData request;
        
        private Restmethod.ResponseData response;
        
        private IList<System.String> scopes;
        
        /// <summary>Description of this method.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("description")]
        public virtual string Description {
            get {
                return this.description;
            }
            set {
                this.description = value;
            }
        }
        
        /// <summary>HTTP method used by this method.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("httpMethod")]
        public virtual string HttpMethod {
            get {
                return this.httpMethod;
            }
            set {
                this.httpMethod = value;
            }
        }
        
        /// <summary>A unique ID for this method. This property can be used to match methods between different versions of Discovery.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("id")]
        public virtual string Id {
            get {
                return this.id;
            }
            set {
                this.id = value;
            }
        }
        
        /// <summary>Media upload parameters.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("mediaUpload")]
        public virtual Restmethod.MediaUploadData MediaUpload {
            get {
                return this.mediaUpload;
            }
            set {
                this.mediaUpload = value;
            }
        }
        
        /// <summary>Ordered list of required parameters, serves as a hint to clients on how to structure their method signatures. The array is ordered such that the &quot;most-significant&quot; parameter appears first.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("parameterOrder")]
        public virtual IList<System.String> ParameterOrder {
            get {
                return this.parameterOrder;
            }
            set {
                this.parameterOrder = value;
            }
        }
        
        /// <summary>Details for all parameters in this method.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("parameters")]
        public virtual Restmethod.ParametersData Parameters {
            get {
                return this.parameters;
            }
            set {
                this.parameters = value;
            }
        }
        
        /// <summary>The URI path of this REST method. Should be used in conjunction with the basePath property at the api-level.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("path")]
        public virtual string Path {
            get {
                return this.path;
            }
            set {
                this.path = value;
            }
        }
        
        /// <summary>The schema for the request.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("request")]
        public virtual Restmethod.RequestData Request {
            get {
                return this.request;
            }
            set {
                this.request = value;
            }
        }
        
        /// <summary>The schema for the response.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("response")]
        public virtual Restmethod.ResponseData Response {
            get {
                return this.response;
            }
            set {
                this.response = value;
            }
        }
        
        /// <summary>OAuth 2.0 scopes applicable to this method.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("scopes")]
        public virtual IList<System.String> Scopes {
            get {
                return this.scopes;
            }
            set {
                this.scopes = value;
            }
        }
        
        /// <summary>Media upload parameters.</summary>
        public class MediaUploadData {
            
            private IList<System.String> accept;
            
            private string maxSize;
            
            private MediaUploadData.ProtocolsData protocols;
            
            /// <summary>MIME Media Ranges for acceptable media uploads to this method.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("accept")]
            public virtual IList<System.String> Accept {
                get {
                    return this.accept;
                }
                set {
                    this.accept = value;
                }
            }
            
            /// <summary>Maximum size of a media upload, such as &quot;1MB&quot;, &quot;2GB&quot; or &quot;3TB&quot;.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("maxSize")]
            public virtual string MaxSize {
                get {
                    return this.maxSize;
                }
                set {
                    this.maxSize = value;
                }
            }
            
            /// <summary>Supported upload protocols.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("protocols")]
            public virtual MediaUploadData.ProtocolsData Protocols {
                get {
                    return this.protocols;
                }
                set {
                    this.protocols = value;
                }
            }
            
            /// <summary>Supported upload protocols.</summary>
            public class ProtocolsData {
                
                private ProtocolsData.ResumableData resumable;
                
                private ProtocolsData.SimpleData simple;
                
                /// <summary>Supports the Resumable Media Upload protocol.</summary>
                [Newtonsoft.Json.JsonPropertyAttribute("resumable")]
                public virtual ProtocolsData.ResumableData Resumable {
                    get {
                        return this.resumable;
                    }
                    set {
                        this.resumable = value;
                    }
                }
                
                /// <summary>Supports uploading as a single HTTP request.</summary>
                [Newtonsoft.Json.JsonPropertyAttribute("simple")]
                public virtual ProtocolsData.SimpleData Simple {
                    get {
                        return this.simple;
                    }
                    set {
                        this.simple = value;
                    }
                }
                
                /// <summary>Supports the Resumable Media Upload protocol.</summary>
                public class ResumableData {
                    
                    private System.Nullable<bool> multipart;
                    
                    private string path;
                    
                    /// <summary>True if this endpoint supports uploading multipart media.</summary>
                    [Newtonsoft.Json.JsonPropertyAttribute("multipart")]
                    public virtual System.Nullable<bool> Multipart {
                        get {
                            return this.multipart;
                        }
                        set {
                            this.multipart = value;
                        }
                    }
                    
                    /// <summary>The URI path to be used for upload. Should be used in conjunction with the basePath property at the api-level.</summary>
                    [Newtonsoft.Json.JsonPropertyAttribute("path")]
                    public virtual string Path {
                        get {
                            return this.path;
                        }
                        set {
                            this.path = value;
                        }
                    }
                }
                
                /// <summary>Supports uploading as a single HTTP request.</summary>
                public class SimpleData {
                    
                    private System.Nullable<bool> multipart;
                    
                    private string path;
                    
                    /// <summary>True if this endpoint supports upload multipart media.</summary>
                    [Newtonsoft.Json.JsonPropertyAttribute("multipart")]
                    public virtual System.Nullable<bool> Multipart {
                        get {
                            return this.multipart;
                        }
                        set {
                            this.multipart = value;
                        }
                    }
                    
                    /// <summary>The URI path to be used for upload. Should be used in conjunction with the basePath property at the api-level.</summary>
                    [Newtonsoft.Json.JsonPropertyAttribute("path")]
                    public virtual string Path {
                        get {
                            return this.path;
                        }
                        set {
                            this.path = value;
                        }
                    }
                }
            }
        }
        
        /// <summary>Details for all parameters in this method.</summary>
        public class ParametersData : System.Collections.Generic.Dictionary<string, Jsonschema> {
        }
        
        /// <summary>The schema for the request.</summary>
        public class RequestData {
            
            private string refValue;
            
            /// <summary>Schema ID for the request schema.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("$ref")]
            public virtual string Ref {
                get {
                    return this.refValue;
                }
                set {
                    this.refValue = value;
                }
            }
        }
        
        /// <summary>The schema for the response.</summary>
        public class ResponseData {
            
            private string refValue;
            
            /// <summary>Schema ID for the response schema.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("$ref")]
            public virtual string Ref {
                get {
                    return this.refValue;
                }
                set {
                    this.refValue = value;
                }
            }
        }
    }
    
    public class Restresource {
        
        private Restresource.MethodsData methods;
        
        private Restresource.ResourcesData resources;
        
        /// <summary>Methods on this resource.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("methods")]
        public virtual Restresource.MethodsData Methods {
            get {
                return this.methods;
            }
            set {
                this.methods = value;
            }
        }
        
        /// <summary>Sub-resources on this resource.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("resources")]
        public virtual Restresource.ResourcesData Resources {
            get {
                return this.resources;
            }
            set {
                this.resources = value;
            }
        }
        
        /// <summary>Methods on this resource.</summary>
        public class MethodsData : System.Collections.Generic.Dictionary<string, Restmethod> {
        }
        
        /// <summary>Sub-resources on this resource.</summary>
        public class ResourcesData : System.Collections.Generic.Dictionary<string, Restresource> {
        }
    }
}
namespace Google.Apis.Discovery.v1 {
    using System;
    using System.IO;
    using System.Collections.Generic;
    using Google.Apis;
    using Google.Apis.Discovery;
    
    
    public partial class DiscoveryService : Google.Apis.Discovery.IRequestProvider {
        
        private Google.Apis.Discovery.IService genericService;
        
        private Google.Apis.Authentication.IAuthenticator authenticator;
        
        private const string DiscoveryDocument = "{\"kind\":\"discovery#restDescription\",\"id\":\"discovery:v1\",\"name\":\"discovery\",\"versi" +
            "on\":\"v1\",\"title\":\"APIs Discovery Service\",\"description\":\"Lets you discover infor" +
            "mation about other Google APIs, such as what APIs are available, the resource an" +
            "d method details for each API\",\"icons\":{\"x16\":\"http://www.google.com/images/icon" +
            "s/feature/filing_cabinet_search-g16.png\",\"x32\":\"http://www.google.com/images/ico" +
            "ns/feature/filing_cabinet_search-g32.png\"},\"documentationLink\":\"http://code.goog" +
            "le.com/apis/discovery\",\"labels\":[\"labs\"],\"protocol\":\"rest\",\"basePath\":\"/discover" +
            "y/v1/\",\"parameters\":{\"alt\":{\"type\":\"string\",\"description\":\"Data format for the r" +
            "esponse.\",\"default\":\"json\",\"enum\":[\"json\"],\"enumDescriptions\":[\"Responses with C" +
            "ontent-Type of application/json\"],\"location\":\"query\"},\"fields\":{\"type\":\"string\"," +
            "\"description\":\"Selector specifying which fields to include in a partial response" +
            ".\",\"location\":\"query\"},\"key\":{\"type\":\"string\",\"description\":\"API key. Your API k" +
            "ey identifies your project and provides you with API access, quota, and reports." +
            " Required unless you provide an OAuth 2.0 token.\",\"location\":\"query\"},\"oauth_tok" +
            "en\":{\"type\":\"string\",\"description\":\"OAuth 2.0 token for the current user.\",\"loca" +
            "tion\":\"query\"},\"prettyPrint\":{\"type\":\"boolean\",\"description\":\"Returns response w" +
            "ith indentations and line breaks.\",\"default\":\"true\",\"location\":\"query\"},\"userIp\"" +
            ":{\"type\":\"string\",\"description\":\"IP address of the site where the request origin" +
            "ates. Use this if you want to enforce per-user limits.\",\"location\":\"query\"}},\"sc" +
            "hemas\":{\"DirectoryList\":{\"id\":\"DirectoryList\",\"type\":\"object\",\"properties\":{\"ite" +
            "ms\":{\"type\":\"array\",\"description\":\"The individual directory entries. One entry p" +
            "er api/version pair.\",\"items\":{\"type\":\"object\",\"properties\":{\"description\":{\"typ" +
            "e\":\"string\",\"description\":\"The description of this API.\"},\"discoveryLink\":{\"type" +
            "\":\"string\",\"description\":\"A link to the discovery document.\"},\"documentationLink" +
            "\":{\"type\":\"string\",\"description\":\"A link to human readable documentation for the" +
            " API.\"},\"icons\":{\"type\":\"object\",\"description\":\"Links to 16x16 and 32x32 icons r" +
            "epresenting the API.\",\"properties\":{\"x16\":{\"type\":\"string\",\"description\":\"The ur" +
            "l of the 16x16 icon.\"},\"x32\":{\"type\":\"string\",\"description\":\"The url of the 32x3" +
            "2 icon.\"}}},\"id\":{\"type\":\"string\",\"description\":\"The id of this API.\"},\"kind\":{\"" +
            "type\":\"string\",\"description\":\"The kind for this response.\",\"default\":\"discovery#" +
            "directoryItem\"},\"labels\":{\"type\":\"array\",\"description\":\"Labels for the status of" +
            " this API, such as labs or deprecated.\",\"items\":{\"type\":\"string\"}},\"name\":{\"type" +
            "\":\"string\",\"description\":\"The name of the API.\"},\"preferred\":{\"type\":\"boolean\",\"" +
            "description\":\"True if this version is the preferred version to use.\"},\"title\":{\"" +
            "type\":\"string\",\"description\":\"The title of this API.\"},\"version\":{\"type\":\"string" +
            "\",\"description\":\"The version of the API.\"}}}},\"kind\":{\"type\":\"string\",\"descripti" +
            "on\":\"The kind for this response.\",\"default\":\"discovery#directoryList\"}}},\"Jsonsc" +
            "hema\":{\"id\":\"Jsonschema\",\"type\":\"object\",\"properties\":{\"$ref\":{\"type\":\"string\",\"" +
            "description\":\"A reference to another schema. The value of this property is the \\" +
            "\"id\\\" of another schema.\"},\"additionalProperties\":{\"$ref\":\"Jsonschema\",\"descript" +
            "ion\":\"If this is a schema for an object, this property is the schema for any add" +
            "itional properties with dynamic keys on this object.\"},\"default\":{\"type\":\"string" +
            "\",\"description\":\"The default value of this property (if one exists).\"},\"descript" +
            "ion\":{\"type\":\"string\",\"description\":\"A description of this object.\"},\"enum\":{\"ty" +
            "pe\":\"array\",\"description\":\"Values this parameter may take (if it is an enum).\",\"" +
            "items\":{\"type\":\"string\"}},\"enumDescriptions\":{\"type\":\"array\",\"description\":\"The " +
            "descriptions for the enums. Each position maps to the corresponding value in the" +
            " \\\"enum\\\" array.\",\"items\":{\"type\":\"string\"}},\"format\":{\"type\":\"string\",\"descript" +
            "ion\":\"An additional regular expression or key that helps constrain the value. Fo" +
            "r more details see: http://tools.ietf.org/html/draft-zyp-json-schema-03#section-" +
            "5.23\"},\"id\":{\"type\":\"string\",\"description\":\"Unique identifier for this schema.\"}" +
            ",\"items\":{\"$ref\":\"Jsonschema\",\"description\":\"If this is a schema for an array, t" +
            "his property is the schema for each element in the array.\"},\"location\":{\"type\":\"" +
            "string\",\"description\":\"Whether this parameter goes in the query or the path for " +
            "REST requests.\"},\"maximum\":{\"type\":\"string\",\"description\":\"The maximum value of " +
            "this parameter.\"},\"minimum\":{\"type\":\"string\",\"description\":\"The minimum value of" +
            " this parameter.\"},\"pattern\":{\"type\":\"string\",\"description\":\"The regular express" +
            "ion this parameter must conform to.\"},\"properties\":{\"type\":\"object\",\"description" +
            "\":\"If this is a schema for an object, list the schema for each property of this " +
            "object.\",\"additionalProperties\":{\"$ref\":\"Jsonschema\"}},\"repeated\":{\"type\":\"boole" +
            "an\",\"description\":\"Whether this parameter may appear multiple times.\"},\"required" +
            "\":{\"type\":\"boolean\",\"description\":\"Whether the parameter is required.\"},\"type\":{" +
            "\"type\":\"string\",\"description\":\"The value type for this schema. A list of values " +
            "can be found here: http://tools.ietf.org/html/draft-zyp-json-schema-03#section-5" +
            ".1\"}}},\"RestDescription\":{\"id\":\"RestDescription\",\"type\":\"object\",\"properties\":{\"" +
            "auth\":{\"type\":\"object\",\"description\":\"Authentication information.\",\"properties\":" +
            "{\"oauth2\":{\"type\":\"object\",\"description\":\"OAuth 2.0 authentication information.\"" +
            ",\"properties\":{\"scopes\":{\"type\":\"object\",\"description\":\"Available OAuth 2.0 scop" +
            "es.\",\"additionalProperties\":{\"type\":\"object\",\"description\":\"The scope value.\",\"p" +
            "roperties\":{\"description\":{\"type\":\"string\",\"description\":\"Description of scope.\"" +
            "}}}}}}}},\"basePath\":{\"type\":\"string\",\"description\":\"The base URI path for REST r" +
            "equests.\"},\"description\":{\"type\":\"string\",\"description\":\"The description of this" +
            " API.\"},\"documentationLink\":{\"type\":\"string\",\"description\":\"A link to human read" +
            "able documentation for the API.\"},\"features\":{\"type\":\"array\",\"description\":\"A li" +
            "st of supported features for this API.\",\"items\":{\"type\":\"string\"}},\"icons\":{\"typ" +
            "e\":\"object\",\"description\":\"Links to 16x16 and 32x32 icons representing the API.\"" +
            ",\"properties\":{\"x16\":{\"type\":\"string\",\"description\":\"The url of the 16x16 icon.\"" +
            "},\"x32\":{\"type\":\"string\",\"description\":\"The url of the 32x32 icon.\"}}},\"id\":{\"ty" +
            "pe\":\"string\",\"description\":\"The id of this API.\"},\"kind\":{\"type\":\"string\",\"descr" +
            "iption\":\"The kind for this response.\",\"default\":\"discovery#restDescription\"},\"la" +
            "bels\":{\"type\":\"array\",\"description\":\"Labels for the status of this API, such as " +
            "labs or deprecated.\",\"items\":{\"type\":\"string\"}},\"methods\":{\"type\":\"object\",\"desc" +
            "ription\":\"API-level methods for this API.\",\"additionalProperties\":{\"$ref\":\"Restm" +
            "ethod\"}},\"name\":{\"type\":\"string\",\"description\":\"The name of this API.\"},\"paramet" +
            "ers\":{\"type\":\"object\",\"description\":\"Common parameters that apply across all api" +
            "s.\",\"additionalProperties\":{\"$ref\":\"Jsonschema\"}},\"protocol\":{\"type\":\"string\",\"d" +
            "escription\":\"The protocol described by this document.\",\"default\":\"rest\"},\"resour" +
            "ces\":{\"type\":\"object\",\"description\":\"The resources in this API.\",\"additionalProp" +
            "erties\":{\"$ref\":\"Restresource\"}},\"schemas\":{\"type\":\"object\",\"description\":\"The s" +
            "chemas for this API.\",\"additionalProperties\":{\"$ref\":\"Jsonschema\"}},\"title\":{\"ty" +
            "pe\":\"string\",\"description\":\"The title of this API.\"},\"version\":{\"type\":\"string\"," +
            "\"description\":\"The version of this API.\"}}},\"Restmethod\":{\"id\":\"Restmethod\",\"typ" +
            "e\":\"object\",\"properties\":{\"description\":{\"type\":\"string\",\"description\":\"Descript" +
            "ion of this method.\"},\"httpMethod\":{\"type\":\"string\",\"description\":\"HTTP method u" +
            "sed by this method.\"},\"id\":{\"type\":\"string\",\"description\":\"A unique ID for this " +
            "method. This property can be used to match methods between different versions of" +
            " Discovery.\"},\"mediaUpload\":{\"type\":\"object\",\"description\":\"Media upload paramet" +
            "ers.\",\"properties\":{\"accept\":{\"type\":\"array\",\"description\":\"MIME Media Ranges fo" +
            "r acceptable media uploads to this method.\",\"items\":{\"type\":\"string\"}},\"maxSize\"" +
            ":{\"type\":\"string\",\"description\":\"Maximum size of a media upload, such as \\\"1MB\\\"" +
            ", \\\"2GB\\\" or \\\"3TB\\\".\"},\"protocols\":{\"type\":\"object\",\"description\":\"Supported up" +
            "load protocols.\",\"properties\":{\"resumable\":{\"type\":\"object\",\"description\":\"Suppo" +
            "rts the Resumable Media Upload protocol.\",\"properties\":{\"multipart\":{\"type\":\"boo" +
            "lean\",\"description\":\"True if this endpoint supports uploading multipart media.\"," +
            "\"default\":\"true\"},\"path\":{\"type\":\"string\",\"description\":\"The URI path to be used" +
            " for upload. Should be used in conjunction with the basePath property at the api" +
            "-level.\"}}},\"simple\":{\"type\":\"object\",\"description\":\"Supports uploading as a sin" +
            "gle HTTP request.\",\"properties\":{\"multipart\":{\"type\":\"boolean\",\"description\":\"Tr" +
            "ue if this endpoint supports upload multipart media.\",\"default\":\"true\"},\"path\":{" +
            "\"type\":\"string\",\"description\":\"The URI path to be used for upload. Should be use" +
            "d in conjunction with the basePath property at the api-level.\"}}}}}}},\"parameter" +
            "Order\":{\"type\":\"array\",\"description\":\"Ordered list of required parameters, serve" +
            "s as a hint to clients on how to structure their method signatures. The array is" +
            " ordered such that the \\\"most-significant\\\" parameter appears first.\",\"items\":{\"" +
            "type\":\"string\"}},\"parameters\":{\"type\":\"object\",\"description\":\"Details for all pa" +
            "rameters in this method.\",\"additionalProperties\":{\"$ref\":\"Jsonschema\"}},\"path\":{" +
            "\"type\":\"string\",\"description\":\"The URI path of this REST method. Should be used " +
            "in conjunction with the basePath property at the api-level.\"},\"request\":{\"type\":" +
            "\"object\",\"description\":\"The schema for the request.\",\"properties\":{\"$ref\":{\"type" +
            "\":\"string\",\"description\":\"Schema ID for the request schema.\"}}},\"response\":{\"typ" +
            "e\":\"object\",\"description\":\"The schema for the response.\",\"properties\":{\"$ref\":{\"" +
            "type\":\"string\",\"description\":\"Schema ID for the response schema.\"}}},\"scopes\":{\"" +
            "type\":\"array\",\"description\":\"OAuth 2.0 scopes applicable to this method.\",\"items" +
            "\":{\"type\":\"string\"}}}},\"Restresource\":{\"id\":\"Restresource\",\"type\":\"object\",\"prop" +
            "erties\":{\"methods\":{\"type\":\"object\",\"description\":\"Methods on this resource.\",\"a" +
            "dditionalProperties\":{\"$ref\":\"Restmethod\"}},\"resources\":{\"type\":\"object\",\"descri" +
            "ption\":\"Sub-resources on this resource.\",\"additionalProperties\":{\"$ref\":\"Restres" +
            "ource\"}}}}},\"resources\":{\"apis\":{\"methods\":{\"getRest\":{\"id\":\"discovery.apis.getR" +
            "est\",\"path\":\"apis/{api}/{version}/rest\",\"httpMethod\":\"GET\",\"description\":\"Retrie" +
            "ve the description of a particular version of an api.\",\"parameters\":{\"api\":{\"typ" +
            "e\":\"string\",\"description\":\"The name of the API.\",\"required\":true,\"location\":\"pat" +
            "h\"},\"version\":{\"type\":\"string\",\"description\":\"The version of the API.\",\"required" +
            "\":true,\"location\":\"path\"}},\"parameterOrder\":[\"api\",\"version\"],\"response\":{\"$ref\"" +
            ":\"RestDescription\"}},\"list\":{\"id\":\"discovery.apis.list\",\"path\":\"apis\",\"httpMetho" +
            "d\":\"GET\",\"description\":\"Retrieve the list of APIs supported at this endpoint.\",\"" +
            "parameters\":{\"label\":{\"type\":\"string\",\"description\":\"Only include APIs with a ma" +
            "tching label, such as \'graduated\' or \'labs\'.\",\"enum\":[\"deprecated\",\"graduated\",\"" +
            "labs\"],\"enumDescriptions\":[\"APIs that have been deprecated.\",\"Supported APIs tha" +
            "t have graduated from labs.\",\"APIs that are experimental\"],\"location\":\"query\"},\"" +
            "name\":{\"type\":\"string\",\"description\":\"Only include APIs with the given name.\",\"l" +
            "ocation\":\"query\"},\"preferred\":{\"type\":\"boolean\",\"description\":\"Return only the p" +
            "referred version of an API.\",\"location\":\"query\"}},\"response\":{\"$ref\":\"DirectoryL" +
            "ist\"}}}}}}";
        
        private const string Version = "v1";
        
        private const string Name = "discovery";
        
        private const string BaseUri = "https://www.googleapis.com/discovery/v1/";
        
        private const Google.Apis.Discovery.DiscoveryVersion DiscoveryVersionUsed = Google.Apis.Discovery.DiscoveryVersion.Version_1_0;
        
        private string key;
        
        protected DiscoveryService(Google.Apis.Discovery.IService genericService, Google.Apis.Authentication.IAuthenticator authenticator) {
            this.genericService = genericService;
            this.authenticator = authenticator;
            this.apis = new ApisResource(this);
        }
        
        public DiscoveryService() : 
                this(Google.Apis.Authentication.NullAuthenticator.Instance) {
        }
        
        public DiscoveryService(Google.Apis.Authentication.IAuthenticator authenticator) : 
                this(new Google.Apis.Discovery.DiscoveryService(new Google.Apis.Discovery.StringDiscoveryDevice(DiscoveryDocument)).GetService(DiscoveryService.DiscoveryVersionUsed, new Google.Apis.Discovery.FactoryParameterV1_0(new System.Uri(DiscoveryService.BaseUri))), authenticator) {
        }
        
        /// <summary>Sets the API-Key (or DeveloperKey) which this service uses for all requests</summary>
        public virtual string Key {
            get {
                return this.key;
            }
            set {
                this.key = value;
            }
        }
        
        public virtual Google.Apis.Requests.IRequest CreateRequest(string resource, string method) {
            Google.Apis.Requests.IRequest request = this.genericService.CreateRequest(resource, method);
            if (!string.IsNullOrEmpty(Key)) {
                request = request.WithKey(this.Key);
            }
            return request.WithAuthentication(authenticator);
        }
        
        public virtual void RegisterSerializer(Google.Apis.ISerializer serializer) {
            genericService.Serializer = serializer;
        }
        
        public virtual string SerializeObject(object obj) {
            return genericService.SerializeRequest(obj);
        }
        
        public virtual T DeserializeResponse<T>(Google.Apis.Requests.IResponse response)
         {
            return genericService.DeserializeResponse<T>(response);
        }
    }
    
    public class ApisResource {
        
        private Google.Apis.Discovery.IRequestProvider service;
        
        private const string Resource = "apis";
        
        public ApisResource(DiscoveryService service) {
            this.service = service;
        }
        
        /// <summary>Retrieve the description of a particular version of an api.</summary>
        /// <param name="api">Required - The name of the API.</param>
        /// <param name="version">Required - The version of the API.</param>
        public virtual GetRestRequest GetRest(string api, string version) {
            return new GetRestRequest(service, api, version);
        }
        
        /// <summary>Retrieve the list of APIs supported at this endpoint.</summary>
        public virtual ListRequest List() {
            return new ListRequest(service);
        }
        
        /// <summary>Only include APIs with a matching label, such as &apos;graduated&apos; or &apos;labs&apos;.</summary>
        [System.ComponentModel.TypeConverterAttribute(typeof(Google.Apis.Util.EnumStringValueTypeConverter))]
        public enum Label {
            
            /// <summary>APIs that have been deprecated.</summary>
            [Google.Apis.Util.StringValueAttribute("deprecated")]
            Deprecated,
            
            /// <summary>Supported APIs that have graduated from labs.</summary>
            [Google.Apis.Util.StringValueAttribute("graduated")]
            Graduated,
            
            /// <summary>APIs that are experimental</summary>
            [Google.Apis.Util.StringValueAttribute("labs")]
            Labs,
        }
        
        public class GetRestRequest : Google.Apis.Requests.ServiceRequest<Google.Apis.Discovery.v1.Data.RestDescription> {
            
            private string api;
            
            private string version;
            
            public GetRestRequest(Google.Apis.Discovery.IRequestProvider service, string api, string version) : 
                    base(service) {
                this.api = api;
                this.version = version;
            }
            
            /// <summary>The name of the API.</summary>
            [Google.Apis.Util.RequestParameterAttribute("api")]
            public virtual string Api {
                get {
                    return this.api;
                }
            }
            
            /// <summary>The version of the API.</summary>
            [Google.Apis.Util.RequestParameterAttribute("version")]
            public virtual string Version {
                get {
                    return this.version;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "apis";
                }
            }
            
            protected override string MethodName {
                get {
                    return "getRest";
                }
            }
        }
        
        public class ListRequest : Google.Apis.Requests.ServiceRequest<Google.Apis.Discovery.v1.Data.DirectoryList> {
            
            private Label? label;
            
            private string name;
            
            private System.Boolean? preferred;
            
            public ListRequest(Google.Apis.Discovery.IRequestProvider service) : 
                    base(service) {
            }
            
            /// <summary>Only include APIs with a matching label, such as 'graduated' or 'labs'.</summary>
            [Google.Apis.Util.RequestParameterAttribute("label")]
            public virtual Label? Label {
                get {
                    return this.label;
                }
                set {
                    this.label = value;
                }
            }
            
            /// <summary>Only include APIs with the given name.</summary>
            [Google.Apis.Util.RequestParameterAttribute("name")]
            public virtual string Name {
                get {
                    return this.name;
                }
                set {
                    this.name = value;
                }
            }
            
            /// <summary>Return only the preferred version of an API.</summary>
            [Google.Apis.Util.RequestParameterAttribute("preferred")]
            public virtual System.Boolean? Preferred {
                get {
                    return this.preferred;
                }
                set {
                    this.preferred = value;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "apis";
                }
            }
            
            protected override string MethodName {
                get {
                    return "list";
                }
            }
        }
    }
    
    public partial class DiscoveryService {
        
        private const string Resource = "";
        
        private ApisResource apis;
        
        private Google.Apis.Discovery.IRequestProvider service {
            get {
                return this;
            }
        }
        
        public virtual ApisResource Apis {
            get {
                return this.apis;
            }
        }
    }
}
