{
  "version": "v1beta1",
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "kind": "discovery#restDescription",
  "description": "API for provisioning and managing identity resources.",
  "servicePath": "",
  "basePath": "",
  "id": "cloudidentity:v1beta1",
  "documentationLink": "https://cloud.google.com/identity/",
  "revision": "20190503",
  "discoveryVersion": "v1",
  "version_module": true,
  "protocol": "rest",
  "canonicalName": "Cloud Identity",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        }
      }
    }
  },
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "ownerDomain": "google.com",
  "name": "cloudidentity",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "title": "Cloud Identity API",
  "ownerName": "Google",
  "resources": {
    "groups": {
      "methods": {
        "delete": {
          "description": "Deletes a Group.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups"
          ],
          "flatPath": "v1beta1/groups/{groupsId}",
          "id": "cloudidentity.groups.delete",
          "path": "v1beta1/{+name}"
        },
        "create": {
          "description": "Creates a Group.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups"
          ],
          "flatPath": "v1beta1/groups",
          "id": "cloudidentity.groups.create",
          "path": "v1beta1/groups"
        },
        "lookup": {
          "description": "Looks up [resource\nname](https://cloud.google.com/apis/design/resource_names) of a Group by\nits EntityKey.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly"
          ],
          "flatPath": "v1beta1/groups:lookup",
          "id": "cloudidentity.groups.lookup",
          "path": "v1beta1/groups:lookup"
        },
        "search": {
          "flatPath": "v1beta1/groups:search",
          "path": "v1beta1/groups:search",
          "id": "cloudidentity.groups.search",
          "description": "Searches for Groups.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups"
          ],
          "flatPath": "v1beta1/groups/{groupsId}",
          "id": "cloudidentity.groups.patch",
          "path": "v1beta1/{+name}",
          "description": "Updates a Group."
        },
        "get": {
          "path": "v1beta1/{+name}",
          "id": "cloudidentity.groups.get",
          "description": "Retrieves a Group.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly"
          ],
          "flatPath": "v1beta1/groups/{groupsId}"
        }
      },
      "resources": {
        "memberships": {
          "methods": {
            "delete": {
              "description": "Deletes a Membership.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups"
              ],
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}",
              "path": "v1beta1/{+name}",
              "id": "cloudidentity.groups.memberships.delete"
            },
            "get": {
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}",
              "path": "v1beta1/{+name}",
              "id": "cloudidentity.groups.memberships.get",
              "description": "Retrieves a Membership.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly"
              ],
              "flatPath": "v1beta1/groups/{groupsId}/memberships",
              "path": "v1beta1/{+parent}/memberships",
              "id": "cloudidentity.groups.memberships.list",
              "description": "List Memberships within a Group."
            },
            "create": {
              "description": "Creates a Membership.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups"
              ],
              "flatPath": "v1beta1/groups/{groupsId}/memberships",
              "id": "cloudidentity.groups.memberships.create",
              "path": "v1beta1/{+parent}/memberships"
            },
            "lookup": {
              "description": "Looks up [resource\nname](https://cloud.google.com/apis/design/resource_names) of a Membership\nwithin a Group by member's EntityKey.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly"
              ],
              "flatPath": "v1beta1/groups/{groupsId}/memberships:lookup",
              "path": "v1beta1/{+parent}/memberships:lookup",
              "id": "cloudidentity.groups.memberships.lookup"
            }
          }
        }
      }
    }
  }
}
