{
  "version": "v1",
  "baseUrl": "https://cloudsearch.googleapis.com/",
  "servicePath": "",
  "kind": "discovery#restDescription",
  "description": "Cloud Search provides cloud-based search capabilities over G Suite data.  The Cloud Search API allows indexing of non-G Suite data into Cloud Search.",
  "basePath": "",
  "revision": "20190925",
  "documentationLink": "https://developers.google.com/cloud-search/docs/guides/",
  "id": "cloudsearch:v1",
  "discoveryVersion": "v1",
  "version_module": true,
  "schemas": {
    "SuggestResult": {
      "id": "SuggestResult",
      "description": "One suggestion result.",
      "type": "object",
      "properties": {
        "peopleSuggestion": {
          "$ref": "PeopleSuggestion",
          "description": "This is present when the suggestion indicates a person. It\ncontains more information about the person - like their email ID,\nname etc."
        },
        "source": {
          "$ref": "Source",
          "description": "The source of the suggestion."
        },
        "querySuggestion": {
          "$ref": "QuerySuggestion",
          "description": "This field will be present if the suggested query is a word/phrase\ncompletion."
        },
        "suggestedQuery": {
          "description": "The suggested query that will be used for search, when the user\nclicks on the suggestion",
          "type": "string"
        }
      }
    },
    "Operation": {
      "description": "This resource represents a long-running operation that is the result of a\nnetwork API call.",
      "type": "object",
      "properties": {
        "done": {
          "description": "If the value is `false`, it means the operation is still in progress.\nIf `true`, the operation is completed, and either `error` or `response` is\navailable.",
          "type": "boolean"
        },
        "name": {
          "type": "string",
          "description": "The server-assigned name, which is only unique within the same service that\noriginally returns it. If you use the default HTTP mapping, the\n`name` should be a resource name ending with `operations/{unique_id}`."
        },
        "error": {
          "$ref": "Status",
          "description": "The error result of the operation in case of failure or cancellation."
        },
        "metadata": {
          "description": "Service-specific metadata associated with the operation.  It typically\ncontains progress information and common metadata such as create time.\nSome services might not provide such metadata.  Any method that returns a\nlong-running operation should document the metadata type, if any.",
          "type": "object",
          "additionalProperties": {
            "type": "any",
            "description": "Properties of the object. Contains field @type with type URL."
          }
        }
      },
      "id": "Operation"
    },
    "DataSourceRestriction": {
      "description": "Restriction on Datasource.",
      "type": "object",
      "properties": {
        "source": {
          "$ref": "Source",
          "description": "The source of restriction."
        },
        "filterOptions": {
          "description": "Filter options restricting the results. If multiple filters\nare present, they are grouped by object type before joining.\nFilters with the same object type are joined conjunctively, then\nthe resulting expressions are joined disjunctively.\n\nThe maximum number of elements is 20.\n\nNOTE: Suggest API supports only few filters at the moment:\n  \"objecttype\", \"type\" and \"mimetype\".\nFor now, schema specific filters cannot be used to filter suggestions.",
          "type": "array",
          "items": {
            "$ref": "FilterOptions"
          }
        }
      },
      "id": "DataSourceRestriction"
    },
    "CustomerSessionStats": {
      "type": "object",
      "properties": {
        "date": {
          "description": "Date for which session stats were calculated. Stats calculated on the next\nday close to midnight are returned.",
          "$ref": "Date"
        },
        "searchSessionsCount": {
          "description": "The count of search sessions on the day",
          "format": "int64",
          "type": "string"
        }
      },
      "id": "CustomerSessionStats"
    },
    "UpdateSchemaRequest": {
      "type": "object",
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "validateOnly": {
          "description": "If true, the request will be validated without side effects.",
          "type": "boolean"
        },
        "schema": {
          "description": "The new schema for the source.",
          "$ref": "Schema"
        }
      },
      "id": "UpdateSchemaRequest"
    },
    "Status": {
      "type": "object",
      "properties": {
        "details": {
          "description": "A list of messages that carry the error details.  There is a common set of\nmessage types for APIs to use.",
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": {
              "type": "any",
              "description": "Properties of the object. Contains field @type with type URL."
            }
          }
        },
        "code": {
          "type": "integer",
          "description": "The status code, which should be an enum value of google.rpc.Code.",
          "format": "int32"
        },
        "message": {
          "description": "A developer-facing error message, which should be in English. Any\nuser-facing error message should be localized and sent in the\ngoogle.rpc.Status.details field, or localized by the client.",
          "type": "string"
        }
      },
      "id": "Status",
      "description": "The `Status` type defines a logical error model that is suitable for\ndifferent programming environments, including REST APIs and RPC APIs. It is\nused by [gRPC](https://github.com/grpc). Each `Status` message contains\nthree pieces of data: error code, error message, and error details.\n\nYou can find out more about this error model and how to work with it in the\n[API Design Guide](https://cloud.google.com/apis/design/errors)."
    },
    "DriveLocationRestrict": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "enum": [
            "UNSPECIFIED",
            "TRASHED",
            "STARRED"
          ]
        }
      },
      "id": "DriveLocationRestrict",
      "description": "Drive location search restricts (e.g. \"is:starred\")."
    },
    "RetrievalImportance": {
      "type": "object",
      "properties": {
        "importance": {
          "enum": [
            "DEFAULT",
            "HIGHEST",
            "HIGH",
            "LOW",
            "NONE"
          ],
          "description": "Indicates the ranking importance given to property when it is matched\nduring retrieval. Once set, the token importance of a property cannot be\nchanged.",
          "type": "string",
          "enumDescriptions": [
            "Treat the match like a body text match.",
            "Treat the match like a match against title of the item.",
            "Treat the match with higher importance than body text.",
            "Treat the match with lower importance than body text.",
            "Do not match against this field during retrieval. The property can still\nbe used for operator matching, faceting, and suggest if\ndesired."
          ]
        }
      },
      "id": "RetrievalImportance"
    },
    "GetCustomerQueryStatsResponse": {
      "type": "object",
      "properties": {
        "stats": {
          "type": "array",
          "items": {
            "$ref": "CustomerQueryStats"
          }
        }
      },
      "id": "GetCustomerQueryStatsResponse"
    },
    "DisplayedProperty": {
      "description": "A reference to a top-level property within the object that should be\ndisplayed in search results. The values of the chosen properties will be\ndisplayed in the search results along with the\ndislpay label\nfor that property if one is specified. If a display label is not specified,\nonly the values will be shown.",
      "type": "object",
      "properties": {
        "propertyName": {
          "description": "The name of the top-level property as defined in a property definition\nfor the object. If the name is not a defined property in the schema, an\nerror will be given when attempting to update the schema.",
          "type": "string"
        }
      },
      "id": "DisplayedProperty"
    },
    "ItemStatus": {
      "description": "This contains item's status and any errors.",
      "type": "object",
      "properties": {
        "processingErrors": {
          "description": "Error details in case the item is in ERROR state.",
          "type": "array",
          "items": {
            "$ref": "ProcessingError"
          }
        },
        "code": {
          "type": "string",
          "enumDescriptions": [
            "Input-only value.  Used with\nItems.list\nto list all items in the queue, regardless of status.",
            "Error encountered by Cloud Search while processing this item.\nDetails of the error are in\nrepositoryError.",
            "Item has been modified in the repository, and is out of date with\nthe version previously accepted into Cloud Search.",
            "Item is known to exist in the repository, but is not yet accepted by\nCloud Search.\nAn item can be in this state when\nItems.push\nhas been called for\nan item of this name that did not exist previously.",
            "API has accepted the up-to-date data of this item."
          ],
          "enum": [
            "CODE_UNSPECIFIED",
            "ERROR",
            "MODIFIED",
            "NEW_ITEM",
            "ACCEPTED"
          ],
          "description": "Status code."
        },
        "repositoryErrors": {
          "description": "Repository error reported by connector.",
          "type": "array",
          "items": {
            "$ref": "RepositoryError"
          }
        }
      },
      "id": "ItemStatus"
    },
    "FieldViolation": {
      "type": "object",
      "properties": {
        "field": {
          "description": "Path of field with violation.",
          "type": "string"
        },
        "description": {
          "description": "Description of the error.",
          "type": "string"
        }
      },
      "id": "FieldViolation"
    },
    "TextValues": {
      "type": "object",
      "properties": {
        "values": {
          "description": "The maximum allowable length for text values is 2048 characters.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "id": "TextValues",
      "description": "List of text values."
    },
    "SourceScoringConfig": {
      "type": "object",
      "properties": {
        "sourceImportance": {
          "description": "Importance of the source.",
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "enum": [
            "DEFAULT",
            "LOW",
            "HIGH"
          ]
        }
      },
      "id": "SourceScoringConfig",
      "description": "Set the scoring configuration. This allows modifying the ranking of results\nfor a source."
    },
    "ObjectPropertyOptions": {
      "description": "Options for object properties.",
      "type": "object",
      "properties": {
        "subobjectProperties": {
          "description": "The properties of the sub-object. These properties represent a nested\nobject. For example, if this property represents a postal address, the\nsubobjectProperties might be named *street*, *city*, and *state*.\nThe maximum number of elements is 1000.",
          "type": "array",
          "items": {
            "$ref": "PropertyDefinition"
          }
        }
      },
      "id": "ObjectPropertyOptions"
    },
    "DateOperatorOptions": {
      "type": "object",
      "properties": {
        "greaterThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ndate property using the greater-than operator. For example, if\ngreaterThanOperatorName is *closedafter* and the property's name is\n*closeDate*, then queries like *closedafter:&lt;value&gt;* will\nshow results only where the value of the property named *closeDate* is\nlater than *&lt;value&gt;*.\nThe operator name can only contain lowercase letters (a-z).\nThe maximum length is 32 characters.",
          "type": "string"
        },
        "lessThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ndate property using the less-than operator. For example, if\nlessThanOperatorName is *closedbefore* and the property's name is\n*closeDate*, then queries like *closedbefore:&lt;value&gt;* will\nshow results only where the value of the property named *closeDate* is\nearlier than *&lt;value&gt;*.\nThe operator name can only contain lowercase letters (a-z).\nThe maximum length is 32 characters.",
          "type": "string"
        },
        "operatorName": {
          "description": "Indicates the actual string required in the query in order to isolate the\ndate property. For example, suppose an issue tracking schema object\nhas a property named *closeDate* that specifies an operator with an\noperatorName of *closedon*. For searches on that data, queries like\n*closedon:&lt;value&gt;* will show results only where the value of the\n*closeDate* property matches *&lt;value&gt;*. By contrast, a\nsearch that uses the same *&lt;value&gt;* without an opera[...]",
          "type": "string"
        }
      },
      "id": "DateOperatorOptions",
      "description": "Optional. Provides a search operator for date properties.\nSearch operators let users restrict the query to specific fields relevant\nto the type of item being searched."
    },
    "RequestOptions": {
      "type": "object",
      "properties": {
        "languageCode": {
          "description": "The BCP-47 language code, such as \"en-US\" or \"sr-Latn\".\nFor more information, see\nhttp://www.unicode.org/reports/tr35/#Unicode_locale_identifier.\nFor translations.\n\nWhen specified, the documents in search results are biased towards the\nspecified language.\nSuggest API does not use this parameter. It autocompletes only based on\ncharacters in the query.",
          "type": "string"
        },
        "timeZone": {
          "description": "Current user's time zone id, such as \"America/Los_Angeles\" or\n\"Australia/Sydney\". These IDs are defined by\n[Unicode Common Locale Data Repository (CLDR)](http://cldr.unicode.org/)\nproject, and currently available in the file\n[timezone.xml](http://unicode.org/repos/cldr/trunk/common/bcp47/timezone.xml).\nThis field is used to correctly interpret date and time queries.\nIf this field is not specified, the default time zone (UTC) is used.",
          "type": "string"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Debug options of the request"
        },
        "searchApplicationId": {
          "type": "string",
          "description": "Id of the application created using SearchApplicationsService."
        }
      },
      "id": "RequestOptions",
      "description": "Shared request options for all RPC methods."
    },
    "GetSearchApplicationUserStatsResponse": {
      "type": "object",
      "properties": {
        "stats": {
          "type": "array",
          "items": {
            "$ref": "SearchApplicationUserStats"
          }
        }
      },
      "id": "GetSearchApplicationUserStatsResponse"
    },
    "ResultCounts": {
      "id": "ResultCounts",
      "description": "Result count information",
      "type": "object",
      "properties": {
        "sourceResultCounts": {
          "type": "array",
          "items": {
            "$ref": "SourceResultCount"
          },
          "description": "Result count information for each source with results."
        }
      }
    },
    "TimestampPropertyOptions": {
      "type": "object",
      "properties": {
        "operatorOptions": {
          "$ref": "TimestampOperatorOptions",
          "description": "If set, describes how the timestamp should be used as a search operator."
        }
      },
      "id": "TimestampPropertyOptions",
      "description": "Options for timestamp properties."
    },
    "SuggestRequest": {
      "description": "Request of suggest API.",
      "type": "object",
      "properties": {
        "requestOptions": {
          "$ref": "RequestOptions",
          "description": "Request options, such as the search application and user timezone."
        },
        "query": {
          "description": "Partial query for which autocomplete suggestions will be shown.\nFor example, if the query is \"sea\", then the server might return\n\"season\", \"search\", \"seagull\" and so on.",
          "type": "string"
        },
        "dataSourceRestrictions": {
          "type": "array",
          "items": {
            "$ref": "DataSourceRestriction"
          },
          "description": "The sources to use for suggestions. If not specified, all data sources\nfrom the current search application are used.\nSuggestions are based on Gmail titles. Suggestions from third party sources\nare not available."
        }
      },
      "id": "SuggestRequest"
    },
    "ScoringConfig": {
      "id": "ScoringConfig",
      "description": "Scoring configurations for a source while processing a\nSearch or\nSuggest request.",
      "type": "object",
      "properties": {
        "disableFreshness": {
          "type": "boolean",
          "description": "Whether to use freshness as a ranking signal. By default, freshness is used\nas a ranking signal. Note that this setting is not available in the Admin\nUI."
        },
        "disablePersonalization": {
          "description": "Whether to personalize the results. By default, personal signals will\nbe used to boost results.",
          "type": "boolean"
        }
      }
    },
    "ValueFilter": {
      "type": "object",
      "properties": {
        "operatorName": {
          "type": "string",
          "description": "The `operator_name` applied to the query, such as *price_greater_than*.\nThe filter can work against both types of filters defined in the schema\nfor your data source:\n\u003cbr/\u003e\u003cbr/\u003e\n1. `operator_name`, where the query filters results by the property\nthat matches the value.\n\u003cbr/\u003e\n2. `greater_than_operator_name` or `less_than_operator_name` in your\nschema. The query filters the results for the property values that are\ngreater than or less[...]"
        },
        "value": {
          "description": "The value to be compared with.",
          "$ref": "Value"
        }
      },
      "id": "ValueFilter"
    },
    "ListItemNamesForUnmappedIdentityResponse": {
      "type": "object",
      "properties": {
        "itemNames": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no\nmore results in the list.",
          "type": "string"
        }
      },
      "id": "ListItemNamesForUnmappedIdentityResponse"
    },
    "ResponseDebugInfo": {
      "id": "ResponseDebugInfo",
      "description": "Debugging information about the response.",
      "type": "object",
      "properties": {
        "formattedDebugInfo": {
          "description": "General debug info formatted for display.",
          "type": "string"
        }
      }
    },
    "NamedProperty": {
      "type": "object",
      "properties": {
        "integerValues": {
          "$ref": "IntegerValues"
        },
        "doubleValues": {
          "$ref": "DoubleValues"
        },
        "name": {
          "description": "The name of the property.  This name should correspond to the name of the\nproperty that was registered for object definition in the schema.\nThe maximum allowable length for this property is 256 characters.",
          "type": "string"
        },
        "booleanValue": {
          "type": "boolean"
        },
        "textValues": {
          "$ref": "TextValues"
        },
        "htmlValues": {
          "$ref": "HtmlValues"
        },
        "timestampValues": {
          "$ref": "TimestampValues"
        },
        "objectValues": {
          "$ref": "ObjectValues"
        },
        "dateValues": {
          "$ref": "DateValues"
        },
        "enumValues": {
          "$ref": "EnumValues"
        }
      },
      "id": "NamedProperty",
      "description": "A typed name-value pair for structured data.  The type of the value should\nbe the same as the registered type for the `name` property in the object\ndefinition of `objectType`."
    },
    "UnmappedIdentity": {
      "type": "object",
      "properties": {
        "resolutionStatusCode": {
          "description": "The resolution status for the external identity.",
          "type": "string",
          "enumDescriptions": [
            "Input-only value.  Used to list all unmapped identities regardless of\nstatus.",
            "The unmapped identity was not found in IDaaS, and needs to be provided by\nthe user.",
            "The identity source associated with the identity was either not found or\ndeleted.",
            "IDaaS does not understand the identity source, probably because the\nschema was modified in a non compatible way.",
            "The number of users associated with the external identity is too large.",
            "Internal error."
          ],
          "enum": [
            "CODE_UNSPECIFIED",
            "NOT_FOUND",
            "IDENTITY_SOURCE_NOT_FOUND",
            "IDENTITY_SOURCE_MISCONFIGURED",
            "TOO_MANY_MAPPINGS_FOUND",
            "INTERNAL_ERROR"
          ]
        },
        "externalIdentity": {
          "$ref": "Principal",
          "description": "The resource name for an external user."
        }
      },
      "id": "UnmappedIdentity"
    },
    "PushItemRequest": {
      "type": "object",
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "item": {
          "description": "Item to push onto the queue.",
          "$ref": "PushItem"
        },
        "connectorName": {
          "description": "Name of connector making this call.\n\u003cbr /\u003eFormat: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        }
      },
      "id": "PushItemRequest"
    },
    "SearchItemsByViewUrlRequest": {
      "type": "object",
      "properties": {
        "viewUrl": {
          "description": "Specify the full view URL to find the corresponding item.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "pageToken": {
          "description": "The next_page_token value returned from a previous request, if any.",
          "type": "string"
        }
      },
      "id": "SearchItemsByViewUrlRequest"
    },
    "PollItemsResponse": {
      "type": "object",
      "properties": {
        "items": {
          "description": "Set of items from the queue available for connector to process.\n\u003cbr /\u003eThese items have the following subset of fields populated: \u003cbr /\u003e\n\u003cbr /\u003eversion\n\u003cbr /\u003emetadata.hash\n\u003cbr /\u003estructured_data.hash\n\u003cbr /\u003econtent.hash\n\u003cbr /\u003epayload\n\u003cbr /\u003estatus\n\u003cbr /\u003equeue",
          "type": "array",
          "items": {
            "$ref": "Item"
          }
        }
      },
      "id": "PollItemsResponse"
    },
    "ListItemsResponse": {
      "id": "ListItemsResponse",
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "Item"
          }
        },
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no\nmore results in the list.",
          "type": "string"
        }
      }
    },
    "GetCustomerSessionStatsResponse": {
      "id": "GetCustomerSessionStatsResponse",
      "type": "object",
      "properties": {
        "stats": {
          "type": "array",
          "items": {
            "$ref": "CustomerSessionStats"
          }
        }
      }
    },
    "UnreserveItemsRequest": {
      "type": "object",
      "properties": {
        "connectorName": {
          "description": "Name of connector making this call.\n\u003cbr /\u003eFormat: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "queue": {
          "type": "string",
          "description": "Name of a queue to unreserve items from."
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      },
      "id": "UnreserveItemsRequest"
    },
    "HtmlPropertyOptions": {
      "type": "object",
      "properties": {
        "retrievalImportance": {
          "$ref": "RetrievalImportance",
          "description": "Indicates the search quality importance of the tokens within the\nfield when used for retrieval. Can only be set to DEFAULT or NONE."
        },
        "operatorOptions": {
          "$ref": "HtmlOperatorOptions",
          "description": "If set, describes how the property should be used as a search operator."
        }
      },
      "id": "HtmlPropertyOptions",
      "description": "Options for html properties."
    },
    "QueryOperator": {
      "type": "object",
      "properties": {
        "isRepeatable": {
          "description": "Indicates if multiple values can be set for this property.",
          "type": "boolean"
        },
        "greaterThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name that can be used to  isolate the property using\nthe greater-than operator."
        },
        "enumValues": {
          "description": "Potential list of values for the opeatror field. This field is only filled\nwhen we can safely enumerate all the possible values of this operator.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "isSuggestable": {
          "type": "boolean",
          "description": "Can get suggestions for this field."
        },
        "lessThanOperatorName": {
          "description": "Indicates the operator name that can be used to  isolate the property using\nthe less-than operator.",
          "type": "string"
        },
        "type": {
          "description": "Type of the operator.",
          "type": "string",
          "enumDescriptions": [
            "Invalid value.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "enum": [
            "UNKNOWN",
            "INTEGER",
            "DOUBLE",
            "TIMESTAMP",
            "BOOLEAN",
            "ENUM",
            "DATE",
            "TEXT",
            "HTML"
          ]
        },
        "displayName": {
          "description": "Display name of the operator",
          "type": "string"
        },
        "operatorName": {
          "description": "The name of the operator.",
          "type": "string"
        },
        "isSortable": {
          "description": "Can this operator be used to sort results.",
          "type": "boolean"
        },
        "isFacetable": {
          "description": "Can this operator be used to get facets.",
          "type": "boolean"
        },
        "isReturnable": {
          "description": "Will the property associated with this facet be returned as part of search\nresults.",
          "type": "boolean"
        }
      },
      "id": "QueryOperator",
      "description": "The definition of a operator that can be used in a Search/Suggest request."
    },
    "TimestampValues": {
      "type": "object",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "google-datetime"
          }
        }
      },
      "id": "TimestampValues",
      "description": "List of timestamp values."
    },
    "SearchQualityMetadata": {
      "description": "Additional search quality metadata of the item.",
      "type": "object",
      "properties": {
        "quality": {
          "description": "An indication of the quality of the item, used to influence search quality.\nValue should be between 0.0 (lowest quality) and 1.0 (highest quality). The\ndefault value is 0.0.",
          "format": "double",
          "type": "number"
        }
      },
      "id": "SearchQualityMetadata"
    },
    "DatePropertyOptions": {
      "description": "Options for date properties.",
      "type": "object",
      "properties": {
        "operatorOptions": {
          "$ref": "DateOperatorOptions",
          "description": "If set, describes how the date should be used as a search operator."
        }
      },
      "id": "DatePropertyOptions"
    },
    "RestrictItem": {
      "description": "Information relevant only to a restrict entry.\nNextId: 12",
      "type": "object",
      "properties": {
        "gmailIntelligentRestrict": {
          "$ref": "GmailIntelligentRestrict"
        },
        "gmailAttachmentRestrict": {
          "$ref": "GmailAttachmentRestrict"
        },
        "gmailActionRestrict": {
          "$ref": "GmailActionRestrict"
        },
        "driveMimeTypeRestrict": {
          "$ref": "DriveMimeTypeRestrict",
          "description": "LINT.IfChange\nDrive Types."
        },
        "searchOperator": {
          "description": "The search restrict (e.g. \"after:2017-09-11 before:2017-09-12\").",
          "type": "string"
        },
        "driveFollowUpRestrict": {
          "$ref": "DriveFollowUpRestrict",
          "description": "LINT.ThenChange(//depot/google3/java/com/google/apps/search/quality/itemsuggest/utils/SubtypeRerankingUtils.java)"
        },
        "driveTimeSpanRestrict": {
          "$ref": "DriveTimeSpanRestrict"
        },
        "driveLocationRestrict": {
          "$ref": "DriveLocationRestrict"
        },
        "gmailTimeRestrict": {
          "$ref": "GmailTimeRestrict"
        },
        "gmailFolderRestrict": {
          "$ref": "GmailFolderRestrict",
          "description": "Gmail Types."
        }
      },
      "id": "RestrictItem"
    },
    "DriveMimeTypeRestrict": {
      "description": "Drive mime-type search restricts (e.g. \"type:pdf\").",
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "enum": [
            "UNSPECIFIED",
            "PDF",
            "DOCUMENT",
            "PRESENTATION",
            "SPREADSHEET",
            "FORM",
            "DRAWING",
            "SCRIPT",
            "MAP",
            "IMAGE",
            "AUDIO",
            "VIDEO",
            "FOLDER",
            "ARCHIVE",
            "SITE"
          ]
        }
      },
      "id": "DriveMimeTypeRestrict"
    },
    "QueryCountByStatus": {
      "type": "object",
      "properties": {
        "statusCode": {
          "type": "integer",
          "description": "This represents the http status code.",
          "format": "int32"
        },
        "count": {
          "format": "int64",
          "type": "string"
        }
      },
      "id": "QueryCountByStatus"
    },
    "Metaline": {
      "type": "object",
      "properties": {
        "properties": {
          "description": "The list of displayed properties for the metaline. The maxiumum number of\nproperties is 5.",
          "type": "array",
          "items": {
            "$ref": "DisplayedProperty"
          }
        }
      },
      "id": "Metaline",
      "description": "A metaline is a list of properties that are displayed along with the search\nresult to provide context."
    },
    "BooleanOperatorOptions": {
      "type": "object",
      "properties": {
        "operatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the\nboolean property. For example, if operatorName is *closed* and the\nproperty's name is *isClosed*, then queries like\n*closed:&lt;value&gt;* will show results only where the value of the\nproperty named *isClosed* matches *&lt;value&gt;*. By contrast, a\nsearch that uses the same *&lt;value&gt;* without an operator will return\nall items where *&lt;value&gt;* matches the value of any\nString prop[...]"
        }
      },
      "id": "BooleanOperatorOptions",
      "description": "Used to provide a search operator for boolean properties. This is\noptional. Search operators let users restrict the query to specific fields\nrelevant to the type of item being searched."
    },
    "GmailAttachmentRestrict": {
      "description": "Gmail Attachment restricts (i.e. has:attachment, has:drive, filename:pdf).",
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enumDescriptions": [
            "",
            "has:attachment",
            "has photos (changes to filename:(jpg OR jpeg OR png)  when typed)",
            "has:drive",
            "has:document",
            "has:spreadsheet",
            "has:presentation",
            "has:youtube",
            "filename:pdf"
          ],
          "enum": [
            "UNSPECIFIED",
            "HAS_ATTACHMENT",
            "HAS_PHOTO",
            "HAS_DRIVE",
            "HAS_DOCUMENT",
            "HAS_SPREADSHEET",
            "HAS_PRESENTATION",
            "HAS_YOUTUBE",
            "HAS_PDF"
          ]
        }
      },
      "id": "GmailAttachmentRestrict"
    },
    "SourceConfig": {
      "id": "SourceConfig",
      "description": "Configurations for a source while processing a\nSearch or\nSuggest request.",
      "type": "object",
      "properties": {
        "source": {
          "$ref": "Source",
          "description": "The source for which this configuration is to be used."
        },
        "scoringConfig": {
          "$ref": "SourceScoringConfig",
          "description": "The scoring configuration for the source."
        },
        "crowdingConfig": {
          "$ref": "SourceCrowdingConfig",
          "description": "The crowding configuration for the source."
        }
      }
    },
    "DataSource": {
      "id": "DataSource",
      "description": "Datasource is a logical namespace for items to be indexed.\nAll items must belong to a datasource.  This is the prerequisite before\nitems can be indexed into Cloud Search.",
      "type": "object",
      "properties": {
        "shortName": {
          "description": "A short name or alias for the source.  This value will be used to match the\n'source' operator. For example, if the short name is *&lt;value&gt;* then\nqueries like *source:&lt;value&gt;* will only return results for this\nsource. The value must be unique across all datasources. The value must\nonly contain alphanumeric characters (a-zA-Z0-9). The value cannot start\nwith 'google' and cannot be one of the following: mail, gmail, docs, drive,\ngroups, sites, calendar, ha[...]",
          "type": "string"
        },
        "name": {
          "type": "string",
          "description": "Name of the datasource resource.\nFormat: datasources/{source_id}.\n\u003cbr /\u003eThe name is ignored when creating a datasource."
        },
        "operationIds": {
          "description": "IDs of the Long Running Operations (LROs) currently running for this\nschema.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "disableModifications": {
          "type": "boolean",
          "description": "If true, Indexing API rejects any modification calls to this datasource\nsuch as create, update, and delete.\nDisabling this does not imply halting process of previously\naccepted data."
        },
        "indexingServiceAccounts": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "List of service accounts that have indexing access."
        },
        "disableServing": {
          "description": "Disable serving any search or assist results.",
          "type": "boolean"
        },
        "displayName": {
          "description": "Required. Display name of the datasource\nThe maximum length is 300 characters.",
          "type": "string"
        },
        "itemsVisibility": {
          "type": "array",
          "items": {
            "$ref": "GSuitePrincipal"
          },
          "description": "This field restricts visibility to items at the datasource level. Items\nwithin the datasource are restricted to the union of users and groups\nincluded in this field. Note that, this does not ensure access to a\nspecific item, as users need to have ACL permissions on the contained\nitems. This ensures a high level access on the entire datasource, and\nthat the individual items are not shared outside this visibility."
        }
      }
    },
    "UpdateDataSourceRequest": {
      "type": "object",
      "properties": {
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        },
        "source": {
          "$ref": "DataSource"
        }
      },
      "id": "UpdateDataSourceRequest"
    },
    "ItemCountByStatus": {
      "id": "ItemCountByStatus",
      "type": "object",
      "properties": {
        "count": {
          "type": "string",
          "description": "Number of items matching the status code.",
          "format": "int64"
        },
        "statusCode": {
          "enum": [
            "CODE_UNSPECIFIED",
            "ERROR",
            "MODIFIED",
            "NEW_ITEM",
            "ACCEPTED"
          ],
          "description": "Status of the items.",
          "type": "string",
          "enumDescriptions": [
            "Input-only value.  Used with\nItems.list\nto list all items in the queue, regardless of status.",
            "Error encountered by Cloud Search while processing this item.\nDetails of the error are in\nrepositoryError.",
            "Item has been modified in the repository, and is out of date with\nthe version previously accepted into Cloud Search.",
            "Item is known to exist in the repository, but is not yet accepted by\nCloud Search.\nAn item can be in this state when\nItems.push\nhas been called for\nan item of this name that did not exist previously.",
            "API has accepted the up-to-date data of this item."
          ]
        }
      }
    },
    "FacetResult": {
      "description": "Source specific facet response",
      "type": "object",
      "properties": {
        "operatorName": {
          "description": "Name of the operator chosen for faceting. @see\ncloudsearch.SchemaPropertyOptions",
          "type": "string"
        },
        "objectType": {
          "description": "Object type for which facet results are returned. Can be empty.",
          "type": "string"
        },
        "sourceName": {
          "description": "Source name for which facet results are returned. Will not be empty.",
          "type": "string"
        },
        "buckets": {
          "description": "FacetBuckets for values in response containing at least a single result.",
          "type": "array",
          "items": {
            "$ref": "FacetBucket"
          }
        }
      },
      "id": "FacetResult"
    },
    "IntegerPropertyOptions": {
      "id": "IntegerPropertyOptions",
      "description": "Options for integer properties.",
      "type": "object",
      "properties": {
        "orderedRanking": {
          "enum": [
            "NO_ORDER",
            "ASCENDING",
            "DESCENDING"
          ],
          "description": "Used to specify the ordered ranking for the integer. Can only be used if\nisRepeatable\nis false.",
          "type": "string",
          "enumDescriptions": [
            "There is no ranking order for the property. Results will not be adjusted\nby this property's value.",
            "This property is ranked in ascending order. Lower values indicate lower\nranking.",
            "This property is ranked in descending order. Lower values indicate\nhigher ranking."
          ]
        },
        "maximumValue": {
          "description": "The maximum value of the property. The minimum and maximum values for the\nproperty are used to rank results according to the\nordered ranking.\nIndexing requests with values greater than the maximum are accepted and\nranked with the same weight as items indexed with the maximum value.",
          "format": "int64",
          "type": "string"
        },
        "minimumValue": {
          "type": "string",
          "description": "The minimum value of the property. The minimum and maximum values for the\nproperty are used to rank results according to the\nordered ranking.\nIndexing requests with values less than the minimum are accepted and\nranked with the same weight as items indexed with the minimum value.",
          "format": "int64"
        },
        "operatorOptions": {
          "$ref": "IntegerOperatorOptions",
          "description": "If set, describes how the integer should be used as a search operator."
        }
      }
    },
    "ItemMetadata": {
      "description": "Available metadata fields for the item.",
      "type": "object",
      "properties": {
        "createTime": {
          "description": "The time when the item was created in the source repository.",
          "format": "google-datetime",
          "type": "string"
        },
        "contentLanguage": {
          "description": "The BCP-47 language code for the item, such as \"en-US\" or \"sr-Latn\". For\nmore information, see\nhttp://www.unicode.org/reports/tr35/#Unicode_locale_identifier.\nThe maximum length is 32 characters.",
          "type": "string"
        },
        "sourceRepositoryUrl": {
          "description": "Link to the source repository serving the data.  &#83;earch results apply\nthis link to the title.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "updateTime": {
          "description": "The time when the item was last modified in the source repository.",
          "format": "google-datetime",
          "type": "string"
        },
        "containerName": {
          "description": "The name of the container for this item.\nDeletion of the container item leads to automatic deletion of this\nitem.  Note: ACLs are not inherited from a container item.\nTo provide ACL inheritance for an item, use the\ninheritAclFrom\nfield. The maximum length is 1536 characters.",
          "type": "string"
        },
        "objectType": {
          "description": "The type of the item.  This should correspond to the name of an object\ndefinition in the schema registered for the data source.  For example, if\nthe schema for the data source contains an object definition with name\n'document', then item indexing requests for objects of that type should set\nobjectType to 'document'.\nThe maximum length is 256 characters.",
          "type": "string"
        },
        "searchQualityMetadata": {
          "$ref": "SearchQualityMetadata",
          "description": "Additional search quality metadata of the item"
        },
        "hash": {
          "description": "Hashing value provided by the API caller.\nThis can be used with the\nitems.push\nmethod to calculate modified state.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "interactions": {
          "description": "A list of interactions for the item.  Interactions are used to improve\nSearch quality, but are not exposed to end users.\nThe maximum number of elements is 1000.",
          "type": "array",
          "items": {
            "$ref": "Interaction"
          }
        },
        "keywords": {
          "description": "Additional keywords or phrases that should match the item.\nUsed internally for user generated content.\nThe maximum number of elements is 100.\nThe maximum length is 8192 characters.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "mimeType": {
          "description": "The original mime-type of\nItemContent.content\nin the source repository.\nThe maximum length is 256 characters.",
          "type": "string"
        },
        "title": {
          "type": "string",
          "description": "The title of the item.  If given, this will be the displayed title of the\nSearch result.\nThe maximum length is 2048 characters."
        }
      },
      "id": "ItemMetadata"
    },
    "CustomerQueryStats": {
      "type": "object",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "Date for which query stats were calculated. Stats calculated on the next\nday close to midnight are returned."
        },
        "queryCountByStatus": {
          "type": "array",
          "items": {
            "$ref": "QueryCountByStatus"
          }
        }
      },
      "id": "CustomerQueryStats"
    },
    "IndexItemOptions": {
      "type": "object",
      "properties": {
        "allowUnknownGsuitePrincipals": {
          "description": "Specifies if the index request should allow gsuite principals that do not\nexist or are deleted in the index request.",
          "type": "boolean"
        }
      },
      "id": "IndexItemOptions"
    },
    "StructuredDataObject": {
      "description": "A structured data object consisting of named properties.",
      "type": "object",
      "properties": {
        "properties": {
          "type": "array",
          "items": {
            "$ref": "NamedProperty"
          },
          "description": "The properties for the object.\nThe maximum number of elements is 1000."
        }
      },
      "id": "StructuredDataObject"
    },
    "EnumPropertyOptions": {
      "description": "Options for enum properties, which allow you to define a restricted set of\nstrings to match user queries, set rankings for those string values, and\ndefine an operator name to be paired with those strings so that users can\nnarrow results to only items with a specific value. For example, for items in\na request tracking system with priority information, you could define *p0* as\nan allowable enum value and tie this enum to the operator name *priority* so\nthat search users[...]",
      "type": "object",
      "properties": {
        "possibleValues": {
          "description": "The list of possible values for the enumeration property. All\nEnumValuePairs must provide a string value. If you specify an integer value\nfor one EnumValuePair, then all possible EnumValuePairs must provide an\ninteger value. Both the string value and integer value must be unique over\nall possible values. Once set, possible values cannot be removed or\nmodified. If you supply an ordered ranking and think you might insert\nadditional enum values in the future, leave g[...]",
          "type": "array",
          "items": {
            "$ref": "EnumValuePair"
          }
        },
        "orderedRanking": {
          "type": "string",
          "enumDescriptions": [
            "There is no ranking order for the property. Results will not be adjusted\nby this property's value.",
            "This property is ranked in ascending order. Lower values indicate lower\nranking.",
            "This property is ranked in descending order. Lower values indicate\nhigher ranking."
          ],
          "enum": [
            "NO_ORDER",
            "ASCENDING",
            "DESCENDING"
          ],
          "description": "Used to specify the ordered ranking for the enumeration that determines how\nthe integer values provided in the possible EnumValuePairs are used to rank\nresults. If specified, integer values must be provided for all possible\nEnumValuePair values given for this property. Can only be used if\nisRepeatable\nis false."
        },
        "operatorOptions": {
          "$ref": "EnumOperatorOptions",
          "description": "If set, describes how the enum should be used as a search operator."
        }
      },
      "id": "EnumPropertyOptions"
    },
    "SourceResultCount": {
      "description": "Per source result count information.",
      "type": "object",
      "properties": {
        "source": {
          "$ref": "Source",
          "description": "The source the result count information is associated with."
        },
        "resultCountExact": {
          "description": "The exact result count for this source.",
          "format": "int64",
          "type": "string"
        },
        "resultCountEstimate": {
          "description": "The estimated result count for this source.",
          "format": "int64",
          "type": "string"
        },
        "hasMoreResults": {
          "description": "Whether there are more search results for this source.",
          "type": "boolean"
        }
      },
      "id": "SourceResultCount"
    },
    "GetCustomerIndexStatsResponse": {
      "type": "object",
      "properties": {
        "stats": {
          "description": "Summary of indexed item counts, one for each day in the requested range.",
          "type": "array",
          "items": {
            "$ref": "CustomerIndexStats"
          }
        }
      },
      "id": "GetCustomerIndexStatsResponse"
    },
    "QuerySource": {
      "id": "QuerySource",
      "description": "List of sources that the user can search using the query API.",
      "type": "object",
      "properties": {
        "shortName": {
          "description": "A short name or alias for the source.  This value can be used with the\n'source' operator.",
          "type": "string"
        },
        "displayName": {
          "description": "Display name of the data source.",
          "type": "string"
        },
        "source": {
          "$ref": "Source",
          "description": "Name of the source"
        },
        "operators": {
          "description": "List of all operators applicable for this source.",
          "type": "array",
          "items": {
            "$ref": "QueryOperator"
          }
        }
      }
    },
    "QueryInterpretation": {
      "type": "object",
      "properties": {
        "interpretedQuery": {
          "type": "string",
          "description": "The interpretation of the query used in search. For example, queries with\nnatural language intent like \"email from john\" will be interpreted as\n\"from:john source:mail\". This field will not be filled when the reason is\nNO_RESULTS_FOUND_FOR_USER_QUERY."
        },
        "interpretationType": {
          "enum": [
            "NONE",
            "BLEND",
            "REPLACE"
          ],
          "type": "string",
          "enumDescriptions": [
            "No natural language interpretation or the natural language interpretation\nis not used to fetch the search results.",
            "The natural language results is mixed with results from original query.",
            "The results from original query are replaced. The reason for replacing\nthe results from original query is populated in the 'Reason' field below."
          ]
        },
        "reason": {
          "description": "The reason for interpretation of the query. This field will not be\nUNSPECIFIED if the interpretation type is not NONE.",
          "type": "string",
          "enumDescriptions": [
            "",
            "Natural language interpretation of the query is used to fetch the search\nresults.",
            "The following values are returned only when interpretation type is\nREPLACE.\nThe search results are replaced by ones which are retrieved through a\nmuch broader version of the query since no results were found for the\nuser query. Interpreted query will be empty for the following case."
          ],
          "enum": [
            "UNSPECIFIED",
            "QUERY_HAS_NATURAL_LANGUAGE_INTENT",
            "NO_RESULTS_FOUND_FOR_USER_QUERY"
          ]
        }
      },
      "id": "QueryInterpretation"
    },
    "ErrorMessage": {
      "description": "Error message per source response.",
      "type": "object",
      "properties": {
        "source": {
          "$ref": "Source"
        },
        "errorMessage": {
          "type": "string"
        }
      },
      "id": "ErrorMessage"
    },
    "TextOperatorOptions": {
      "type": "object",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ntext property. For example, if operatorName is *subject* and the\nproperty's name is *subjectLine*, then queries like\n*subject:&lt;value&gt;* will show results only where the value of the\nproperty named *subjectLine* matches *&lt;value&gt;*. By contrast, a\nsearch that uses the same *&lt;value&gt;* without an operator will return\nall items where *&lt;value&gt;* matches the value of any\ntext p[...]",
          "type": "string"
        },
        "exactMatchWithOperator": {
          "description": "If true, the text value will be tokenized as one atomic value in\noperator searches and facet matches. For example, if the operator name is\n\"genre\" and the value is \"science-fiction\" the query restrictions\n\"genre:science\" and \"genre:fiction\" will not match the item;\n\"genre:science-fiction\" will. Value matching is case-sensitive\nand does not remove special characters.\nIf false, the text will be tokenized. For example, if the value is\n\"science-fiction\" t[...]",
          "type": "boolean"
        }
      },
      "id": "TextOperatorOptions",
      "description": "Used to provide a search operator for text properties. This is optional.\nSearch operators let users restrict the query to specific fields relevant\nto the type of item being searched."
    },
    "ResultDisplayField": {
      "type": "object",
      "properties": {
        "label": {
          "description": "The display label for the property.",
          "type": "string"
        },
        "property": {
          "$ref": "NamedProperty",
          "description": "The name value pair for the property."
        },
        "operatorName": {
          "description": "The operator name of the property.",
          "type": "string"
        }
      },
      "id": "ResultDisplayField",
      "description": "Display Fields for Search Results"
    },
    "ListQuerySourcesResponse": {
      "description": "List sources response.",
      "type": "object",
      "properties": {
        "nextPageToken": {
          "type": "string"
        },
        "sources": {
          "type": "array",
          "items": {
            "$ref": "QuerySource"
          }
        }
      },
      "id": "ListQuerySourcesResponse"
    },
    "Media": {
      "description": "Media resource.",
      "type": "object",
      "properties": {
        "resourceName": {
          "description": "Name of the media resource.",
          "type": "string"
        }
      },
      "id": "Media"
    },
    "FacetBucket": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer",
          "description": "Number of results that match the bucket value. Counts are only returned\nfor searches when count accuracy is ensured. Can be empty.",
          "format": "int32"
        },
        "percentage": {
          "description": "Percent of results that match the bucket value. This value is between\n(0-100]. Percentages are returned for all searches, but are an estimate.\nBecause percentages are always returned, you should render percentages\ninstead of counts.",
          "format": "int32",
          "type": "integer"
        },
        "value": {
          "$ref": "Value"
        }
      },
      "id": "FacetBucket",
      "description": "A bucket in a facet is the basic unit of operation. A bucket can comprise\neither a single value OR a contiguous range of values, depending on the\ntype of the field bucketed.\nFacetBucket is currently used only for returning the response object."
    },
    "Filter": {
      "type": "object",
      "properties": {
        "compositeFilter": {
          "$ref": "CompositeFilter"
        },
        "valueFilter": {
          "$ref": "ValueFilter"
        }
      },
      "id": "Filter",
      "description": "A generic way of expressing filters in a query, which supports two\napproaches: \u003cbr/\u003e\u003cbr/\u003e\n**1. Setting a ValueFilter.** The name must match an operator_name defined in\nthe schema for your data source.\n\u003cbr/\u003e\n**2. Setting a CompositeFilter.** The filters are evaluated\nusing the logical operator. The top-level operators can only be either an AND\nor a NOT. AND can appear only at the top-most level. OR can appear only under\na top-level AND."
    },
    "GetSearchApplicationSessionStatsResponse": {
      "type": "object",
      "properties": {
        "stats": {
          "type": "array",
          "items": {
            "$ref": "SearchApplicationSessionStats"
          }
        }
      },
      "id": "GetSearchApplicationSessionStatsResponse"
    },
    "ResetSearchApplicationRequest": {
      "type": "object",
      "properties": {
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        }
      },
      "id": "ResetSearchApplicationRequest"
    },
    "Name": {
      "type": "object",
      "properties": {
        "displayName": {
          "description": "The read-only display name formatted according to the locale specified by\nthe viewer's account or the \u003ccode\u003eAccept-Language\u003c/code\u003e HTTP header.",
          "type": "string"
        }
      },
      "id": "Name",
      "description": "A person's name."
    },
    "IntegerOperatorOptions": {
      "description": "Used to provide a search operator for integer properties. This is\noptional. Search operators let users restrict the query to specific fields\nrelevant to the type of item being searched.",
      "type": "object",
      "properties": {
        "lessThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the\ninteger property using the less-than operator. For example, if\nlessThanOperatorName is *prioritybelow* and the property's name is\n*priorityVal*, then queries like *prioritybelow:&lt;value&gt;* will\nshow results only where the value of the property named *priorityVal* is\nless than *&lt;value&gt;*.\nThe operator name can only contain lowercase letters (a-z).\nThe maximum length is 32 characters[...]"
        },
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ninteger property. For example, if operatorName is *priority* and the\nproperty's name is *priorityVal*, then queries like\n*priority:&lt;value&gt;* will show results only where the value of the\nproperty named *priorityVal* matches *&lt;value&gt;*. By contrast, a\nsearch that uses the same *&lt;value&gt;* without an operator will return\nall items where *&lt;value&gt;* matches the value of any St[...]",
          "type": "string"
        },
        "greaterThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the\ninteger property using the greater-than operator. For example, if\ngreaterThanOperatorName is *priorityabove* and the property's name is\n*priorityVal*, then queries like *priorityabove:&lt;value&gt;* will\nshow results only where the value of the property named *priorityVal* is\ngreater than *&lt;value&gt;*.\nThe operator name can only contain lowercase letters (a-z).\nThe maximum length is 32 c[...]"
        }
      },
      "id": "IntegerOperatorOptions"
    },
    "FilterOptions": {
      "id": "FilterOptions",
      "description": "Filter options to be applied on query.",
      "type": "object",
      "properties": {
        "objectType": {
          "description": "If object_type is set, only objects of that type are returned. This should\ncorrespond to the name of the object that was registered within the\ndefinition of schema. The maximum length is 256 characters.",
          "type": "string"
        },
        "filter": {
          "$ref": "Filter",
          "description": "Generic filter to restrict the search, such as `lang:en`, `site:xyz`."
        }
      }
    },
    "CustomerUserStats": {
      "type": "object",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "Date for which session stats were calculated. Stats calculated on the next\nday close to midnight are returned."
        },
        "thirtyDaysActiveUsersCount": {
          "type": "string",
          "description": "The count of unique active users in the past thirty days",
          "format": "int64"
        },
        "sevenDaysActiveUsersCount": {
          "description": "The count of unique active users in the past seven days",
          "format": "int64",
          "type": "string"
        },
        "oneDayActiveUsersCount": {
          "description": "The count of unique active users in the past one day",
          "format": "int64",
          "type": "string"
        }
      },
      "id": "CustomerUserStats"
    },
    "ProcessingError": {
      "type": "object",
      "properties": {
        "code": {
          "enumDescriptions": [
            "Input only value.  Use this value in Items.",
            "Item's ACL, metadata, or content is malformed or in invalid state.\nFieldViolations contains more details on where the problem is.",
            "Countent format is unsupported.",
            "Items with incomplete ACL information due to inheriting other\nitems with broken ACL or having groups with unmapped descendants.",
            "ACL inheritance graph formed a cycle."
          ],
          "enum": [
            "PROCESSING_ERROR_CODE_UNSPECIFIED",
            "MALFORMED_REQUEST",
            "UNSUPPORTED_CONTENT_FORMAT",
            "INDIRECT_BROKEN_ACL",
            "ACL_CYCLE"
          ],
          "description": "Error code indicating the nature of the error.",
          "type": "string"
        },
        "errorMessage": {
          "description": "Description of the error.",
          "type": "string"
        },
        "fieldViolations": {
          "description": "In case the item fields are invalid, this field contains the details\nabout the validation errors.",
          "type": "array",
          "items": {
            "$ref": "FieldViolation"
          }
        }
      },
      "id": "ProcessingError"
    },
    "EnumValues": {
      "id": "EnumValues",
      "description": "List of enum values.",
      "type": "object",
      "properties": {
        "values": {
          "description": "The maximum allowable length for string values is 32 characters.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "ResultDisplayLine": {
      "description": "The collection of fields that make up a displayed line",
      "type": "object",
      "properties": {
        "fields": {
          "type": "array",
          "items": {
            "$ref": "ResultDisplayField"
          }
        }
      },
      "id": "ResultDisplayLine"
    },
    "SearchApplicationUserStats": {
      "type": "object",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "Date for which session stats were calculated. Stats calculated on the next\nday close to midnight are returned."
        },
        "thirtyDaysActiveUsersCount": {
          "type": "string",
          "description": "The count of unique active users in the past thirty days",
          "format": "int64"
        },
        "sevenDaysActiveUsersCount": {
          "type": "string",
          "description": "The count of unique active users in the past seven days",
          "format": "int64"
        },
        "oneDayActiveUsersCount": {
          "description": "The count of unique active users in the past one day",
          "format": "int64",
          "type": "string"
        }
      },
      "id": "SearchApplicationUserStats"
    },
    "ListUnmappedIdentitiesResponse": {
      "type": "object",
      "properties": {
        "nextPageToken": {
          "type": "string",
          "description": "Token to retrieve the next page of results, or empty if there are no\nmore results in the list."
        },
        "unmappedIdentities": {
          "type": "array",
          "items": {
            "$ref": "UnmappedIdentity"
          }
        }
      },
      "id": "ListUnmappedIdentitiesResponse"
    },
    "DataSourceIndexStats": {
      "type": "object",
      "properties": {
        "date": {
          "description": "Date for which index stats were calculated. If the date of request is not\nthe current date then stats calculated on the next day are returned. Stats\nare calculated close to mid night in this case. If date of request is\ncurrent date, then real time stats are returned.",
          "$ref": "Date"
        },
        "itemCountByStatus": {
          "type": "array",
          "items": {
            "$ref": "ItemCountByStatus"
          },
          "description": "Number of items aggregrated by status code."
        }
      },
      "id": "DataSourceIndexStats",
      "description": "Aggregation of items by status code as of the specified date."
    },
    "ItemStructuredData": {
      "type": "object",
      "properties": {
        "hash": {
          "description": "Hashing value provided by the API caller.\nThis can be used with the\nitems.push\nmethod to calculate modified state.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "object": {
          "description": "The structured data object that should conform to a registered object\ndefinition in the schema for the data source.",
          "$ref": "StructuredDataObject"
        }
      },
      "id": "ItemStructuredData",
      "description": "Available structured data fields for the item."
    },
    "DebugOptions": {
      "description": "Shared request debug options for all cloudsearch RPC methods.",
      "type": "object",
      "properties": {
        "enableDebugging": {
          "type": "boolean",
          "description": "If you are asked by Google to help with debugging, set this field.\nOtherwise, ignore this field."
        }
      },
      "id": "DebugOptions"
    },
    "Item": {
      "description": "Represents a single object that is an item in the search index, such as a\nfile, folder, or a database record.",
      "type": "object",
      "properties": {
        "itemType": {
          "type": "string",
          "enumDescriptions": [
            "",
            "An item that is indexed for the only purpose of serving information.\nThese items cannot be referred in\ncontainerName\nor inheritAclFrom\nfields.",
            "An item that gets indexed and whose purpose is to supply other items\nwith ACLs and/or contain other items.",
            "An item that does not get indexed, but otherwise has the same purpose\nas CONTAINER_ITEM."
          ],
          "enum": [
            "UNSPECIFIED",
            "CONTENT_ITEM",
            "CONTAINER_ITEM",
            "VIRTUAL_CONTAINER_ITEM"
          ],
          "description": "Type for this item."
        },
        "structuredData": {
          "$ref": "ItemStructuredData",
          "description": "The structured data for the item that should conform to a registered\nobject definition in the schema for the data source."
        },
        "status": {
          "$ref": "ItemStatus",
          "description": "Status of the item.\nOutput only field."
        },
        "name": {
          "description": "Name of the Item. Format:\ndatasources/{source_id}/items/{item_id}\n\u003cbr /\u003eThis is a required field.\nThe maximum length is 1536 characters.",
          "type": "string"
        },
        "payload": {
          "type": "string",
          "description": "Additional state connector can store for this item.\nThe maximum length is 10000 bytes.",
          "format": "byte"
        },
        "acl": {
          "$ref": "ItemAcl",
          "description": "Access control list for this item."
        },
        "content": {
          "$ref": "ItemContent",
          "description": "Item content to be indexed and made text searchable."
        },
        "metadata": {
          "$ref": "ItemMetadata",
          "description": "Metadata information."
        },
        "queue": {
          "description": "Queue this item belongs to.\nThe maximum length is 100 characters.",
          "type": "string"
        },
        "version": {
          "type": "string",
          "description": "Required. The indexing system stores the version from the datasource as a\nbyte string and compares the Item version in the index\nto the version of the queued Item using lexical ordering.\n\u003cbr /\u003e\u003cbr /\u003e\nCloud Search Indexing won't index or delete any queued item with\na version value that is less than or equal to the version of the\ncurrently indexed item.\nThe maximum length for this field is 1024 bytes.",
          "format": "byte"
        }
      },
      "id": "Item"
    },
    "Interaction": {
      "type": "object",
      "properties": {
        "principal": {
          "$ref": "Principal",
          "description": "The user that acted on the item."
        },
        "type": {
          "enum": [
            "UNSPECIFIED",
            "VIEW",
            "EDIT"
          ],
          "type": "string",
          "enumDescriptions": [
            "Invalid value.",
            "This interaction indicates the user viewed the item.",
            "This interaction indicates the user edited the item."
          ]
        },
        "interactionTime": {
          "type": "string",
          "description": "The time when the user acted on the item.  If multiple actions of the same\ntype exist for a single user, only the most recent action is recorded.",
          "format": "google-datetime"
        }
      },
      "id": "Interaction",
      "description": "Represents an interaction between a user and an item."
    },
    "Value": {
      "type": "object",
      "properties": {
        "stringValue": {
          "type": "string"
        },
        "dateValue": {
          "$ref": "Date"
        },
        "doubleValue": {
          "format": "double",
          "type": "number"
        },
        "timestampValue": {
          "format": "google-datetime",
          "type": "string"
        },
        "booleanValue": {
          "type": "boolean"
        },
        "integerValue": {
          "type": "string",
          "format": "int64"
        }
      },
      "id": "Value",
      "description": "Definition of a single value with generic type."
    },
    "StartUploadItemRequest": {
      "type": "object",
      "properties": {
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        },
        "connectorName": {
          "type": "string",
          "description": "Name of connector making this call.\n\u003cbr /\u003eFormat: datasources/{source_id}/connectors/{ID}"
        }
      },
      "id": "StartUploadItemRequest",
      "description": "Start upload file request."
    },
    "Photo": {
      "id": "Photo",
      "description": "A person's photo.",
      "type": "object",
      "properties": {
        "url": {
          "description": "The URL of the photo.",
          "type": "string"
        }
      }
    },
    "ItemAcl": {
      "id": "ItemAcl",
      "description": "Access control list information for the item. For more information see\nhttps://developers.google.com/cloud-search/docs/guides/index-your-data#acls",
      "type": "object",
      "properties": {
        "aclInheritanceType": {
          "enumDescriptions": [
            "The default value when this item does not inherit an ACL.\nUse NOT_APPLICABLE when\ninheritAclFrom\nis empty.  An item without ACL inheritance can still have ACLs supplied\nby its own readers and\ndeniedReaders fields.",
            "During an authorization conflict, the ACL of the child item determines\nits read access.",
            "During an authorization conflict, the ACL of the parent item\nspecified in the\ninheritAclFrom\nfield determines read access.",
            "Access is granted only if this item and the parent item specified in\nthe inheritAclFrom\nfield both permit read access."
          ],
          "enum": [
            "NOT_APPLICABLE",
            "CHILD_OVERRIDE",
            "PARENT_OVERRIDE",
            "BOTH_PERMIT"
          ],
          "description": "Sets the type of access rules to apply when an item inherits its ACL from a\nparent. This should always be set in tandem with the\ninheritAclFrom\nfield. Also, when the\ninheritAclFrom field\nis set, this field should be set to a valid AclInheritanceType.",
          "type": "string"
        },
        "owners": {
          "description": "Optional. List of owners for the item. This field has no bearing on\ndocument access permissions. It does, however, offer\na slight ranking boosts items where the querying user is an owner.\nThe maximum number of elements is 5.",
          "type": "array",
          "items": {
            "$ref": "Principal"
          }
        },
        "inheritAclFrom": {
          "description": "Name of the item to inherit the Access Permission List (ACL) from.\nNote: ACL inheritance *only* provides access permissions\nto child items and does not define structural relationships, nor does it\nprovide convenient ways to delete large groups of items.\nDeleting an ACL parent from the index only alters the access permissions of\nchild items that reference the parent in the\ninheritAclFrom\nfield. The item is still in the index, but may not\nvisible in search results[...]",
          "type": "string"
        },
        "deniedReaders": {
          "description": "List of principals who are explicitly denied access to the item in search\nresults. While principals are denied access by default, use denied readers\nto handle exceptions and override the list allowed readers.\nThe maximum number of elements is 100.",
          "type": "array",
          "items": {
            "$ref": "Principal"
          }
        },
        "readers": {
          "description": "List of principals who are allowed to see the item in search results.\nOptional if inheriting permissions from another item or if the item\nis not intended to be visible, such as\nvirtual\ncontainers.\nThe maximum number of elements is 1000.",
          "type": "array",
          "items": {
            "$ref": "Principal"
          }
        }
      }
    },
    "GmailFolderRestrict": {
      "id": "GmailFolderRestrict",
      "description": "Gmail Folder restricts (i.e. in Drafts/Sent/Chats/User Generated Labels).",
      "type": "object",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "IN_SENT",
            "IN_DRAFT",
            "CHATS",
            "IN_TRASH",
            "USER_GENERATED_LABEL"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "in:sent",
            "in:draft",
            "label:chats",
            "in:trash",
            "label:\u003cuser generated\u003e"
          ]
        }
      }
    },
    "RepositoryError": {
      "id": "RepositoryError",
      "description": "Errors when the connector is communicating to the source repository.",
      "type": "object",
      "properties": {
        "type": {
          "enumDescriptions": [
            "Unknown error.",
            "Unknown or unreachable host.",
            "DNS problem, such as the DNS server is not responding.",
            "Cannot connect to the repository server.",
            "Failed authentication due to incorrect credentials.",
            "Service account is not authorized for the repository.",
            "Repository server error.",
            "Quota exceeded.",
            "Server temporarily unavailable.",
            "Client-related error, such as an invalid request from the connector to\nthe repository server."
          ],
          "enum": [
            "UNKNOWN",
            "NETWORK_ERROR",
            "DNS_ERROR",
            "CONNECTION_ERROR",
            "AUTHENTICATION_ERROR",
            "AUTHORIZATION_ERROR",
            "SERVER_ERROR",
            "QUOTA_EXCEEDED",
            "SERVICE_UNAVAILABLE",
            "CLIENT_ERROR"
          ],
          "description": "Type of error.",
          "type": "string"
        },
        "errorMessage": {
          "description": "Message that describes the error. The maximum allowable length\nof the message is 8192 characters.",
          "type": "string"
        },
        "httpStatusCode": {
          "description": "Error codes.  Matches the definition of HTTP status codes.",
          "format": "int32",
          "type": "integer"
        }
      }
    },
    "Principal": {
      "description": "Reference to a user, group, or domain.",
      "type": "object",
      "properties": {
        "gsuitePrincipal": {
          "description": "This principal is a GSuite user, group or domain.",
          "$ref": "GSuitePrincipal"
        },
        "groupResourceName": {
          "description": "This principal is a group identified using an external identity.\nThe name field must specify the group resource name with this format:\nidentitysources/{source_id}/groups/{ID}",
          "type": "string"
        },
        "userResourceName": {
          "description": "This principal is a user identified using an external identity.\nThe name field must specify the user resource name with this format:\nidentitysources/{source_id}/users/{ID}",
          "type": "string"
        }
      },
      "id": "Principal"
    },
    "GetSearchApplicationQueryStatsResponse": {
      "id": "GetSearchApplicationQueryStatsResponse",
      "type": "object",
      "properties": {
        "stats": {
          "type": "array",
          "items": {
            "$ref": "SearchApplicationQueryStats"
          }
        }
      }
    },
    "ResultDebugInfo": {
      "type": "object",
      "properties": {
        "formattedDebugInfo": {
          "description": "General debug info formatted for display.",
          "type": "string"
        }
      },
      "id": "ResultDebugInfo",
      "description": "Debugging information about the result."
    },
    "SortOptions": {
      "type": "object",
      "properties": {
        "operatorName": {
          "description": "Name of the operator corresponding to the field to sort on.\nThe corresponding property must be marked as\nsortable.",
          "type": "string"
        },
        "sortOrder": {
          "type": "string",
          "enumDescriptions": [
            "",
            ""
          ],
          "enum": [
            "ASCENDING",
            "DESCENDING"
          ],
          "description": "Ascending is the default sort order"
        }
      },
      "id": "SortOptions"
    },
    "Schema": {
      "description": "The schema definition for a data source.",
      "type": "object",
      "properties": {
        "operationIds": {
          "description": "IDs of the Long Running Operations (LROs) currently running for this\nschema. After modifying the schema, wait for operations to complete\nbefore indexing additional content.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "objectDefinitions": {
          "description": "The list of top-level objects for the data source.\nThe maximum number of elements is 10.",
          "type": "array",
          "items": {
            "$ref": "ObjectDefinition"
          }
        }
      },
      "id": "Schema"
    },
    "PropertyDefinition": {
      "id": "PropertyDefinition",
      "description": "The definition of a property within an object.",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the property. Item indexing requests sent to the Indexing API\nshould set the property name\nequal to this value. For example, if name is *subject_line*, then indexing\nrequests for document items with subject fields should set the\nname for that field equal to\n*subject_line*. Use the name as the identifier for the object property.\nOnce registered as a property for an object, you cannot re-use this name\nfor another property within that object.\nThe name m[...]"
        },
        "booleanPropertyOptions": {
          "$ref": "BooleanPropertyOptions"
        },
        "timestampPropertyOptions": {
          "$ref": "TimestampPropertyOptions"
        },
        "doublePropertyOptions": {
          "$ref": "DoublePropertyOptions"
        },
        "textPropertyOptions": {
          "$ref": "TextPropertyOptions"
        },
        "isWildcardSearchable": {
          "description": "Indicates that users can perform wildcard search for this\nproperty. Only supported for Text properties. IsReturnable must be true to\nset this option. In a given datasource maximum of 5 properties can be\nmarked as is_wildcard_searchable.\n\nNote: This is an alpha feature and is enabled for whitelisted users only.",
          "type": "boolean"
        },
        "isRepeatable": {
          "description": "Indicates that multiple values are allowed for the property. For example, a\ndocument only has one description but can have multiple comments. Cannot be\ntrue for properties whose type is a boolean.\nIf set to false, properties that contain more than one value will cause the\nindexing request for that item to be rejected.",
          "type": "boolean"
        },
        "objectPropertyOptions": {
          "$ref": "ObjectPropertyOptions"
        },
        "isSuggestable": {
          "description": "Indicates that the property can be used for generating query suggestions.",
          "type": "boolean"
        },
        "integerPropertyOptions": {
          "$ref": "IntegerPropertyOptions"
        },
        "htmlPropertyOptions": {
          "$ref": "HtmlPropertyOptions"
        },
        "enumPropertyOptions": {
          "$ref": "EnumPropertyOptions"
        },
        "displayOptions": {
          "$ref": "PropertyDisplayOptions",
          "description": "Options that determine how the property is displayed in the Cloud Search\nresults page if it is specified to be displayed in the object's\ndisplay options\n."
        },
        "datePropertyOptions": {
          "$ref": "DatePropertyOptions"
        },
        "isSortable": {
          "description": "Indicates that the property can be used for sorting. Cannot be true for\nproperties that are repeatable. Cannot be true for properties whose type\nis object or user identifier. IsReturnable must be true to set this option.\nOnly supported for Boolean, Date, Double, Integer, and Timestamp\nproperties.",
          "type": "boolean"
        },
        "isFacetable": {
          "description": "Indicates that the property can be used for generating facets. Cannot be\ntrue for properties whose type is object. IsReturnable must be true to set\nthis option.\nOnly supported for Boolean, Enum, and Text properties.",
          "type": "boolean"
        },
        "isReturnable": {
          "description": "Indicates that the property identifies data that should be returned in\nsearch results via the Query API. If set to *true*, indicates that Query\nAPI users can use matching property fields in results. However, storing\nfields requires more space allocation and uses more bandwidth for search\nqueries, which impacts performance over large datasets. Set to *true* here\nonly if the field is needed for search results. Cannot be true for\nproperties whose type is an object.",
          "type": "boolean"
        }
      }
    },
    "GSuitePrincipal": {
      "type": "object",
      "properties": {
        "gsuiteUserEmail": {
          "type": "string",
          "description": "This principal references a G Suite user account"
        },
        "gsuiteGroupEmail": {
          "type": "string",
          "description": "This principal references a G Suite group account"
        },
        "gsuiteDomain": {
          "description": "This principal represents all users of the G Suite domain of the\ncustomer.",
          "type": "boolean"
        }
      },
      "id": "GSuitePrincipal"
    },
    "TextPropertyOptions": {
      "description": "Options for text properties.",
      "type": "object",
      "properties": {
        "retrievalImportance": {
          "$ref": "RetrievalImportance",
          "description": "Indicates the search quality importance of the tokens within the\nfield when used for retrieval."
        },
        "operatorOptions": {
          "$ref": "TextOperatorOptions",
          "description": "If set, describes how the property should be used as a search operator."
        }
      },
      "id": "TextPropertyOptions"
    },
    "SuggestResponse": {
      "type": "object",
      "properties": {
        "suggestResults": {
          "type": "array",
          "items": {
            "$ref": "SuggestResult"
          },
          "description": "List of suggestions."
        }
      },
      "id": "SuggestResponse",
      "description": "Response of the suggest API."
    },
    "PeopleSuggestion": {
      "type": "object",
      "properties": {
        "person": {
          "description": "Suggested person. All fields of the person object might not be populated.",
          "$ref": "Person"
        }
      },
      "id": "PeopleSuggestion",
      "description": "This field contains information about the person being suggested."
    },
    "IndexItemRequest": {
      "type": "object",
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "item": {
          "$ref": "Item",
          "description": "Name of the item.  Format:\ndatasources/{source_id}/items/{item_id}"
        },
        "connectorName": {
          "description": "Name of connector making this call.\n\u003cbr /\u003eFormat: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "indexItemOptions": {
          "$ref": "IndexItemOptions"
        },
        "mode": {
          "enum": [
            "UNSPECIFIED",
            "SYNCHRONOUS",
            "ASYNCHRONOUS"
          ],
          "description": "Required. The RequestMode for this request.",
          "type": "string",
          "enumDescriptions": [
            "Priority is not specified in the update request.\nLeaving priority unspecified results in an update failure.",
            "For real-time updates.",
            "For changes that are executed after the response is sent back to the\ncaller."
          ]
        }
      },
      "id": "IndexItemRequest"
    },
    "GmailIntelligentRestrict": {
      "type": "object",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "SOCIAL",
            "UPDATES",
            "FORUMS",
            "PROMOTIONS",
            "IMPORTANT",
            "FLIGHT_RESERVATION",
            "LODGING_RESERVATION",
            "CAR_RESERVATION",
            "BUS_RESERVATION"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "category:social",
            "category:updates",
            "category:forums",
            "category:promotions",
            "is:important",
            "label:^cob_sm_flightreservation",
            "label:^cob_sm_lodgingreservation",
            "label:^cob_sm_rentalcarreservation",
            "label:^cob_sm_busreservation"
          ]
        }
      },
      "id": "GmailIntelligentRestrict",
      "description": "Gmail Intelligent restricts (i.e. smartlabels, important)."
    },
    "QueryInterpretationOptions": {
      "description": "Options to interpret user query.",
      "type": "object",
      "properties": {
        "enableVerbatimMode": {
          "description": "Enable this flag to turn off all internal optimizations like natural\nlanguage (NL) interpretation of queries, supplemental result retrieval,\nand usage of synonyms including custom ones.\nNl interpretation will be disabled if either one of the two flags is true.",
          "type": "boolean"
        },
        "disableNlInterpretation": {
          "type": "boolean",
          "description": "Flag to disable natural language (NL) interpretation of queries. Default is\nfalse, Set to true to disable natural language interpretation. NL\ninterpretation only applies to predefined datasources."
        }
      },
      "id": "QueryInterpretationOptions"
    },
    "Snippet": {
      "description": "Snippet of the search result, which summarizes the content of the resulting\npage.",
      "type": "object",
      "properties": {
        "matchRanges": {
          "description": "The matched ranges in the snippet.",
          "type": "array",
          "items": {
            "$ref": "MatchRange"
          }
        },
        "snippet": {
          "description": "The snippet of the document.\nThe snippet of the document. May contain escaped HTML character that\nshould be unescaped prior to rendering.",
          "type": "string"
        }
      },
      "id": "Snippet"
    },
    "DriveFollowUpRestrict": {
      "description": "Drive follow-up search restricts (e.g. \"followup:suggestions\").",
      "type": "object",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "FOLLOWUP_SUGGESTIONS",
            "FOLLOWUP_ACTION_ITEMS"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            ""
          ]
        }
      },
      "id": "DriveFollowUpRestrict"
    },
    "GmailActionRestrict": {
      "description": "Gmail Action restricts (i.e. read/replied/snoozed).",
      "type": "object",
      "properties": {
        "type": {
          "enumDescriptions": [
            "",
            "is:unread",
            "is:read",
            "label:^io_re",
            "label:mute"
          ],
          "enum": [
            "UNSPECIFIED",
            "UNREAD",
            "READ",
            "REPLIED_TO",
            "MUTED"
          ],
          "type": "string"
        }
      },
      "id": "GmailActionRestrict"
    },
    "IntegerValues": {
      "type": "object",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "format": "int64",
            "type": "string"
          }
        }
      },
      "id": "IntegerValues",
      "description": "List of integer values."
    },
    "DoublePropertyOptions": {
      "type": "object",
      "properties": {
        "operatorOptions": {
          "description": "If set, describes how the double should be used as a search operator.",
          "$ref": "DoubleOperatorOptions"
        }
      },
      "id": "DoublePropertyOptions",
      "description": "Options for double properties."
    },
    "SearchApplicationSessionStats": {
      "id": "SearchApplicationSessionStats",
      "type": "object",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "Date for which session stats were calculated. Stats calculated on the next\nday close to midnight are returned."
        },
        "searchSessionsCount": {
          "type": "string",
          "description": "The count of search sessions on the day",
          "format": "int64"
        }
      }
    },
    "BooleanPropertyOptions": {
      "description": "Options for boolean properties.",
      "type": "object",
      "properties": {
        "operatorOptions": {
          "$ref": "BooleanOperatorOptions",
          "description": "If set, describes how the boolean should be used as a search operator."
        }
      },
      "id": "BooleanPropertyOptions"
    },
    "SearchRequest": {
      "id": "SearchRequest",
      "description": "The search API request.",
      "type": "object",
      "properties": {
        "queryInterpretationOptions": {
          "$ref": "QueryInterpretationOptions",
          "description": "Options to interpret the user query."
        },
        "requestOptions": {
          "$ref": "RequestOptions",
          "description": "Request options, such as the search application and user timezone."
        },
        "dataSourceRestrictions": {
          "description": "The sources to use for querying. If not specified, all data sources\nfrom the current search application are used.",
          "type": "array",
          "items": {
            "$ref": "DataSourceRestriction"
          }
        },
        "sortOptions": {
          "$ref": "SortOptions",
          "description": "The options for sorting the search results"
        },
        "facetOptions": {
          "type": "array",
          "items": {
            "$ref": "FacetOptions"
          }
        },
        "pageSize": {
          "description": "Maximum number of search results to return in one page.\nValid values are between 1 and 100, inclusive.\nDefault value is 10.",
          "format": "int32",
          "type": "integer"
        },
        "query": {
          "type": "string",
          "description": "The raw query string.\nSee supported search operators in the [Cloud search\nCheat\nSheet](https://gsuite.google.com/learning-center/products/cloudsearch/cheat-sheet/)"
        },
        "start": {
          "description": "Starting index of the results.",
          "format": "int32",
          "type": "integer"
        }
      }
    },
    "CompositeFilter": {
      "type": "object",
      "properties": {
        "subFilters": {
          "type": "array",
          "items": {
            "$ref": "Filter"
          },
          "description": "Sub filters."
        },
        "logicOperator": {
          "enumDescriptions": [
            "Logical operators, which can only be applied to sub filters.",
            "",
            "NOT can only be applied on a single sub filter."
          ],
          "enum": [
            "AND",
            "OR",
            "NOT"
          ],
          "description": "The logic operator of the sub filter.",
          "type": "string"
        }
      },
      "id": "CompositeFilter"
    },
    "EnumValuePair": {
      "description": "The enumeration value pair defines two things: a required string value and\nan optional integer value. The string value defines the necessary query\nterm required to retrieve that item, such as *p0* for a priority item.\nThe integer value determines the ranking of that string value relative\nto other enumerated values for the same property. For example, you might\nassociate *p0* with *0* and define another enum pair such as *p1* and *1*.\nYou must use the integer value in c[...]",
      "type": "object",
      "properties": {
        "stringValue": {
          "description": "The string value of the EnumValuePair.\nThe maximum length is 32 characters.",
          "type": "string"
        },
        "integerValue": {
          "description": "The integer value of the EnumValuePair which must be non-negative.\nOptional.",
          "format": "int32",
          "type": "integer"
        }
      },
      "id": "EnumValuePair"
    },
    "SearchItemsByViewUrlResponse": {
      "id": "SearchItemsByViewUrlResponse",
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "Item"
          }
        },
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no\nmore results in the list.",
          "type": "string"
        }
      }
    },
    "ObjectOptions": {
      "id": "ObjectOptions",
      "description": "The options for an object.",
      "type": "object",
      "properties": {
        "freshnessOptions": {
          "$ref": "FreshnessOptions",
          "description": "The freshness options for an object."
        },
        "displayOptions": {
          "$ref": "ObjectDisplayOptions",
          "description": "Options that determine how the object is displayed in the Cloud Search\nresults page."
        }
      }
    },
    "GetCustomerUserStatsResponse": {
      "type": "object",
      "properties": {
        "stats": {
          "type": "array",
          "items": {
            "$ref": "CustomerUserStats"
          }
        }
      },
      "id": "GetCustomerUserStatsResponse"
    },
    "DeleteQueueItemsRequest": {
      "id": "DeleteQueueItemsRequest",
      "type": "object",
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "connectorName": {
          "type": "string",
          "description": "Name of connector making this call.\n\u003cbr /\u003eFormat: datasources/{source_id}/connectors/{ID}"
        },
        "queue": {
          "type": "string",
          "description": "Name of a queue to delete items from."
        }
      }
    },
    "DriveTimeSpanRestrict": {
      "id": "DriveTimeSpanRestrict",
      "description": "The time span search restrict (e.g. \"after:2017-09-11 before:2017-09-12\").",
      "type": "object",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "TODAY",
            "YESTERDAY",
            "LAST_7_DAYS",
            "LAST_30_DAYS",
            "LAST_90_DAYS"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "Not Enabled",
            "Not Enabled"
          ]
        }
      }
    },
    "FacetOptions": {
      "description": "Specifies operators to return facet results for. There will be one\nFacetResult for every source_name/object_type/operator_name combination.",
      "type": "object",
      "properties": {
        "objectType": {
          "description": "If object_type is set, only those objects of that type will be used to\ncompute facets. If empty, then all objects will be used to compute facets.",
          "type": "string"
        },
        "sourceName": {
          "description": "Source name to facet on. Format: datasources/{source_id}\nIf empty, all data sources will be used.",
          "type": "string"
        },
        "numFacetBuckets": {
          "type": "integer",
          "description": "Maximum number of facet buckets that should be returned for this facet.\nDefaults to 10.\nMaximum value is 100.",
          "format": "int32"
        },
        "operatorName": {
          "description": "Name of the operator chosen for faceting. @see\ncloudsearch.SchemaPropertyOptions",
          "type": "string"
        }
      },
      "id": "FacetOptions"
    },
    "Person": {
      "description": "Object to represent a person.",
      "type": "object",
      "properties": {
        "photos": {
          "type": "array",
          "items": {
            "$ref": "Photo"
          },
          "description": "A person's read-only photo. A picture shown next to the person's name to\nhelp others recognize the person in search results."
        },
        "personNames": {
          "description": "The person's name",
          "type": "array",
          "items": {
            "$ref": "Name"
          }
        },
        "emailAddresses": {
          "description": "The person's email addresses",
          "type": "array",
          "items": {
            "$ref": "EmailAddress"
          }
        },
        "name": {
          "type": "string",
          "description": "The resource name of the person to provide information about.\nSee \u003ca href=\"https://developers.google.com/people/api/rest/v1/people/get\"\u003e\nPeople.get\u003c/a\u003e from Google People API."
        },
        "obfuscatedId": {
          "description": "Obfuscated ID of a person.",
          "type": "string"
        }
      },
      "id": "Person"
    },
    "GetDataSourceIndexStatsResponse": {
      "type": "object",
      "properties": {
        "stats": {
          "description": "Summary of indexed item counts, one for each day in the requested range.",
          "type": "array",
          "items": {
            "$ref": "DataSourceIndexStats"
          }
        }
      },
      "id": "GetDataSourceIndexStatsResponse"
    },
    "StructuredResult": {
      "id": "StructuredResult",
      "description": "Structured results that are returned as part of search request.",
      "type": "object",
      "properties": {
        "person": {
          "$ref": "Person",
          "description": "Representation of a person"
        }
      }
    },
    "ResultDisplayMetadata": {
      "id": "ResultDisplayMetadata",
      "type": "object",
      "properties": {
        "objectTypeLabel": {
          "description": "The display label for the object.",
          "type": "string"
        },
        "metalines": {
          "description": "The metalines content to be displayed with the result.",
          "type": "array",
          "items": {
            "$ref": "ResultDisplayLine"
          }
        }
      }
    },
    "SpellResult": {
      "id": "SpellResult",
      "type": "object",
      "properties": {
        "suggestedQuery": {
          "type": "string",
          "description": "The suggested spelling of the query."
        }
      }
    },
    "SearchApplication": {
      "description": "SearchApplication",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the Search Application.\n\u003cbr /\u003eFormat: searchapplications/{application_id}.",
          "type": "string"
        },
        "operationIds": {
          "description": "IDs of the Long Running Operations (LROs) currently running for this\nschema. Output only field.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "dataSourceRestrictions": {
          "type": "array",
          "items": {
            "$ref": "DataSourceRestriction"
          },
          "description": "Retrictions applied to the configurations.\nThe maximum number of elements is 10."
        },
        "sourceConfig": {
          "description": "Configuration for a sources specified in data_source_restrictions.",
          "type": "array",
          "items": {
            "$ref": "SourceConfig"
          }
        },
        "defaultSortOptions": {
          "description": "The default options for sorting the search results",
          "$ref": "SortOptions"
        },
        "displayName": {
          "type": "string",
          "description": "Display name of the Search Application.\nThe maximum length is 300 characters."
        },
        "defaultFacetOptions": {
          "type": "array",
          "items": {
            "$ref": "FacetOptions"
          },
          "description": "The default fields for returning facet results.\nThe sources specified here also have been included in\ndata_source_restrictions\nabove."
        },
        "scoringConfig": {
          "$ref": "ScoringConfig",
          "description": "Configuration for ranking results."
        }
      },
      "id": "SearchApplication"
    },
    "DoubleOperatorOptions": {
      "type": "object",
      "properties": {
        "operatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to use the\ndouble property in sorting or as a facet.\nThe operator name can only contain lowercase letters (a-z).\nThe maximum length is 32 characters."
        }
      },
      "id": "DoubleOperatorOptions",
      "description": "Used to provide a search operator for double properties. This is\noptional. Search operators let users restrict the query to specific fields\nrelevant to the type of item being searched."
    },
    "QuerySuggestion": {
      "description": "This field does not contain anything as of now and is just used as an\nindicator that the suggest result was a phrase completion.",
      "type": "object",
      "properties": {},
      "id": "QuerySuggestion"
    },
    "PollItemsRequest": {
      "type": "object",
      "properties": {
        "connectorName": {
          "description": "Name of connector making this call.\n\u003cbr /\u003eFormat: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "queue": {
          "description": "Queue name to fetch items from.  If unspecified, PollItems will\nfetch from 'default' queue.\nThe maximum length is 100 characters.",
          "type": "string"
        },
        "limit": {
          "description": "Maximum number of items to return.\n\u003cbr /\u003eThe maximum and the default value is 1000",
          "format": "int32",
          "type": "integer"
        },
        "statusCodes": {
          "description": "Limit the items polled to the ones with these statuses.",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "CODE_UNSPECIFIED",
              "ERROR",
              "MODIFIED",
              "NEW_ITEM",
              "ACCEPTED"
            ]
          },
          "enumDescriptions": [
            "Input-only value.  Used with\nItems.list\nto list all items in the queue, regardless of status.",
            "Error encountered by Cloud Search while processing this item.\nDetails of the error are in\nrepositoryError.",
            "Item has been modified in the repository, and is out of date with\nthe version previously accepted into Cloud Search.",
            "Item is known to exist in the repository, but is not yet accepted by\nCloud Search.\nAn item can be in this state when\nItems.push\nhas been called for\nan item of this name that did not exist previously.",
            "API has accepted the up-to-date data of this item."
          ]
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      },
      "id": "PollItemsRequest"
    },
    "EnumOperatorOptions": {
      "id": "EnumOperatorOptions",
      "description": "Used to provide a search operator for enum properties. This is\noptional. Search operators let users restrict the query to specific fields\nrelevant to the type of item being searched. For example, if you provide no\noperator for a *priority* enum property with possible values *p0* and *p1*,\na query that contains the term *p0* will return items that have *p0* as the\nvalue of the *priority* property, as well as any items that contain the\nstring *p0* in other fields. If yo[...]",
      "type": "object",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\nenum property. For example, if operatorName is *priority* and the\nproperty's name is *priorityVal*, then queries like\n*priority:&lt;value&gt;* will show results only where the value of the\nproperty named *priorityVal* matches *&lt;value&gt;*. By contrast, a\nsearch that uses the same *&lt;value&gt;* without an operator will return\nall items where *&lt;value&gt;* matches the value of any Strin[...]",
          "type": "string"
        }
      }
    },
    "SearchResponse": {
      "id": "SearchResponse",
      "description": "The search API response.",
      "type": "object",
      "properties": {
        "resultCountEstimate": {
          "description": "The estimated result count for this query.",
          "format": "int64",
          "type": "string"
        },
        "debugInfo": {
          "$ref": "ResponseDebugInfo",
          "description": "Debugging information about the response."
        },
        "resultCounts": {
          "$ref": "ResultCounts",
          "description": "Expanded result count information."
        },
        "facetResults": {
          "description": "Repeated facet results.",
          "type": "array",
          "items": {
            "$ref": "FacetResult"
          }
        },
        "structuredResults": {
          "type": "array",
          "items": {
            "$ref": "StructuredResult"
          },
          "description": "Structured results for the user query. These results are not counted\nagainst the page_size."
        },
        "spellResults": {
          "description": "Suggested spelling for the query.",
          "type": "array",
          "items": {
            "$ref": "SpellResult"
          }
        },
        "resultCountExact": {
          "type": "string",
          "description": "The exact result count for this query.",
          "format": "int64"
        },
        "queryInterpretation": {
          "$ref": "QueryInterpretation",
          "description": "Query interpretation result for user query. Empty if query interpretation\nis disabled."
        },
        "hasMoreResults": {
          "description": "Whether there are more search results matching the query.",
          "type": "boolean"
        },
        "errorInfo": {
          "$ref": "ErrorInfo",
          "description": "Error information about the response."
        },
        "results": {
          "description": "Results from a search query.",
          "type": "array",
          "items": {
            "$ref": "SearchResult"
          }
        }
      }
    },
    "PropertyDisplayOptions": {
      "id": "PropertyDisplayOptions",
      "description": "The display options for a property.",
      "type": "object",
      "properties": {
        "displayLabel": {
          "description": "The user friendly label for the property that will be used if the property\nis specified to be displayed in ObjectDisplayOptions. If given, the display\nlabel will be shown in front of the property values when the property is\npart of the object display options. For example, if the property value is\n'1', the value by itself may not be useful context for the user. If the\ndisplay name given was 'priority', then the user will see 'priority : 1' in\nthe search results whi[...]",
          "type": "string"
        }
      }
    },
    "ObjectDefinition": {
      "description": "The definition for an object within a data source.",
      "type": "object",
      "properties": {
        "options": {
          "description": "The optional object-specific options.",
          "$ref": "ObjectOptions"
        },
        "propertyDefinitions": {
          "description": "The property definitions for the object.\nThe maximum number of elements is 1000.",
          "type": "array",
          "items": {
            "$ref": "PropertyDefinition"
          }
        },
        "name": {
          "description": "Name for the object, which then defines its type. Item indexing requests\nshould set the\nobjectType field\nequal to this value. For example, if *name* is *Document*, then indexing\nrequests for items of type Document should set\nobjectType equal to\n*Document*. Each object definition must be uniquely named within a schema.\nThe name must start with a letter and can only contain letters (A-Z, a-z)\nor numbers (0-9).\nThe maximum length is 256 characters.",
          "type": "string"
        }
      },
      "id": "ObjectDefinition"
    },
    "FreshnessOptions": {
      "description": "Indicates which freshness property to use when adjusting search ranking for\nan item. Fresher, more recent dates indicate higher quality. Use the\nfreshness option property that best works with your data. For fileshare\ndocuments, last modified time is most relevant. For calendar event data,\nthe time when the event occurs is a more relevant freshness indicator. In\nthis way, calendar events that occur closer to the time of the search query\nare considered higher quality an[...]",
      "type": "object",
      "properties": {
        "freshnessDuration": {
          "description": "The duration after which an object should be considered\nstale. The default value is 180 days (in seconds).",
          "format": "google-duration",
          "type": "string"
        },
        "freshnessProperty": {
          "description": "This property indicates the freshness level of the object in the index.\nIf set, this property must be a top-level property within the\nproperty definitions\nand it must be a\ntimestamp type\nor\ndate type.\nOtherwise, the Indexing API uses\nupdateTime\nas the freshness indicator.\nThe maximum length is 256 characters.\n\nWhen a property is used to calculate fresheness, the value defaults\nto 2 years from the current time.",
          "type": "string"
        }
      },
      "id": "FreshnessOptions"
    },
    "SearchApplicationQueryStats": {
      "type": "object",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "Date for which query stats were calculated. Stats calculated on the next\nday close to midnight are returned."
        },
        "queryCountByStatus": {
          "type": "array",
          "items": {
            "$ref": "QueryCountByStatus"
          }
        }
      },
      "id": "SearchApplicationQueryStats"
    },
    "UploadItemRef": {
      "description": "Represents an upload session reference.\nThis reference is created via upload\nmethod.\nUpdating of item content may refer to this uploaded content via\ncontentDataRef.",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the content reference.\nThe maximum length is 2048 characters."
        }
      },
      "id": "UploadItemRef"
    },
    "EmailAddress": {
      "description": "A person's email address.",
      "type": "object",
      "properties": {
        "emailAddress": {
          "type": "string",
          "description": "The email address."
        }
      },
      "id": "EmailAddress"
    },
    "HtmlOperatorOptions": {
      "description": "Used to provide a search operator for html properties. This is optional.\nSearch operators let users restrict the query to specific fields relevant\nto the type of item being searched.",
      "type": "object",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\nhtml property. For example, if operatorName is *subject* and the\nproperty's name is *subjectLine*, then queries like\n*subject:&lt;value&gt;* will show results only where the value of the\nproperty named *subjectLine* matches *&lt;value&gt;*. By contrast, a\nsearch that uses the same *&lt;value&gt;* without an operator will return\nall items where *&lt;value&gt;* matches the value of any\nhtml p[...]",
          "type": "string"
        }
      },
      "id": "HtmlOperatorOptions"
    },
    "GmailTimeRestrict": {
      "type": "object",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "FROM_THIS_WEEK",
            "OLDER_THAN_ONE_YEAR",
            "FROM_TODAY",
            "FROM_YESTERDAY",
            "FROM_THIS_MONTH",
            "FROM_CERTAIN_MONTH",
            "OLDER_THAN_TODAY",
            "OLDER_THAN_YESTERDAY",
            "OLDER_THAN_A_WEEK",
            "OLDER_THAN_A_MONTH"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "newer_than:7d",
            "older_than:1y",
            "newer_than:1d",
            "newer_than:2d older_than:1d",
            "newer_than:30d",
            "This will read as something like \"From November\" and will have operator\nbefore:X after:Y",
            "older_than:1d",
            "older_than:2d",
            "older_than:7d",
            "older_than:30d"
          ]
        }
      },
      "id": "GmailTimeRestrict",
      "description": "Gmail Time restricts (i.e. received today, this week)."
    },
    "QueryItem": {
      "description": "Information relevant only to a query entry.",
      "type": "object",
      "properties": {
        "isSynthetic": {
          "description": "True if the text was generated by means other than a previous user search.",
          "type": "boolean"
        }
      },
      "id": "QueryItem"
    },
    "ItemContent": {
      "description": "Content of an item to be indexed and surfaced by Cloud Search.",
      "type": "object",
      "properties": {
        "contentFormat": {
          "enumDescriptions": [
            "Invalid value.",
            "contentFormat is HTML.",
            "contentFormat is free text.",
            "contentFormat is raw bytes."
          ],
          "enum": [
            "UNSPECIFIED",
            "HTML",
            "TEXT",
            "RAW"
          ],
          "type": "string"
        },
        "hash": {
          "description": "Hashing info calculated and provided by the API client for content.\nCan be used with the items.push method to calculate modified state.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "inlineContent": {
          "description": "Content that is supplied inlined within the update method.\nThe maximum length is 102400 bytes (100 KiB).",
          "format": "byte",
          "type": "string"
        },
        "contentDataRef": {
          "$ref": "UploadItemRef",
          "description": "Upload reference ID of a previously uploaded content via write method."
        }
      },
      "id": "ItemContent"
    },
    "CustomerIndexStats": {
      "type": "object",
      "properties": {
        "itemCountByStatus": {
          "description": "Number of items aggregrated by status code.",
          "type": "array",
          "items": {
            "$ref": "ItemCountByStatus"
          }
        },
        "date": {
          "$ref": "Date",
          "description": "Date for which statistics were calculated."
        }
      },
      "id": "CustomerIndexStats",
      "description": "Aggregation of items by status code as of the specified date."
    },
    "SourceCrowdingConfig": {
      "id": "SourceCrowdingConfig",
      "description": "Set search results crowding limits. Crowding is a situation in which\nmultiple results from the same source or host \"crowd out\" other results,\ndiminishing the quality of search for users. To foster better search quality\nand source diversity in search results, you can set a condition to reduce\nrepetitive results by source.",
      "type": "object",
      "properties": {
        "numResults": {
          "description": "Maximum number of results allowed from a source.\nNo limits will be set on results if this value is less than or equal to 0.",
          "format": "int32",
          "type": "integer"
        },
        "numSuggestions": {
          "description": "Maximum number of suggestions allowed from a source.\nNo limits will be set on results if this value is less than or equal to 0.",
          "format": "int32",
          "type": "integer"
        }
      }
    },
    "PushItem": {
      "type": "object",
      "properties": {
        "metadataHash": {
          "description": "Metadata hash of the item according to the repository. If specified, this\nis used to determine how to modify this\nitem's status. Setting this field and the\ntype field results in argument\nerror.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "payload": {
          "type": "string",
          "description": "Provides additional document state information for the connector,\nsuch as an alternate repository ID and other metadata.\nThe maximum length is 8192 bytes.",
          "format": "byte"
        },
        "repositoryError": {
          "description": "Populate this field to store Connector or repository error details.\nThis information is displayed in the Admin Console.\nThis field may only be populated when the\nType is\nREPOSITORY_ERROR.",
          "$ref": "RepositoryError"
        },
        "type": {
          "description": "The type of the push operation that defines the push behavior.",
          "type": "string",
          "enumDescriptions": [
            "Default UNSPECIFIED.  Specifies that the push operation should not modify\nItemStatus",
            "Indicates that the repository document has been modified or updated since\nthe previous\nupdate\ncall. This changes status to\nMODIFIED state for\nan existing item. If this is called on a non existing item, the status is\nchanged to\nNEW_ITEM.",
            "Item in the repository has not been modified since the last update\ncall.  This push operation will set status to\nACCEPTED state.",
            "Connector is facing a repository error regarding this item.  Change\nstatus to\nREPOSITORY_ERROR\nstate. Item is unreserved and rescheduled at a future time determined by\nexponential backoff.",
            "Call push with REQUEUE only for items that have been reserved.\nThis action unreserves the item and resets its available time to the\nwall clock time."
          ],
          "enum": [
            "UNSPECIFIED",
            "MODIFIED",
            "NOT_MODIFIED",
            "REPOSITORY_ERROR",
            "REQUEUE"
          ]
        },
        "structuredDataHash": {
          "description": "Structured data hash of the item according to the repository. If specified,\nthis is used to determine how to modify this item's status. Setting this\nfield and the type field\nresults in argument error.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "queue": {
          "description": "Queue to which this item belongs to.  The \u003ccode\u003edefault\u003c/code\u003e queue is\nchosen if this field is not specified. The maximum length is\n512 characters.",
          "type": "string"
        },
        "contentHash": {
          "description": "Content hash of the item according to the repository. If specified, this is\nused to determine how to modify this\nitem's status. Setting this field and the\ntype field results in argument\nerror.\nThe maximum length is 2048 characters.",
          "type": "string"
        }
      },
      "id": "PushItem",
      "description": "Represents an item to be pushed to the indexing queue."
    },
    "ObjectDisplayOptions": {
      "description": "The display options for an object.",
      "type": "object",
      "properties": {
        "objectDisplayLabel": {
          "description": "The user friendly label to display in the search result to inidicate the\ntype of the item. This is OPTIONAL; if not given, an object label will not\nbe displayed on the context line of the search results. The maximum length\nis 32 characters.",
          "type": "string"
        },
        "metalines": {
          "description": "Defines the properties that will be displayed in the metalines of the\nsearch results. The property values will be displayed in the order given\nhere. If a property holds multiple values, all of the values will be\ndiplayed before the next properties. For this reason, it is a good practice\nto specify singular properties before repeated properties in this list. All\nof the properties must set\nis_returnable\nto true. The maximum number of metalines is 3.",
          "type": "array",
          "items": {
            "$ref": "Metaline"
          }
        }
      },
      "id": "ObjectDisplayOptions"
    },
    "CheckAccessResponse": {
      "type": "object",
      "properties": {
        "hasAccess": {
          "description": "Returns true if principal has access.  Returns false otherwise.",
          "type": "boolean"
        }
      },
      "id": "CheckAccessResponse"
    },
    "Date": {
      "type": "object",
      "properties": {
        "year": {
          "description": "Year of date. Must be from 1 to 9999.",
          "format": "int32",
          "type": "integer"
        },
        "day": {
          "description": "Day of month. Must be from 1 to 31 and valid for the year and month.",
          "format": "int32",
          "type": "integer"
        },
        "month": {
          "description": "Month of date. Must be from 1 to 12.",
          "format": "int32",
          "type": "integer"
        }
      },
      "id": "Date",
      "description": "Represents a whole calendar date, for example a date of birth. The time of day and time zone are either specified elsewhere or are not significant. The date is relative to the [Proleptic Gregorian Calendar](https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar). The date must be a valid calendar date between the year 1 and 9999."
    },
    "HtmlValues": {
      "description": "List of html values.",
      "type": "object",
      "properties": {
        "values": {
          "description": "The maximum allowable length for html values is 2048 characters.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "id": "HtmlValues"
    },
    "ListSearchApplicationsResponse": {
      "id": "ListSearchApplicationsResponse",
      "type": "object",
      "properties": {
        "searchApplications": {
          "type": "array",
          "items": {
            "$ref": "SearchApplication"
          }
        },
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no\nmore results in the list.",
          "type": "string"
        }
      }
    },
    "TimestampOperatorOptions": {
      "id": "TimestampOperatorOptions",
      "description": "Used to provide a search operator for timestamp properties. This is\noptional. Search operators let users restrict the query to specific fields\nrelevant to the type of item being searched.",
      "type": "object",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ntimestamp property. For example, if operatorName is *closedon* and the\nproperty's name is *closeDate*, then queries like\n*closedon:&lt;value&gt;* will show results only where the value of the\nproperty named *closeDate* matches *&lt;value&gt;*. By contrast, a\nsearch that uses the same *&lt;value&gt;* without an operator will return\nall items where *&lt;value&gt;* matches the value of any Stri[...]",
          "type": "string"
        },
        "greaterThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the\ntimestamp property using the greater-than operator. For example, if\ngreaterThanOperatorName is *closedafter* and the property's name is\n*closeDate*, then queries like *closedafter:&lt;value&gt;* will\nshow results only where the value of the property named *closeDate* is\nlater than *&lt;value&gt;*.\nThe operator name can only contain lowercase letters (a-z).\nThe maximum length is 32 character[...]"
        },
        "lessThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ntimestamp property using the less-than operator. For example, if\nlessThanOperatorName is *closedbefore* and the property's name is\n*closeDate*, then queries like *closedbefore:&lt;value&gt;* will\nshow results only where the value of the property named *closeDate* is\nearlier than *&lt;value&gt;*.\nThe operator name can only contain lowercase letters (a-z).\nThe maximum length is 32 characters.[...]",
          "type": "string"
        }
      }
    },
    "SearchResult": {
      "id": "SearchResult",
      "description": "Results containing indexed information for a document.",
      "type": "object",
      "properties": {
        "metadata": {
          "description": "Metadata of the search result.",
          "$ref": "Metadata"
        },
        "snippet": {
          "description": "The concatenation of all snippets (summaries) available for this result.",
          "$ref": "Snippet"
        },
        "title": {
          "description": "Title of the search result.",
          "type": "string"
        },
        "debugInfo": {
          "description": "Debugging information about this search result.",
          "$ref": "ResultDebugInfo"
        },
        "clusteredResults": {
          "description": "If source is clustered, provide list of clustered results. There will only\nbe one level of clustered results. If current source is not enabled for\nclustering, this field will be empty.",
          "type": "array",
          "items": {
            "$ref": "SearchResult"
          }
        },
        "url": {
          "type": "string",
          "description": "The URL of the search result. The URL contains a Google redirect to the\nactual item. This URL is signed and shouldn't be changed."
        }
      }
    },
    "DoubleValues": {
      "id": "DoubleValues",
      "description": "List of double values.",
      "type": "object",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "double"
          }
        }
      }
    },
    "ListDataSourceResponse": {
      "id": "ListDataSourceResponse",
      "type": "object",
      "properties": {
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no\nmore results in the list.",
          "type": "string"
        },
        "sources": {
          "type": "array",
          "items": {
            "$ref": "DataSource"
          }
        }
      }
    },
    "ErrorInfo": {
      "description": "Error information about the response.",
      "type": "object",
      "properties": {
        "errorMessages": {
          "type": "array",
          "items": {
            "$ref": "ErrorMessage"
          }
        }
      },
      "id": "ErrorInfo"
    },
    "ObjectValues": {
      "id": "ObjectValues",
      "description": "List of object values.",
      "type": "object",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "$ref": "StructuredDataObject"
          }
        }
      }
    },
    "DateValues": {
      "type": "object",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "$ref": "Date"
          }
        }
      },
      "id": "DateValues",
      "description": "List of date values."
    },
    "Source": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Source name for content indexed by the\nIndexing API."
        },
        "predefinedSource": {
          "enum": [
            "NONE",
            "QUERY_HISTORY",
            "PERSON",
            "GOOGLE_DRIVE",
            "GOOGLE_GMAIL",
            "GOOGLE_SITES",
            "GOOGLE_GROUPS",
            "GOOGLE_CALENDAR",
            "GOOGLE_KEEP"
          ],
          "description": "Predefined content source for Google Apps.",
          "type": "string",
          "enumDescriptions": [
            "",
            "Suggests queries issued by the user in the past. Only valid when used\nwith the suggest API. Ignored when used in the query API.",
            "Suggests people in the organization. Only valid when used\nwith the suggest API. Results in an error when used in the query API.",
            "",
            "",
            "",
            "",
            "",
            ""
          ]
        }
      },
      "id": "Source",
      "description": "Defines sources for the suggest/search APIs."
    },
    "Metadata": {
      "description": "Metadata of a matched search result.",
      "type": "object",
      "properties": {
        "fields": {
          "description": "Indexed fields in structured data, returned as a generic named property.",
          "type": "array",
          "items": {
            "$ref": "NamedProperty"
          }
        },
        "owner": {
          "$ref": "Person",
          "description": "Owner (usually creator) of the document or object of the search result."
        },
        "updateTime": {
          "type": "string",
          "description": "The last modified date for the object in the search result. If not\nset in the item, the value returned here is empty. When\n`updateTime` is used for calculating freshness and is not set, this\nvalue defaults to 2 years from the current time.",
          "format": "google-datetime"
        },
        "mimeType": {
          "description": "Mime type of the search result.",
          "type": "string"
        },
        "objectType": {
          "type": "string",
          "description": "Object type of the search result."
        },
        "displayOptions": {
          "$ref": "ResultDisplayMetadata",
          "description": "Options that specify how to display a structured data search result."
        },
        "source": {
          "$ref": "Source",
          "description": "The named source for the result, such as Gmail."
        },
        "createTime": {
          "description": "The creation time for this document or object in the search result.",
          "format": "google-datetime",
          "type": "string"
        }
      },
      "id": "Metadata"
    },
    "MatchRange": {
      "description": "Matched range of a snippet [start, end).",
      "type": "object",
      "properties": {
        "end": {
          "description": "End of the match in the snippet.",
          "format": "int32",
          "type": "integer"
        },
        "start": {
          "description": "Starting position of the match in the snippet.",
          "format": "int32",
          "type": "integer"
        }
      },
      "id": "MatchRange"
    }
  },
  "protocol": "rest",
  "canonicalName": "Cloud Search",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud_search": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.query": {
          "description": "Search your organization's data in the Cloud Search index"
        },
        "https://www.googleapis.com/auth/cloud_search.settings": {
          "description": "New Service: https://www.googleapis.com/auth/cloud_search.settings"
        },
        "https://www.googleapis.com/auth/cloud_search.debug": {
          "description": "New Service: https://www.googleapis.com/auth/cloud_search.debug"
        },
        "https://www.googleapis.com/auth/cloud_search.indexing": {
          "description": "New Service: https://www.googleapis.com/auth/cloud_search.indexing"
        },
        "https://www.googleapis.com/auth/cloud_search.settings.indexing": {
          "description": "New Service: https://www.googleapis.com/auth/cloud_search.settings.indexing"
        },
        "https://www.googleapis.com/auth/cloud_search.stats.indexing": {
          "description": "New Service: https://www.googleapis.com/auth/cloud_search.stats.indexing"
        },
        "https://www.googleapis.com/auth/cloud_search.stats": {
          "description": "New Service: https://www.googleapis.com/auth/cloud_search.stats"
        },
        "https://www.googleapis.com/auth/cloud_search.settings.query": {
          "description": "New Service: https://www.googleapis.com/auth/cloud_search.settings.query"
        }
      }
    }
  },
  "rootUrl": "https://cloudsearch.googleapis.com/",
  "ownerDomain": "google.com",
  "name": "cloudsearch",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "title": "Cloud Search API",
  "ownerName": "Google",
  "resources": {
    "media": {
      "methods": {
        "upload": {
          "flatPath": "v1/media/{mediaId}",
          "path": "v1/media/{+resourceName}",
          "description": "Uploads media for indexing.\n\nThe upload endpoint supports direct and resumable upload protocols and\nis intended for large items that can not be\n[inlined during index requests](https://developers.google.com/cloud-search/docs/reference/rest/v1/indexing.datasources.items#itemcontent).\nTo index large content:\n\n1. Call\n   indexing.datasources.items.upload\n   with the resource name to begin an upload session and retrieve the\n   UploadItemRef.\n1. Call media.upload t[...]",
          "supportsMediaUpload": true,
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.indexing"
          ],
          "id": "cloudsearch.media.upload"
        }
      }
    },
    "stats": {
      "methods": {
        "getUser": {
          "path": "v1/stats/user",
          "id": "cloudsearch.stats.getUser",
          "description": "Get the users statistics for customer",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "flatPath": "v1/stats/user"
        },
        "getIndex": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "flatPath": "v1/stats/index",
          "id": "cloudsearch.stats.getIndex",
          "path": "v1/stats/index",
          "description": "Gets indexed item statistics aggreggated across all data sources. This\nAPI only returns statistics for previous dates; it doesn't return\nstatistics for the current day.",
          "httpMethod": "GET"
        },
        "getQuery": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "flatPath": "v1/stats/query",
          "path": "v1/stats/query",
          "id": "cloudsearch.stats.getQuery",
          "description": "Get the query statistics for customer",
          "httpMethod": "GET"
        },
        "getSession": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "flatPath": "v1/stats/session",
          "id": "cloudsearch.stats.getSession",
          "path": "v1/stats/session",
          "description": "Get the # of search sessions for the customer"
        }
      },
      "resources": {
        "index": {
          "resources": {
            "datasources": {
              "methods": {
                "get": {
                  "description": "Gets indexed item statistics for a single data source.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "flatPath": "v1/stats/index/datasources/{datasourcesId}",
                  "id": "cloudsearch.stats.index.datasources.get",
                  "path": "v1/stats/index/{+name}"
                }
              }
            }
          }
        },
        "session": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "flatPath": "v1/stats/session/searchapplications/{searchapplicationsId}",
                  "path": "v1/stats/session/{+name}",
                  "id": "cloudsearch.stats.session.searchapplications.get",
                  "description": "Get the # of search sessions for the search application"
                }
              }
            }
          }
        },
        "user": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "flatPath": "v1/stats/user/searchapplications/{searchapplicationsId}",
                  "path": "v1/stats/user/{+name}",
                  "id": "cloudsearch.stats.user.searchapplications.get",
                  "description": "Get the users statistics for search application"
                }
              }
            }
          }
        },
        "query": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "flatPath": "v1/stats/query/searchapplications/{searchapplicationsId}",
                  "path": "v1/stats/query/{+name}",
                  "id": "cloudsearch.stats.query.searchapplications.get",
                  "description": "Get the query statistics for search application"
                }
              }
            }
          }
        }
      }
    },
    "settings": {
      "resources": {
        "datasources": {
          "methods": {
            "delete": {
              "description": "Deletes a datasource.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "path": "v1/settings/{+name}",
              "id": "cloudsearch.settings.datasources.delete"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "path": "v1/settings/{+name}",
              "id": "cloudsearch.settings.datasources.get",
              "description": "Gets a datasource."
            },
            "list": {
              "description": "Lists datasources.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/settings/datasources",
              "path": "v1/settings/datasources",
              "id": "cloudsearch.settings.datasources.list"
            },
            "update": {
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "path": "v1/settings/{+name}",
              "id": "cloudsearch.settings.datasources.update",
              "description": "Updates a datasource.",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            },
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/settings/datasources",
              "path": "v1/settings/datasources",
              "id": "cloudsearch.settings.datasources.create",
              "description": "Creates a datasource."
            }
          }
        },
        "searchapplications": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "flatPath": "v1/settings/searchapplications",
              "id": "cloudsearch.settings.searchapplications.create",
              "path": "v1/settings/searchapplications",
              "description": "Creates a search application."
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "path": "v1/settings/{+name}",
              "id": "cloudsearch.settings.searchapplications.get",
              "description": "Gets the specified search application."
            },
            "update": {
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "id": "cloudsearch.settings.searchapplications.update",
              "path": "v1/settings/{+name}",
              "description": "Updates a search application."
            },
            "delete": {
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "id": "cloudsearch.settings.searchapplications.delete",
              "path": "v1/settings/{+name}",
              "description": "Deletes a search application.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ]
            },
            "reset": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}:reset",
              "id": "cloudsearch.settings.searchapplications.reset",
              "path": "v1/settings/{+name}:reset",
              "description": "Resets a search application to default settings. This will return an empty\nresponse."
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "flatPath": "v1/settings/searchapplications",
              "id": "cloudsearch.settings.searchapplications.list",
              "path": "v1/settings/searchapplications",
              "description": "Lists all search applications.",
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "indexing": {
      "resources": {
        "datasources": {
          "methods": {
            "getSchema": {
              "path": "v1/indexing/{+name}/schema",
              "id": "cloudsearch.indexing.datasources.getSchema",
              "description": "Gets the schema of a data source.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema"
            },
            "updateSchema": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "path": "v1/indexing/{+name}/schema",
              "id": "cloudsearch.indexing.datasources.updateSchema",
              "description": "Updates the schema of a data source.",
              "httpMethod": "PUT"
            },
            "deleteSchema": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "path": "v1/indexing/{+name}/schema",
              "id": "cloudsearch.indexing.datasources.deleteSchema",
              "description": "Deletes the schema of a data source."
            }
          },
          "resources": {
            "items": {
              "methods": {
                "upload": {
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:upload",
                  "id": "cloudsearch.indexing.datasources.items.upload",
                  "path": "v1/indexing/{+name}:upload",
                  "description": "Creates an upload session for uploading item content. For items smaller\nthan 100 KB, it's easier to embed the content\ninline within\nan index request.\n\nThis API requires an admin or service account to execute. The service\naccount used is the one whitelisted in the corresponding data source.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "deleteQueueItems": {
                  "description": "Deletes all items in a queue. This method is useful for deleting stale\nitems.\n\nThis API requires an admin or service account to execute. The service\naccount used is the one whitelisted in the corresponding data source.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:deleteQueueItems",
                  "id": "cloudsearch.indexing.datasources.items.deleteQueueItems",
                  "path": "v1/indexing/{+name}/items:deleteQueueItems"
                },
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                  "id": "cloudsearch.indexing.datasources.items.get",
                  "path": "v1/indexing/{+name}",
                  "description": "Gets Item resource by item name.\n\nThis API requires an admin or service account to execute.  The service\naccount used is the one whitelisted in the corresponding data source."
                },
                "unreserve": {
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:unreserve",
                  "path": "v1/indexing/{+name}/items:unreserve",
                  "id": "cloudsearch.indexing.datasources.items.unreserve",
                  "description": "Unreserves all items from a queue, making them all eligible to be\npolled.  This method is useful for resetting the indexing queue\nafter a connector has been restarted.\n\nThis API requires an admin or service account to execute. The service\naccount used is the one whitelisted in the corresponding data source.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "index": {
                  "path": "v1/indexing/{+name}:index",
                  "id": "cloudsearch.indexing.datasources.items.index",
                  "description": "Updates Item ACL, metadata, and\ncontent. It will insert the Item if it\ndoes not exist.\nThis method does not support partial updates.  Fields with no provided\nvalues are cleared out in the Cloud Search index.\n\nThis API requires an admin or service account to execute. The service\naccount used is the one whitelisted in the corresponding data source.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:index"
                },
                "poll": {
                  "description": "Polls for unreserved items from the indexing queue and marks a\nset as reserved, starting with items that have\nthe oldest timestamp from the highest priority\nItemStatus.\nThe priority order is as follows: \u003cbr /\u003e\nERROR\n\u003cbr /\u003e\nMODIFIED\n\u003cbr /\u003e\nNEW_ITEM\n\u003cbr /\u003e\nACCEPTED\n\u003cbr /\u003e\nReserving items ensures that polling from other threads\ncannot create overlapping sets.\n\nAfter handling the reserved items, the c[...]",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:poll",
                  "id": "cloudsearch.indexing.datasources.items.poll",
                  "path": "v1/indexing/{+name}/items:poll"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                  "id": "cloudsearch.indexing.datasources.items.delete",
                  "path": "v1/indexing/{+name}",
                  "description": "Deletes Item resource for the\nspecified resource name. This API requires an admin or service account\nto execute. The service account used is the one whitelisted in the\ncorresponding data source."
                },
                "push": {
                  "id": "cloudsearch.indexing.datasources.items.push",
                  "path": "v1/indexing/{+name}:push",
                  "description": "Pushes an item onto a queue for later polling and updating.\n\nThis API requires an admin or service account to execute. The service\naccount used is the one whitelisted in the corresponding data source.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:push"
                },
                "list": {
                  "path": "v1/indexing/{+name}/items",
                  "id": "cloudsearch.indexing.datasources.items.list",
                  "description": "Lists all or a subset of Item resources.\n\nThis API requires an admin or service account to execute. The service\naccount used is the one whitelisted in the corresponding data source.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items"
                }
              }
            }
          }
        }
      }
    },
    "query": {
      "methods": {
        "search": {
          "description": "The Cloud Search Query API provides the search method, which returns\nthe most relevant results from a user query.  The results can come from\nG Suite Apps, such as Gmail or Google Drive, or they can come from data\nthat you have indexed from a third party.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ],
          "flatPath": "v1/query/search",
          "path": "v1/query/search",
          "id": "cloudsearch.query.search"
        },
        "suggest": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ],
          "flatPath": "v1/query/suggest",
          "path": "v1/query/suggest",
          "id": "cloudsearch.query.suggest",
          "description": "Provides suggestions for autocompleting the query."
        }
      },
      "resources": {
        "sources": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.query"
              ],
              "flatPath": "v1/query/sources",
              "path": "v1/query/sources",
              "id": "cloudsearch.query.sources.list",
              "description": "Returns list of sources that user can use for Search and Suggest APIs.",
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "operations": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.debug",
            "https://www.googleapis.com/auth/cloud_search.indexing",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing",
            "https://www.googleapis.com/auth/cloud_search.settings.query"
          ],
          "flatPath": "v1/operations/{operationsId}",
          "path": "v1/{+name}",
          "id": "cloudsearch.operations.get",
          "description": "Gets the latest state of a long-running operation.  Clients can use this\nmethod to poll the operation result at intervals as recommended by the API\nservice."
        }
      }
    },
    "debug": {
      "resources": {
        "datasources": {
          "resources": {
            "items": {
              "methods": {
                "searchByViewUrl": {
                  "flatPath": "v1/debug/datasources/{datasourcesId}/items:searchByViewUrl",
                  "path": "v1/debug/{+name}/items:searchByViewUrl",
                  "id": "cloudsearch.debug.datasources.items.searchByViewUrl",
                  "description": "Fetches the item whose viewUrl exactly matches that of the URL provided\nin the request.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ]
                },
                "checkAccess": {
                  "description": "Checks whether an item is accessible by specified principal.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}:checkAccess",
                  "path": "v1/debug/{+name}:checkAccess",
                  "id": "cloudsearch.debug.datasources.items.checkAccess"
                }
              },
              "resources": {
                "unmappedids": {
                  "methods": {
                    "list": {
                      "description": "List all unmapped identities for a specific item.",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud_search",
                        "https://www.googleapis.com/auth/cloud_search.debug"
                      ],
                      "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}/unmappedids",
                      "id": "cloudsearch.debug.datasources.items.unmappedids.list",
                      "path": "v1/debug/{+parent}/unmappedids"
                    }
                  }
                }
              }
            }
          }
        },
        "identitysources": {
          "resources": {
            "unmappedids": {
              "methods": {
                "list": {
                  "flatPath": "v1/debug/identitysources/{identitysourcesId}/unmappedids",
                  "id": "cloudsearch.debug.identitysources.unmappedids.list",
                  "path": "v1/debug/{+parent}/unmappedids",
                  "description": "Lists unmapped user identities for an identity source.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ]
                }
              }
            },
            "items": {
              "methods": {
                "listForunmappedidentity": {
                  "flatPath": "v1/debug/identitysources/{identitysourcesId}/items:forunmappedidentity",
                  "path": "v1/debug/{+parent}/items:forunmappedidentity",
                  "id": "cloudsearch.debug.identitysources.items.listForunmappedidentity",
                  "description": "Lists names of items associated with an unmapped identity.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ]
                }
              }
            }
          }
        }
      }
    }
  }
}
