{
  "basePath": "",
  "id": "cloudsearch:v1",
  "documentationLink": "https://gsuite.google.com/products/cloud-search/",
  "revision": "20190522",
  "discoveryVersion": "v1",
  "version_module": true,
  "schemas": {
    "DriveFollowUpRestrict": {
      "description": "Drive follow-up search restricts (e.g. \"followup:suggestions\").",
      "type": "object",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "FOLLOWUP_SUGGESTIONS",
            "FOLLOWUP_ACTION_ITEMS"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            ""
          ]
        }
      },
      "id": "DriveFollowUpRestrict"
    },
    "GmailActionRestrict": {
      "description": "Gmail Action restricts (i.e. read/replied/snoozed).",
      "type": "object",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "UNREAD",
            "READ",
            "REPLIED_TO",
            "MUTED"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "is:unread",
            "is:read",
            "label:^io_re",
            "label:mute"
          ]
        }
      },
      "id": "GmailActionRestrict"
    },
    "DoublePropertyOptions": {
      "description": "Options for double properties.",
      "type": "object",
      "properties": {
        "operatorOptions": {
          "$ref": "DoubleOperatorOptions",
          "description": "If set, describes how the double should be used as a search operator."
        }
      },
      "id": "DoublePropertyOptions"
    },
    "IntegerValues": {
      "description": "List of integer values.",
      "type": "object",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "format": "int64",
            "type": "string"
          }
        }
      },
      "id": "IntegerValues"
    },
    "BooleanPropertyOptions": {
      "type": "object",
      "properties": {
        "operatorOptions": {
          "$ref": "BooleanOperatorOptions",
          "description": "If set, describes how the boolean should be used as a search operator."
        }
      },
      "id": "BooleanPropertyOptions",
      "description": "Options for boolean properties."
    },
    "SearchRequest": {
      "description": "The search API request.",
      "type": "object",
      "properties": {
        "queryInterpretationOptions": {
          "description": "Options to interpret the user query.",
          "$ref": "QueryInterpretationOptions"
        },
        "requestOptions": {
          "$ref": "RequestOptions",
          "description": "Request options, such as the search application and user timezone."
        },
        "dataSourceRestrictions": {
          "description": "The sources to use for querying. If not specified, all data sources\nfrom the current search application are used.",
          "type": "array",
          "items": {
            "$ref": "DataSourceRestriction"
          }
        },
        "sortOptions": {
          "$ref": "SortOptions",
          "description": "The options for sorting the search results"
        },
        "facetOptions": {
          "type": "array",
          "items": {
            "$ref": "FacetOptions"
          }
        },
        "pageSize": {
          "description": "Maximum number of search results to return in one page.\nValid values are between 1 and 100, inclusive.\nDefault value is 10.",
          "format": "int32",
          "type": "integer"
        },
        "query": {
          "description": "The raw query string.\nSee supported search operators in the [Cloud search\nCheat\nSheet](https://gsuite.google.com/learning-center/products/cloudsearch/cheat-sheet/)",
          "type": "string"
        },
        "start": {
          "description": "Starting index of the results.",
          "format": "int32",
          "type": "integer"
        }
      },
      "id": "SearchRequest"
    },
    "CompositeFilter": {
      "properties": {
        "subFilters": {
          "description": "Sub filters.",
          "type": "array",
          "items": {
            "$ref": "Filter"
          }
        },
        "logicOperator": {
          "enumDescriptions": [
            "Logical operators, which can only be applied to sub filters.",
            "",
            "NOT can only be applied on a single sub filter."
          ],
          "enum": [
            "AND",
            "OR",
            "NOT"
          ],
          "description": "The logic operator of the sub filter.",
          "type": "string"
        }
      },
      "id": "CompositeFilter",
      "type": "object"
    },
    "EnumValuePair": {
      "description": "The enumeration value pair defines two things: a required string value and\nan optional integer value. The string value defines the necessary query\nterm required to retrieve that item, such as *p0* for a priority item.\nThe integer value determines the ranking of that string value relative\nto other enumerated values for the same property. For example, you might\nassociate *p0* with *0* and define another enum pair such as *p1* and *1*.\nYou must use the integer value in c[...]",
      "type": "object",
      "properties": {
        "integerValue": {
          "description": "The integer value of the EnumValuePair which must be non-negative.\nOptional.",
          "format": "int32",
          "type": "integer"
        },
        "stringValue": {
          "description": "The string value of the EnumValuePair.\nThe maximum length is 32 characters.",
          "type": "string"
        }
      },
      "id": "EnumValuePair"
    },
    "SearchItemsByViewUrlResponse": {
      "type": "object",
      "properties": {
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no\nmore results in the list.",
          "type": "string"
        },
        "items": {
          "type": "array",
          "items": {
            "$ref": "Item"
          }
        }
      },
      "id": "SearchItemsByViewUrlResponse"
    },
    "ObjectOptions": {
      "description": "The options for an object.",
      "type": "object",
      "properties": {
        "displayOptions": {
          "$ref": "ObjectDisplayOptions",
          "description": "Options that determine how the object is displayed in the Cloud Search\nresults page."
        },
        "freshnessOptions": {
          "$ref": "FreshnessOptions",
          "description": "The freshness options for an object."
        }
      },
      "id": "ObjectOptions"
    },
    "DeleteQueueItemsRequest": {
      "id": "DeleteQueueItemsRequest",
      "type": "object",
      "properties": {
        "connectorName": {
          "description": "Name of connector making this call.\n\u003cbr /\u003eFormat: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "queue": {
          "type": "string",
          "description": "Name of a queue to delete items from."
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        }
      }
    },
    "DriveTimeSpanRestrict": {
      "type": "object",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "TODAY",
            "YESTERDAY",
            "LAST_7_DAYS",
            "LAST_30_DAYS",
            "LAST_90_DAYS"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "Not Enabled",
            "Not Enabled"
          ]
        }
      },
      "id": "DriveTimeSpanRestrict",
      "description": "The time span search restrict (e.g. \"after:2017-09-11 before:2017-09-12\")."
    },
    "FacetOptions": {
      "description": "Specifies operators to return facet results for. There will be one\nFacetResult for every source_name/object_type/operator_name combination.",
      "type": "object",
      "properties": {
        "objectType": {
          "description": "If object_type is set, only those objects of that type will be used to\ncompute facets. If empty, then all objects will be used to compute facets.",
          "type": "string"
        },
        "sourceName": {
          "description": "Source name to facet on. Format: datasources/{source_id}\nIf empty, all data sources will be used.",
          "type": "string"
        },
        "numFacetBuckets": {
          "description": "Maximum number of facet buckets that should be returned for this facet.\nDefaults to 10.\nMaximum value is 100.",
          "format": "int32",
          "type": "integer"
        },
        "operatorName": {
          "description": "Name of the operator chosen for faceting. @see\ncloudsearch.SchemaPropertyOptions",
          "type": "string"
        }
      },
      "id": "FacetOptions"
    },
    "Person": {
      "description": "Object to represent a person.",
      "type": "object",
      "properties": {
        "obfuscatedId": {
          "description": "Obfuscated ID of a person.",
          "type": "string"
        },
        "photos": {
          "description": "A person's read-only photo. A picture shown next to the person's name to\nhelp others recognize the person in search results.",
          "type": "array",
          "items": {
            "$ref": "Photo"
          }
        },
        "personNames": {
          "description": "The person's name",
          "type": "array",
          "items": {
            "$ref": "Name"
          }
        },
        "emailAddresses": {
          "description": "The person's email addresses",
          "type": "array",
          "items": {
            "$ref": "EmailAddress"
          }
        },
        "name": {
          "description": "The resource name of the person to provide information about.\nSee \u003ca href=\"https://developers.google.com/people/api/rest/v1/people/get\"\u003e\nPeople.get\u003c/a\u003e from Google People API.",
          "type": "string"
        }
      },
      "id": "Person"
    },
    "GetDataSourceIndexStatsResponse": {
      "type": "object",
      "properties": {
        "stats": {
          "description": "Summary of indexed item counts, one for each day in the requested range.",
          "type": "array",
          "items": {
            "$ref": "DataSourceIndexStats"
          }
        }
      },
      "id": "GetDataSourceIndexStatsResponse"
    },
    "StructuredResult": {
      "type": "object",
      "properties": {
        "person": {
          "description": "Representation of a person",
          "$ref": "Person"
        }
      },
      "id": "StructuredResult",
      "description": "Structured results that are returned as part of search request."
    },
    "ResultDisplayMetadata": {
      "type": "object",
      "properties": {
        "objectTypeLabel": {
          "description": "The display label for the object.",
          "type": "string"
        },
        "metalines": {
          "description": "The metalines content to be displayed with the result.",
          "type": "array",
          "items": {
            "$ref": "ResultDisplayLine"
          }
        }
      },
      "id": "ResultDisplayMetadata"
    },
    "SpellResult": {
      "type": "object",
      "properties": {
        "suggestedQuery": {
          "description": "The suggested spelling of the query.",
          "type": "string"
        }
      },
      "id": "SpellResult"
    },
    "SearchApplication": {
      "description": "SearchApplication",
      "type": "object",
      "properties": {
        "dataSourceRestrictions": {
          "description": "Retrictions applied to the configurations.\nThe maximum number of elements is 10.",
          "type": "array",
          "items": {
            "$ref": "DataSourceRestriction"
          }
        },
        "sourceConfig": {
          "type": "array",
          "items": {
            "$ref": "SourceConfig"
          },
          "description": "Configuration for a sources specified in data_source_restrictions."
        },
        "defaultSortOptions": {
          "$ref": "SortOptions",
          "description": "The default options for sorting the search results"
        },
        "displayName": {
          "description": "Display name of the Search Application.\nThe maximum length is 300 characters.",
          "type": "string"
        },
        "defaultFacetOptions": {
          "description": "The default fields for returning facet results.\nThe sources specified here also have been included in\ndata_source_restrictions\nabove.",
          "type": "array",
          "items": {
            "$ref": "FacetOptions"
          }
        },
        "scoringConfig": {
          "description": "Configuration for ranking results.",
          "$ref": "ScoringConfig"
        },
        "name": {
          "description": "Name of the Search Application.\n\u003cbr /\u003eFormat: searchapplications/{application_id}.",
          "type": "string"
        },
        "operationIds": {
          "description": "IDs of the Long Running Operations (LROs) currently running for this\nschema. Output only field.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "id": "SearchApplication"
    },
    "DoubleOperatorOptions": {
      "type": "object",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to use the\ndouble property in sorting or as a facet.\nThe operator name can only contain lowercase letters (a-z).\nThe maximum length is 32 characters.",
          "type": "string"
        }
      },
      "id": "DoubleOperatorOptions",
      "description": "Used to provide a search operator for double properties. This is\noptional. Search operators let users restrict the query to specific fields\nrelevant to the type of item being searched."
    },
    "QuerySuggestion": {
      "id": "QuerySuggestion",
      "description": "This field does not contain anything as of now and is just used as an\nindicator that the suggest result was a phrase completion.",
      "type": "object",
      "properties": {}
    },
    "PollItemsRequest": {
      "type": "object",
      "properties": {
        "connectorName": {
          "description": "Name of connector making this call.\n\u003cbr /\u003eFormat: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "queue": {
          "type": "string",
          "description": "Queue name to fetch items from.  If unspecified, PollItems will\nfetch from 'default' queue.\nThe maximum length is 100 characters."
        },
        "limit": {
          "description": "Maximum number of items to return.\n\u003cbr /\u003eThe maximum and the default value is 1000",
          "format": "int32",
          "type": "integer"
        },
        "statusCodes": {
          "enumDescriptions": [
            "Input-only value.  Used with\nItems.list\nto list all items in the queue, regardless of status.",
            "Error encountered by Cloud Search while processing this item.\nDetails of the error are in\nrepositoryError.",
            "Item has been modified in the repository, and is out of date with\nthe version previously accepted into Cloud Search.",
            "Item is known to exist in the repository, but is not yet accepted by\nCloud Search.\nAn item can be in this state when\nItems.push\nhas been called for\nan item of this name that did not exist previously.",
            "API has accepted the up-to-date data of this item."
          ],
          "description": "Limit the items polled to the ones with these statuses.",
          "type": "array",
          "items": {
            "enum": [
              "CODE_UNSPECIFIED",
              "ERROR",
              "MODIFIED",
              "NEW_ITEM",
              "ACCEPTED"
            ],
            "type": "string"
          }
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        }
      },
      "id": "PollItemsRequest"
    },
    "EnumOperatorOptions": {
      "id": "EnumOperatorOptions",
      "description": "Used to provide a search operator for enum properties. This is\noptional. Search operators let users restrict the query to specific fields\nrelevant to the type of item being searched. For example, if you provide no\noperator for a *priority* enum property with possible values *p0* and *p1*,\na query that contains the term *p0* will return items that have *p0* as the\nvalue of the *priority* property, as well as any items that contain the\nstring *p0* in other fields. If yo[...]",
      "type": "object",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\nenum property. For example, if operatorName is *priority* and the\nproperty's name is *priorityVal*, then queries like\n*priority:&lt;value&gt;* will show results only where the value of the\nproperty named *priorityVal* matches *&lt;value&gt;*. By contrast, a\nsearch that uses the same *&lt;value&gt;* without an operator will return\nall items where *&lt;value&gt;* matches the value of any Strin[...]",
          "type": "string"
        }
      }
    },
    "SearchResponse": {
      "id": "SearchResponse",
      "description": "The search API response.",
      "type": "object",
      "properties": {
        "resultCountEstimate": {
          "description": "The estimated result count for this query.",
          "format": "int64",
          "type": "string"
        },
        "debugInfo": {
          "$ref": "ResponseDebugInfo",
          "description": "Debugging information about the response."
        },
        "resultCounts": {
          "$ref": "ResultCounts",
          "description": "Expanded result count information."
        },
        "facetResults": {
          "description": "Repeated facet results.",
          "type": "array",
          "items": {
            "$ref": "FacetResult"
          }
        },
        "spellResults": {
          "description": "Suggested spelling for the query.",
          "type": "array",
          "items": {
            "$ref": "SpellResult"
          }
        },
        "structuredResults": {
          "description": "Structured results for the user query. These results are not counted\nagainst the page_size.",
          "type": "array",
          "items": {
            "$ref": "StructuredResult"
          }
        },
        "resultCountExact": {
          "description": "The exact result count for this query.",
          "format": "int64",
          "type": "string"
        },
        "errorInfo": {
          "$ref": "ErrorInfo",
          "description": "Error information about the response."
        },
        "hasMoreResults": {
          "description": "Whether there are more search results matching the query.",
          "type": "boolean"
        },
        "queryInterpretation": {
          "description": "Query interpretation result for user query. Empty if query interpretation\nis disabled.",
          "$ref": "QueryInterpretation"
        },
        "results": {
          "type": "array",
          "items": {
            "$ref": "SearchResult"
          },
          "description": "Results from a search query."
        }
      }
    },
    "PropertyDisplayOptions": {
      "id": "PropertyDisplayOptions",
      "description": "The display options for a property.",
      "type": "object",
      "properties": {
        "displayLabel": {
          "description": "The user friendly label for the property that will be used if the property\nis specified to be displayed in ObjectDisplayOptions. If given, the display\nlabel will be shown in front of the property values when the property is\npart of the object display options. For example, if the property value is\n'1', the value by itself may not be useful context for the user. If the\ndisplay name given was 'priority', then the user will see 'priority : 1' in\nthe search results whi[...]",
          "type": "string"
        }
      }
    },
    "ObjectDefinition": {
      "id": "ObjectDefinition",
      "description": "The definition for an object within a data source.",
      "type": "object",
      "properties": {
        "propertyDefinitions": {
          "description": "The property definitions for the object.\nThe maximum number of elements is 1000.",
          "type": "array",
          "items": {
            "$ref": "PropertyDefinition"
          }
        },
        "name": {
          "description": "Name for the object, which then defines its type. Item indexing requests\nshould set the\nobjectType field\nequal to this value. For example, if *name* is *Document*, then indexing\nrequests for items of type Document should set\nobjectType equal to\n*Document*. Each object definition must be uniquely named within a schema.\nThe name must start with a letter and can only contain letters (A-Z, a-z)\nor numbers (0-9).\nThe maximum length is 256 characters.",
          "type": "string"
        },
        "options": {
          "$ref": "ObjectOptions",
          "description": "The optional object-specific options."
        }
      }
    },
    "FreshnessOptions": {
      "properties": {
        "freshnessDuration": {
          "description": "The duration after which an object should be considered\nstale. The default value is 180 days (in seconds).",
          "format": "google-duration",
          "type": "string"
        },
        "freshnessProperty": {
          "description": "This property indicates the freshness level of the object in the index.\nIf set, this property must be a top-level property within the\nproperty definitions\nand it must be a\ntimestamp type\nor\ndate type.\nOtherwise, the Indexing API uses\nupdateTime\nas the freshness indicator.\nThe maximum length is 256 characters.\n\nWhen a property is used to calculate fresheness, the value defaults\nto 2 years from the current time.",
          "type": "string"
        }
      },
      "id": "FreshnessOptions",
      "description": "Indicates which freshness property to use when adjusting search ranking for\nan item. Fresher, more recent dates indicate higher quality. Use the\nfreshness option property that best works with your data. For fileshare\ndocuments, last modified time is most relevant. For calendar event data,\nthe time when the event occurs is a more relevant freshness indicator. In\nthis way, calendar events that occur closer to the time of the search query\nare considered higher quality an[...]",
      "type": "object"
    },
    "UploadItemRef": {
      "id": "UploadItemRef",
      "description": "Represents an upload session reference.\nThis reference is created via upload\nmethod.\nUpdating of item content may refer to this uploaded content via\ncontentDataRef.",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the content reference.\nThe maximum length is 2048 characters.",
          "type": "string"
        }
      }
    },
    "EmailAddress": {
      "type": "object",
      "properties": {
        "emailAddress": {
          "description": "The email address.",
          "type": "string"
        }
      },
      "id": "EmailAddress",
      "description": "A person's email address."
    },
    "HtmlOperatorOptions": {
      "description": "Used to provide a search operator for html properties. This is optional.\nSearch operators let users restrict the query to specific fields relevant\nto the type of item being searched.",
      "type": "object",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\nhtml property. For example, if operatorName is *subject* and the\nproperty's name is *subjectLine*, then queries like\n*subject:&lt;value&gt;* will show results only where the value of the\nproperty named *subjectLine* matches *&lt;value&gt;*. By contrast, a\nsearch that uses the same *&lt;value&gt;* without an operator will return\nall items where *&lt;value&gt;* matches the value of any\nhtml p[...]",
          "type": "string"
        }
      },
      "id": "HtmlOperatorOptions"
    },
    "GmailTimeRestrict": {
      "description": "Gmail Time restricts (i.e. received today, this week).",
      "type": "object",
      "properties": {
        "type": {
          "enumDescriptions": [
            "",
            "newer_than:7d",
            "older_than:1y",
            "newer_than:1d",
            "newer_than:2d older_than:1d",
            "newer_than:30d",
            "This will read as something like \"From November\" and will have operator\nbefore:X after:Y",
            "older_than:1d",
            "older_than:2d",
            "older_than:7d",
            "older_than:30d"
          ],
          "enum": [
            "UNSPECIFIED",
            "FROM_THIS_WEEK",
            "OLDER_THAN_ONE_YEAR",
            "FROM_TODAY",
            "FROM_YESTERDAY",
            "FROM_THIS_MONTH",
            "FROM_CERTAIN_MONTH",
            "OLDER_THAN_TODAY",
            "OLDER_THAN_YESTERDAY",
            "OLDER_THAN_A_WEEK",
            "OLDER_THAN_A_MONTH"
          ],
          "type": "string"
        }
      },
      "id": "GmailTimeRestrict"
    },
    "QueryItem": {
      "description": "Information relevant only to a query entry.",
      "type": "object",
      "properties": {
        "isSynthetic": {
          "description": "True if the text was generated by means other than a previous user search.",
          "type": "boolean"
        }
      },
      "id": "QueryItem"
    },
    "ItemContent": {
      "id": "ItemContent",
      "description": "Content of an item to be indexed and surfaced by Cloud Search.",
      "type": "object",
      "properties": {
        "contentFormat": {
          "type": "string",
          "enumDescriptions": [
            "Invalid value.",
            "contentFormat is HTML.",
            "contentFormat is free text.",
            "contentFormat is raw bytes."
          ],
          "enum": [
            "UNSPECIFIED",
            "HTML",
            "TEXT",
            "RAW"
          ]
        },
        "hash": {
          "description": "Hashing info calculated and provided by the API client for content.\nCan be used with the items.push method to calculate modified state.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "inlineContent": {
          "description": "Content that is supplied inlined within the update method.\nThe maximum length is 102400 bytes (100 KiB).",
          "format": "byte",
          "type": "string"
        },
        "contentDataRef": {
          "description": "Upload reference ID of a previously uploaded content via write method.",
          "$ref": "UploadItemRef"
        }
      }
    },
    "CustomerIndexStats": {
      "description": "Aggregation of items by status code as of the specified date.",
      "type": "object",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "Date for which statistics were calculated."
        },
        "itemCountByStatus": {
          "description": "Number of items aggregrated by status code.",
          "type": "array",
          "items": {
            "$ref": "ItemCountByStatus"
          }
        }
      },
      "id": "CustomerIndexStats"
    },
    "SourceCrowdingConfig": {
      "id": "SourceCrowdingConfig",
      "description": "Set search results crowding limits. Crowding is a situation in which\nmultiple results from the same source or host \"crowd out\" other results,\ndiminishing the quality of search for users. To foster better search quality\nand source diversity in search results, you can set a condition to reduce\nrepetitive results by source.",
      "type": "object",
      "properties": {
        "numResults": {
          "description": "Maximum number of results allowed from a source.\nNo limits will be set on results if this value is less than or equal to 0.",
          "format": "int32",
          "type": "integer"
        },
        "field": {
          "description": "Use a field to control results crowding. For example, if you want to\ncontrol overly similar results from Gmail topics, use `thread_id`.\nFor similar pages from Google Sites, you can use `webspace_id`.\nWhen matching query results contain the same field value in\n`GenericMetadata`, crowding limits are set on those records.",
          "type": "string"
        },
        "source": {
          "description": "Control results by content source. This option limits the total number\nof results from a given source and ignores field-based crowding control.",
          "type": "boolean"
        },
        "numSuggestions": {
          "type": "integer",
          "description": "Maximum number of suggestions allowed from a source.\nNo limits will be set on results if this value is less than or equal to 0.",
          "format": "int32"
        }
      }
    },
    "PushItem": {
      "description": "Represents an item to be pushed to the indexing queue.",
      "type": "object",
      "properties": {
        "contentHash": {
          "description": "Content hash of the item according to the repository. If specified, this is\nused to determine how to modify this\nitem's status. Setting this field and the\ntype field results in argument\nerror.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "metadataHash": {
          "description": "Metadata hash of the item according to the repository. If specified, this\nis used to determine how to modify this\nitem's status. Setting this field and the\ntype field results in argument\nerror.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "payload": {
          "description": "Provides additional document state information for the connector,\nsuch as an alternate repository ID and other metadata.\nThe maximum length is 8192 bytes.",
          "format": "byte",
          "type": "string"
        },
        "repositoryError": {
          "$ref": "RepositoryError",
          "description": "Populate this field to store Connector or repository error details.\nThis information is displayed in the Admin Console.\nThis field may only be populated when the\nType is\nREPOSITORY_ERROR."
        },
        "type": {
          "enum": [
            "UNSPECIFIED",
            "MODIFIED",
            "NOT_MODIFIED",
            "REPOSITORY_ERROR",
            "REQUEUE"
          ],
          "description": "The type of the push operation that defines the push behavior.",
          "type": "string",
          "enumDescriptions": [
            "Default UNSPECIFIED.  Specifies that the push operation should not modify\nItemStatus",
            "Indicates that the repository document has been modified or updated since\nthe previous\nupdate\ncall. This changes status to\nMODIFIED state for\nan existing item. If this is called on a non existing item, the status is\nchanged to\nNEW_ITEM.",
            "Item in the repository has not been modified since the last update\ncall.  This push operation will set status to\nACCEPTED state.",
            "Connector is facing a repository error regarding this item.  Change\nstatus to\nREPOSITORY_ERROR\nstate. Item is unreserved and rescheduled at a future time determined by\nexponential backoff.",
            "Call push with REQUEUE only for items that have been reserved.\nThis action unreserves the item and resets its available time to the\nwall clock time."
          ]
        },
        "structuredDataHash": {
          "type": "string",
          "description": "Structured data hash of the item according to the repository. If specified,\nthis is used to determine how to modify this item's status. Setting this\nfield and the type field\nresults in argument error.\nThe maximum length is 2048 characters."
        },
        "queue": {
          "description": "Queue to which this item belongs to.  The \u003ccode\u003edefault\u003c/code\u003e queue is\nchosen if this field is not specified. The maximum length is\n512 characters.",
          "type": "string"
        }
      },
      "id": "PushItem"
    },
    "Date": {
      "description": "Represents a whole calendar date, for example a date of birth. The time of day and time zone are either specified elsewhere or are not significant. The date is relative to the [Proleptic Gregorian Calendar](https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar). The date must be a valid calendar date between the year 1 and 9999.",
      "type": "object",
      "properties": {
        "year": {
          "description": "Year of date. Must be from 1 to 9999.",
          "format": "int32",
          "type": "integer"
        },
        "day": {
          "description": "Day of month. Must be from 1 to 31 and valid for the year and month.",
          "format": "int32",
          "type": "integer"
        },
        "month": {
          "type": "integer",
          "description": "Month of date. Must be from 1 to 12.",
          "format": "int32"
        }
      },
      "id": "Date"
    },
    "CheckAccessResponse": {
      "type": "object",
      "properties": {
        "hasAccess": {
          "type": "boolean",
          "description": "Returns true if principal has access.  Returns false otherwise."
        }
      },
      "id": "CheckAccessResponse"
    },
    "ObjectDisplayOptions": {
      "description": "The display options for an object.",
      "type": "object",
      "properties": {
        "objectDisplayLabel": {
          "description": "The user friendly label to display in the search result to inidicate the\ntype of the item. This is OPTIONAL; if not given, an object label will not\nbe displayed on the context line of the search results. The maximum length\nis 32 characters.",
          "type": "string"
        },
        "metalines": {
          "description": "Defines the properties that will be displayed in the metalines of the\nsearch results. The property values will be displayed in the order given\nhere. If a property holds multiple values, all of the values will be\ndiplayed before the next properties. For this reason, it is a good practice\nto specify singular properties before repeated properties in this list. All\nof the properties must set\nis_returnable\nto true. The maximum number of metalines is 3.",
          "type": "array",
          "items": {
            "$ref": "Metaline"
          }
        }
      },
      "id": "ObjectDisplayOptions"
    },
    "ListSearchApplicationsResponse": {
      "type": "object",
      "properties": {
        "nextPageToken": {
          "type": "string",
          "description": "Token to retrieve the next page of results, or empty if there are no\nmore results in the list."
        },
        "searchApplications": {
          "type": "array",
          "items": {
            "$ref": "SearchApplication"
          }
        }
      },
      "id": "ListSearchApplicationsResponse"
    },
    "HtmlValues": {
      "description": "List of html values.",
      "type": "object",
      "properties": {
        "values": {
          "description": "The maximum allowable length for html values is 2048 characters.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "id": "HtmlValues"
    },
    "TimestampOperatorOptions": {
      "description": "Used to provide a search operator for timestamp properties. This is\noptional. Search operators let users restrict the query to specific fields\nrelevant to the type of item being searched.",
      "type": "object",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ntimestamp property. For example, if operatorName is *closedon* and the\nproperty's name is *closeDate*, then queries like\n*closedon:&lt;value&gt;* will show results only where the value of the\nproperty named *closeDate* matches *&lt;value&gt;*. By contrast, a\nsearch that uses the same *&lt;value&gt;* without an operator will return\nall items where *&lt;value&gt;* matches the value of any Stri[...]",
          "type": "string"
        },
        "greaterThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ntimestamp property using the greater-than operator. For example, if\ngreaterThanOperatorName is *closedafter* and the property's name is\n*closeDate*, then queries like *closedafter:&lt;value&gt;* will\nshow results only where the value of the property named *closeDate* is\nlater than *&lt;value&gt;*.\nThe operator name can only contain lowercase letters (a-z).\nThe maximum length is 32 character[...]",
          "type": "string"
        },
        "lessThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ntimestamp property using the less-than operator. For example, if\nlessThanOperatorName is *closedbefore* and the property's name is\n*closeDate*, then queries like *closedbefore:&lt;value&gt;* will\nshow results only where the value of the property named *closeDate* is\nearlier than *&lt;value&gt;*.\nThe operator name can only contain lowercase letters (a-z).\nThe maximum length is 32 characters.[...]",
          "type": "string"
        }
      },
      "id": "TimestampOperatorOptions"
    },
    "SearchResult": {
      "description": "Results containing indexed information for a document.",
      "type": "object",
      "properties": {
        "clusteredResults": {
          "type": "array",
          "items": {
            "$ref": "SearchResult"
          },
          "description": "If source is clustered, provide list of clustered results. There will only\nbe one level of clustered results. If current source is not enabled for\nclustering, this field will be empty."
        },
        "url": {
          "description": "The URL of the search result. The URL contains a Google redirect to the\nactual item. This URL is signed and shouldn't be changed.",
          "type": "string"
        },
        "metadata": {
          "$ref": "Metadata",
          "description": "Metadata of the search result."
        },
        "snippet": {
          "description": "The concatenation of all snippets (summaries) available for this result.",
          "$ref": "Snippet"
        },
        "title": {
          "description": "Title of the search result.",
          "type": "string"
        },
        "debugInfo": {
          "$ref": "ResultDebugInfo",
          "description": "Debugging information about this search result."
        }
      },
      "id": "SearchResult"
    },
    "DoubleValues": {
      "description": "List of double values.",
      "type": "object",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "format": "double",
            "type": "number"
          }
        }
      },
      "id": "DoubleValues"
    },
    "ErrorInfo": {
      "description": "Error information about the response.",
      "type": "object",
      "properties": {
        "errorMessages": {
          "type": "array",
          "items": {
            "$ref": "ErrorMessage"
          }
        }
      },
      "id": "ErrorInfo"
    },
    "ListDataSourceResponse": {
      "properties": {
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no\nmore results in the list.",
          "type": "string"
        },
        "sources": {
          "type": "array",
          "items": {
            "$ref": "DataSource"
          }
        }
      },
      "id": "ListDataSourceResponse",
      "type": "object"
    },
    "ObjectValues": {
      "description": "List of object values.",
      "type": "object",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "$ref": "StructuredDataObject"
          }
        }
      },
      "id": "ObjectValues"
    },
    "DateValues": {
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "$ref": "Date"
          }
        }
      },
      "id": "DateValues",
      "description": "List of date values.",
      "type": "object"
    },
    "Source": {
      "description": "Defines sources for the suggest/search APIs.",
      "type": "object",
      "properties": {
        "name": {
          "description": "Source name for content indexed by the\nIndexing API.",
          "type": "string"
        },
        "predefinedSource": {
          "enumDescriptions": [
            "",
            "Suggests queries issued by the user in the past. Only valid when used\nwith the suggest API. Ignored when used in the query API.",
            "Suggests people in the organization. Only valid when used\nwith the suggest API. Results in an error when used in the query API.",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "enum": [
            "NONE",
            "QUERY_HISTORY",
            "PERSON",
            "GOOGLE_DRIVE",
            "GOOGLE_GMAIL",
            "GOOGLE_SITES",
            "GOOGLE_GROUPS",
            "GOOGLE_CALENDAR",
            "GOOGLE_KEEP"
          ],
          "description": "Predefined content source for Google Apps.",
          "type": "string"
        }
      },
      "id": "Source"
    },
    "Metadata": {
      "properties": {
        "mimeType": {
          "type": "string",
          "description": "Mime type of the search result."
        },
        "objectType": {
          "description": "Object type of the search result.",
          "type": "string"
        },
        "displayOptions": {
          "description": "Options that specify how to display a structured data search result.",
          "$ref": "ResultDisplayMetadata"
        },
        "source": {
          "$ref": "Source",
          "description": "The named source for the result, such as Gmail."
        },
        "createTime": {
          "description": "The creation time for this document or object in the search result.",
          "format": "google-datetime",
          "type": "string"
        },
        "fields": {
          "description": "Indexed fields in structured data, returned as a generic named property.",
          "type": "array",
          "items": {
            "$ref": "NamedProperty"
          }
        },
        "owner": {
          "description": "Owner (usually creator) of the document or object of the search result.",
          "$ref": "Person"
        },
        "updateTime": {
          "type": "string",
          "description": "The last modified date for the object in the search result. If not\nset in the item, the value returned here is empty. When\n`updateTime` is used for calculating freshness and is not set, this\nvalue defaults to 2 years from the current time.",
          "format": "google-datetime"
        }
      },
      "id": "Metadata",
      "description": "Metadata of a matched search result.",
      "type": "object"
    },
    "MatchRange": {
      "description": "Matched range of a snippet [start, end).",
      "type": "object",
      "properties": {
        "end": {
          "description": "End of the match in the snippet.",
          "format": "int32",
          "type": "integer"
        },
        "start": {
          "description": "Starting position of the match in the snippet.",
          "format": "int32",
          "type": "integer"
        }
      },
      "id": "MatchRange"
    },
    "SuggestResult": {
      "id": "SuggestResult",
      "description": "One suggestion result.",
      "type": "object",
      "properties": {
        "source": {
          "$ref": "Source",
          "description": "The source of the suggestion."
        },
        "querySuggestion": {
          "$ref": "QuerySuggestion",
          "description": "This field will be present if the suggested query is a word/phrase\ncompletion."
        },
        "suggestedQuery": {
          "description": "The suggested query that will be used for search, when the user\nclicks on the suggestion",
          "type": "string"
        },
        "peopleSuggestion": {
          "description": "This is present when the suggestion indicates a person. It\ncontains more information about the person - like their email ID,\nname etc.",
          "$ref": "PeopleSuggestion"
        }
      }
    },
    "Operation": {
      "description": "This resource represents a long-running operation that is the result of a\nnetwork API call.",
      "type": "object",
      "properties": {
        "done": {
          "description": "If the value is `false`, it means the operation is still in progress.\nIf `true`, the operation is completed, and either `error` or `response` is\navailable.",
          "type": "boolean"
        },
        "name": {
          "description": "The server-assigned name, which is only unique within the same service that\noriginally returns it. If you use the default HTTP mapping, the\n`name` should be a resource name ending with `operations/{unique_id}`.",
          "type": "string"
        },
        "error": {
          "$ref": "Status",
          "description": "The error result of the operation in case of failure or cancellation."
        },
        "metadata": {
          "additionalProperties": {
            "description": "Properties of the object. Contains field @type with type URL.",
            "type": "any"
          },
          "description": "Service-specific metadata associated with the operation.  It typically\ncontains progress information and common metadata such as create time.\nSome services might not provide such metadata.  Any method that returns a\nlong-running operation should document the metadata type, if any.",
          "type": "object"
        }
      },
      "id": "Operation"
    },
    "DataSourceRestriction": {
      "type": "object",
      "properties": {
        "source": {
          "$ref": "Source",
          "description": "The source of restriction."
        },
        "filterOptions": {
          "description": "Filter options restricting the results. If multiple filters\nare present, they are grouped by object type before joining.\nFilters with the same object type are joined conjunctively, then\nthe resulting expressions are joined disjunctively.\n\nThe maximum number of elements is 20.\n\nNOTE: Suggest API supports only few filters at the moment:\n  \"objecttype\", \"type\" and \"mimetype\".\nFor now, schema specific filters cannot be used to filter suggestions.",
          "type": "array",
          "items": {
            "$ref": "FilterOptions"
          }
        }
      },
      "id": "DataSourceRestriction",
      "description": "Restriction on Datasource."
    },
    "UpdateSchemaRequest": {
      "type": "object",
      "properties": {
        "validateOnly": {
          "description": "If true, the request will be validated without side effects.",
          "type": "boolean"
        },
        "schema": {
          "description": "The new schema for the source.",
          "$ref": "Schema"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      },
      "id": "UpdateSchemaRequest"
    },
    "Status": {
      "description": "The `Status` type defines a logical error model that is suitable for\ndifferent programming environments, including REST APIs and RPC APIs. It is\nused by [gRPC](https://github.com/grpc). The error model is designed to be:\n\n- Simple to use and understand for most users\n- Flexible enough to meet unexpected needs\n\n# Overview\n\nThe `Status` message contains three pieces of data: error code, error\nmessage, and error details. The error code should be an enum value of\ngoo[...]",
      "type": "object",
      "properties": {
        "message": {
          "description": "A developer-facing error message, which should be in English. Any\nuser-facing error message should be localized and sent in the\ngoogle.rpc.Status.details field, or localized by the client.",
          "type": "string"
        },
        "details": {
          "description": "A list of messages that carry the error details.  There is a common set of\nmessage types for APIs to use.",
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": {
              "description": "Properties of the object. Contains field @type with type URL.",
              "type": "any"
            }
          }
        },
        "code": {
          "description": "The status code, which should be an enum value of google.rpc.Code.",
          "format": "int32",
          "type": "integer"
        }
      },
      "id": "Status"
    },
    "DriveLocationRestrict": {
      "description": "Drive location search restricts (e.g. \"is:starred\").",
      "type": "object",
      "properties": {
        "type": {
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "enum": [
            "UNSPECIFIED",
            "TRASHED",
            "STARRED"
          ],
          "type": "string"
        }
      },
      "id": "DriveLocationRestrict"
    },
    "RetrievalImportance": {
      "type": "object",
      "properties": {
        "importance": {
          "description": "Indicates the ranking importance given to property when it is matched\nduring retrieval. Once set, the token importance of a property cannot be\nchanged.",
          "type": "string",
          "enumDescriptions": [
            "Treat the match like a body text match.",
            "Treat the match like a match against title of the item.",
            "Treat the match with higher importance than body text.",
            "Treat the match with lower importance than body text.",
            "Do not match against this field during retrieval. The property can still\nbe used for operator matching, faceting, and suggest if\ndesired."
          ],
          "enum": [
            "DEFAULT",
            "HIGHEST",
            "HIGH",
            "LOW",
            "NONE"
          ]
        }
      },
      "id": "RetrievalImportance"
    },
    "DisplayedProperty": {
      "id": "DisplayedProperty",
      "description": "A reference to a top-level property within the object that should be\ndisplayed in search results. The values of the chosen properties will be\ndisplayed in the search results along with the\ndislpay label\nfor that property if one is specified. If a display label is not specified,\nonly the values will be shown.",
      "type": "object",
      "properties": {
        "propertyName": {
          "description": "The name of the top-level property as defined in a property definition\nfor the object. If the name is not a defined property in the schema, an\nerror will be given when attempting to update the schema.",
          "type": "string"
        }
      }
    },
    "ItemStatus": {
      "type": "object",
      "properties": {
        "processingErrors": {
          "description": "Error details in case the item is in ERROR state.",
          "type": "array",
          "items": {
            "$ref": "ProcessingError"
          }
        },
        "code": {
          "enum": [
            "CODE_UNSPECIFIED",
            "ERROR",
            "MODIFIED",
            "NEW_ITEM",
            "ACCEPTED"
          ],
          "description": "Status code.",
          "type": "string",
          "enumDescriptions": [
            "Input-only value.  Used with\nItems.list\nto list all items in the queue, regardless of status.",
            "Error encountered by Cloud Search while processing this item.\nDetails of the error are in\nrepositoryError.",
            "Item has been modified in the repository, and is out of date with\nthe version previously accepted into Cloud Search.",
            "Item is known to exist in the repository, but is not yet accepted by\nCloud Search.\nAn item can be in this state when\nItems.push\nhas been called for\nan item of this name that did not exist previously.",
            "API has accepted the up-to-date data of this item."
          ]
        },
        "repositoryErrors": {
          "description": "Repository error reported by connector.",
          "type": "array",
          "items": {
            "$ref": "RepositoryError"
          }
        }
      },
      "id": "ItemStatus",
      "description": "This contains item's status and any errors."
    },
    "FieldViolation": {
      "type": "object",
      "properties": {
        "field": {
          "description": "Path of field with violation.",
          "type": "string"
        },
        "description": {
          "description": "Description of the error.",
          "type": "string"
        }
      },
      "id": "FieldViolation"
    },
    "TextValues": {
      "description": "List of text values.",
      "type": "object",
      "properties": {
        "values": {
          "description": "The maximum allowable length for text values is 2048 characters.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "id": "TextValues"
    },
    "SourceScoringConfig": {
      "properties": {
        "sourceImportance": {
          "description": "Importance of the source.",
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "enum": [
            "DEFAULT",
            "LOW",
            "HIGH"
          ]
        }
      },
      "id": "SourceScoringConfig",
      "description": "Set the scoring configuration. This allows modifying the ranking of results\nfor a source.",
      "type": "object"
    },
    "ObjectPropertyOptions": {
      "id": "ObjectPropertyOptions",
      "description": "Options for object properties.",
      "type": "object",
      "properties": {
        "subobjectProperties": {
          "description": "The properties of the sub-object. These properties represent a nested\nobject. For example, if this property represents a postal address, the\nsubobjectProperties might be named *street*, *city*, and *state*.\nThe maximum number of elements is 1000.",
          "type": "array",
          "items": {
            "$ref": "PropertyDefinition"
          }
        }
      }
    },
    "DateOperatorOptions": {
      "id": "DateOperatorOptions",
      "description": "Optional. Provides a search operator for date properties.\nSearch operators let users restrict the query to specific fields relevant\nto the type of item being searched.",
      "type": "object",
      "properties": {
        "greaterThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ndate property using the greater-than operator. For example, if\ngreaterThanOperatorName is *closedafter* and the property's name is\n*closeDate*, then queries like *closedafter:&lt;value&gt;* will\nshow results only where the value of the property named *closeDate* is\nlater than *&lt;value&gt;*.\nThe operator name can only contain lowercase letters (a-z).\nThe maximum length is 32 characters.",
          "type": "string"
        },
        "lessThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ndate property using the less-than operator. For example, if\nlessThanOperatorName is *closedbefore* and the property's name is\n*closeDate*, then queries like *closedbefore:&lt;value&gt;* will\nshow results only where the value of the property named *closeDate* is\nearlier than *&lt;value&gt;*.\nThe operator name can only contain lowercase letters (a-z).\nThe maximum length is 32 characters.",
          "type": "string"
        },
        "operatorName": {
          "description": "Indicates the actual string required in the query in order to isolate the\ndate property. For example, suppose an issue tracking schema object\nhas a property named *closeDate* that specifies an operator with an\noperatorName of *closedon*. For searches on that data, queries like\n*closedon:&lt;value&gt;* will show results only where the value of the\n*closeDate* property matches *&lt;value&gt;*. By contrast, a\nsearch that uses the same *&lt;value&gt;* without an opera[...]",
          "type": "string"
        }
      }
    },
    "RequestOptions": {
      "description": "Shared request options for all RPC methods.",
      "type": "object",
      "properties": {
        "searchApplicationId": {
          "description": "Id of the application created using SearchApplicationsService.",
          "type": "string"
        },
        "languageCode": {
          "description": "The BCP-47 language code, such as \"en-US\" or \"sr-Latn\".\nFor more information, see\nhttp://www.unicode.org/reports/tr35/#Unicode_locale_identifier.\nFor translations.\n\nWhen specified, the documents in search results are biased towards the\nspecified language.\nSuggest API does not use this parameter. It autocompletes only based on\ncharacters in the query.",
          "type": "string"
        },
        "timeZone": {
          "description": "Current user's time zone id, such as \"America/Los_Angeles\" or\n\"Australia/Sydney\". These IDs are defined by\n[Unicode Common Locale Data Repository (CLDR)](http://cldr.unicode.org/)\nproject, and currently available in the file\n[timezone.xml](http://unicode.org/repos/cldr/trunk/common/bcp47/timezone.xml)",
          "type": "string"
        },
        "debugOptions": {
          "description": "Debug options of the request",
          "$ref": "DebugOptions"
        }
      },
      "id": "RequestOptions"
    },
    "ResultCounts": {
      "description": "Result count information",
      "type": "object",
      "properties": {
        "sourceResultCounts": {
          "type": "array",
          "items": {
            "$ref": "SourceResultCount"
          },
          "description": "Result count information for each source with results."
        }
      },
      "id": "ResultCounts"
    },
    "TimestampPropertyOptions": {
      "properties": {
        "operatorOptions": {
          "$ref": "TimestampOperatorOptions",
          "description": "If set, describes how the timestamp should be used as a search operator."
        }
      },
      "id": "TimestampPropertyOptions",
      "description": "Options for timestamp properties.",
      "type": "object"
    },
    "SuggestRequest": {
      "type": "object",
      "properties": {
        "requestOptions": {
          "$ref": "RequestOptions",
          "description": "Request options, such as the search application and user timezone."
        },
        "query": {
          "type": "string",
          "description": "Partial query for which autocomplete suggestions will be shown.\nFor example, if the query is \"sea\", then the server might return\n\"season\", \"search\", \"seagull\" and so on."
        },
        "dataSourceRestrictions": {
          "description": "The sources to use for suggestions. If not specified, all data sources\nfrom the current search application are used.\nSuggestions are based on Gmail titles. Suggestions from third party sources\nare not available.",
          "type": "array",
          "items": {
            "$ref": "DataSourceRestriction"
          }
        }
      },
      "id": "SuggestRequest",
      "description": "Request of suggest API."
    },
    "ScoringConfig": {
      "description": "Scoring configurations for a source while processing a\nSearch or\nSuggest request.",
      "type": "object",
      "properties": {
        "disableFreshness": {
          "description": "Whether to use freshness as a ranking signal. By default, freshness is used\nas a ranking signal. Note that this setting is not available in the Admin\nUI.",
          "type": "boolean"
        },
        "disablePersonalization": {
          "description": "Whether to personalize the results. By default, personal signals will\nbe used to boost results.",
          "type": "boolean"
        }
      },
      "id": "ScoringConfig"
    },
    "ValueFilter": {
      "type": "object",
      "properties": {
        "operatorName": {
          "description": "The `operator_name` applied to the query, such as *price_greater_than*.\nThe filter can work against both types of filters defined in the schema\nfor your data source:\n\u003cbr/\u003e\u003cbr/\u003e\n1. `operator_name`, where the query filters results by the property\nthat matches the value.\n\u003cbr/\u003e\n2. `greater_than_operator_name` or `less_than_operator_name` in your\nschema. The query filters the results for the property values that are\ngreater than or less[...]",
          "type": "string"
        },
        "value": {
          "$ref": "Value",
          "description": "The value to be compared with."
        }
      },
      "id": "ValueFilter"
    },
    "ListItemNamesForUnmappedIdentityResponse": {
      "type": "object",
      "properties": {
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no\nmore results in the list.",
          "type": "string"
        },
        "itemNames": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "id": "ListItemNamesForUnmappedIdentityResponse"
    },
    "ResponseDebugInfo": {
      "id": "ResponseDebugInfo",
      "description": "Debugging information about the response.",
      "type": "object",
      "properties": {
        "formattedDebugInfo": {
          "description": "General debug info formatted for display.",
          "type": "string"
        }
      }
    },
    "NamedProperty": {
      "description": "A typed name-value pair for structured data.  The type of the value should\nbe the same as the registered type for the `name` property in the object\ndefinition of `objectType`.",
      "type": "object",
      "properties": {
        "doubleValues": {
          "$ref": "DoubleValues"
        },
        "name": {
          "type": "string",
          "description": "The name of the property.  This name should correspond to the name of the\nproperty that was registered for object definition in the schema.\nThe maximum allowable length for this property is 256 characters."
        },
        "booleanValue": {
          "type": "boolean"
        },
        "textValues": {
          "$ref": "TextValues"
        },
        "htmlValues": {
          "$ref": "HtmlValues"
        },
        "timestampValues": {
          "$ref": "TimestampValues"
        },
        "objectValues": {
          "$ref": "ObjectValues"
        },
        "dateValues": {
          "$ref": "DateValues"
        },
        "enumValues": {
          "$ref": "EnumValues"
        },
        "integerValues": {
          "$ref": "IntegerValues"
        }
      },
      "id": "NamedProperty"
    },
    "UnmappedIdentity": {
      "type": "object",
      "properties": {
        "externalIdentity": {
          "description": "The resource name for an external user.",
          "$ref": "Principal"
        },
        "resolutionStatusCode": {
          "enumDescriptions": [
            "Input-only value.  Used to list all unmapped identities regardless of\nstatus.",
            "The unmapped identity was not found in IDaaS, and needs to be provided by\nthe user.",
            "The identity source associated with the identity was either not found or\ndeleted.",
            "IDaaS does not understand the identity source, probably because the\nschema was modified in a non compatible way.",
            "The number of users associated with the external identity is too large.",
            "Internal error."
          ],
          "enum": [
            "CODE_UNSPECIFIED",
            "NOT_FOUND",
            "IDENTITY_SOURCE_NOT_FOUND",
            "IDENTITY_SOURCE_MISCONFIGURED",
            "TOO_MANY_MAPPINGS_FOUND",
            "INTERNAL_ERROR"
          ],
          "description": "The resolution status for the external identity.",
          "type": "string"
        }
      },
      "id": "UnmappedIdentity"
    },
    "PushItemRequest": {
      "type": "object",
      "properties": {
        "connectorName": {
          "description": "Name of connector making this call.\n\u003cbr /\u003eFormat: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "item": {
          "$ref": "PushItem",
          "description": "Item to push onto the queue."
        }
      },
      "id": "PushItemRequest"
    },
    "SearchItemsByViewUrlRequest": {
      "type": "object",
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "pageToken": {
          "description": "The next_page_token value returned from a previous request, if any.",
          "type": "string"
        },
        "viewUrl": {
          "description": "Specify the full view URL to find the corresponding item.\nThe maximum length is 2048 characters.",
          "type": "string"
        }
      },
      "id": "SearchItemsByViewUrlRequest"
    },
    "PollItemsResponse": {
      "properties": {
        "items": {
          "description": "Set of items from the queue available for connector to process.\n\u003cbr /\u003eThese items have the following subset of fields populated: \u003cbr /\u003e\n\u003cbr /\u003eversion\n\u003cbr /\u003emetadata.hash\n\u003cbr /\u003estructured_data.hash\n\u003cbr /\u003econtent.hash\n\u003cbr /\u003epayload\n\u003cbr /\u003estatus\n\u003cbr /\u003equeue",
          "type": "array",
          "items": {
            "$ref": "Item"
          }
        }
      },
      "id": "PollItemsResponse",
      "type": "object"
    },
    "ListItemsResponse": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "Item"
          }
        },
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no\nmore results in the list.",
          "type": "string"
        }
      },
      "id": "ListItemsResponse"
    },
    "UnreserveItemsRequest": {
      "type": "object",
      "properties": {
        "connectorName": {
          "description": "Name of connector making this call.\n\u003cbr /\u003eFormat: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "queue": {
          "type": "string",
          "description": "Name of a queue to unreserve items from."
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      },
      "id": "UnreserveItemsRequest"
    },
    "HtmlPropertyOptions": {
      "description": "Options for html properties.",
      "type": "object",
      "properties": {
        "retrievalImportance": {
          "description": "Indicates the search quality importance of the tokens within the\nfield when used for retrieval. Can only be set to DEFAULT or NONE.",
          "$ref": "RetrievalImportance"
        },
        "operatorOptions": {
          "$ref": "HtmlOperatorOptions",
          "description": "If set, describes how the property should be used as a search operator."
        }
      },
      "id": "HtmlPropertyOptions"
    },
    "QueryOperator": {
      "description": "The definition of a operator that can be used in a Search/Suggest request.",
      "type": "object",
      "properties": {
        "displayName": {
          "description": "Display name of the operator",
          "type": "string"
        },
        "isReturnable": {
          "description": "Will the property associated with this facet be returned as part of search\nresults.",
          "type": "boolean"
        },
        "isFacetable": {
          "description": "Can this operator be used to get facets.",
          "type": "boolean"
        },
        "isSortable": {
          "description": "Can this operator be used to sort results.",
          "type": "boolean"
        },
        "operatorName": {
          "description": "The name of the operator.",
          "type": "string"
        },
        "isRepeatable": {
          "type": "boolean",
          "description": "Indicates if multiple values can be set for this property."
        },
        "greaterThanOperatorName": {
          "description": "Indicates the operator name that can be used to  isolate the property using\nthe greater-than operator.",
          "type": "string"
        },
        "enumValues": {
          "description": "Potential list of values for the opeatror field. This field is only filled\nwhen we can safely enumerate all the possible values of this operator.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "lessThanOperatorName": {
          "description": "Indicates the operator name that can be used to  isolate the property using\nthe less-than operator.",
          "type": "string"
        },
        "isSuggestable": {
          "description": "Can get suggestions for this field.",
          "type": "boolean"
        },
        "type": {
          "enumDescriptions": [
            "Invalid value.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "enum": [
            "UNKNOWN",
            "INTEGER",
            "DOUBLE",
            "TIMESTAMP",
            "BOOLEAN",
            "ENUM",
            "DATE",
            "TEXT",
            "HTML"
          ],
          "description": "Type of the operator.",
          "type": "string"
        }
      },
      "id": "QueryOperator"
    },
    "TimestampValues": {
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "format": "google-datetime",
            "type": "string"
          }
        }
      },
      "id": "TimestampValues",
      "description": "List of timestamp values.",
      "type": "object"
    },
    "SearchQualityMetadata": {
      "properties": {
        "quality": {
          "type": "number",
          "description": "An indication of the quality of the item, used to influence search quality.\nValue should be between 0.0 (lowest quality) and 1.0 (highest quality). The\ndefault value is 0.0.",
          "format": "double"
        }
      },
      "id": "SearchQualityMetadata",
      "description": "Additional search quality metadata of the item.",
      "type": "object"
    },
    "DatePropertyOptions": {
      "description": "Options for date properties.",
      "type": "object",
      "properties": {
        "operatorOptions": {
          "description": "If set, describes how the date should be used as a search operator.",
          "$ref": "DateOperatorOptions"
        }
      },
      "id": "DatePropertyOptions"
    },
    "RestrictItem": {
      "description": "Information relevant only to a restrict entry.\nNextId: 12",
      "type": "object",
      "properties": {
        "driveTimeSpanRestrict": {
          "$ref": "DriveTimeSpanRestrict"
        },
        "driveLocationRestrict": {
          "$ref": "DriveLocationRestrict"
        },
        "gmailTimeRestrict": {
          "$ref": "GmailTimeRestrict"
        },
        "gmailFolderRestrict": {
          "$ref": "GmailFolderRestrict",
          "description": "Gmail Types."
        },
        "gmailAttachmentRestrict": {
          "$ref": "GmailAttachmentRestrict"
        },
        "gmailIntelligentRestrict": {
          "$ref": "GmailIntelligentRestrict"
        },
        "gmailActionRestrict": {
          "$ref": "GmailActionRestrict"
        },
        "driveMimeTypeRestrict": {
          "$ref": "DriveMimeTypeRestrict",
          "description": "LINT.IfChange\nDrive Types."
        },
        "driveFollowUpRestrict": {
          "description": "LINT.ThenChange(//depot/google3/java/com/google/apps/search/quality/itemsuggest/utils/SubtypeRerankingUtils.java)",
          "$ref": "DriveFollowUpRestrict"
        },
        "searchOperator": {
          "description": "The search restrict (e.g. \"after:2017-09-11 before:2017-09-12\").",
          "type": "string"
        }
      },
      "id": "RestrictItem"
    },
    "DriveMimeTypeRestrict": {
      "type": "object",
      "properties": {
        "type": {
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "enum": [
            "UNSPECIFIED",
            "PDF",
            "DOCUMENT",
            "PRESENTATION",
            "SPREADSHEET",
            "FORM",
            "DRAWING",
            "SCRIPT",
            "MAP",
            "IMAGE",
            "AUDIO",
            "VIDEO",
            "FOLDER",
            "ARCHIVE",
            "SITE"
          ],
          "type": "string"
        }
      },
      "id": "DriveMimeTypeRestrict",
      "description": "Drive mime-type search restricts (e.g. \"type:pdf\")."
    },
    "Metaline": {
      "description": "A metaline is a list of properties that are displayed along with the search\nresult to provide context.",
      "type": "object",
      "properties": {
        "properties": {
          "description": "The list of displayed properties for the metaline. The maxiumum number of\nproperties is 5.",
          "type": "array",
          "items": {
            "$ref": "DisplayedProperty"
          }
        }
      },
      "id": "Metaline"
    },
    "BooleanOperatorOptions": {
      "id": "BooleanOperatorOptions",
      "description": "Used to provide a search operator for boolean properties. This is\noptional. Search operators let users restrict the query to specific fields\nrelevant to the type of item being searched.",
      "type": "object",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\nboolean property. For example, if operatorName is *closed* and the\nproperty's name is *isClosed*, then queries like\n*closed:&lt;value&gt;* will show results only where the value of the\nproperty named *isClosed* matches *&lt;value&gt;*. By contrast, a\nsearch that uses the same *&lt;value&gt;* without an operator will return\nall items where *&lt;value&gt;* matches the value of any\nString prop[...]",
          "type": "string"
        }
      }
    },
    "GmailAttachmentRestrict": {
      "description": "Gmail Attachment restricts (i.e. has:attachment, has:drive, filename:pdf).",
      "type": "object",
      "properties": {
        "type": {
          "enumDescriptions": [
            "",
            "has:attachment",
            "has photos (changes to filename:(jpg OR jpeg OR png)  when typed)",
            "has:drive",
            "has:document",
            "has:spreadsheet",
            "has:presentation",
            "has:youtube",
            "filename:pdf"
          ],
          "enum": [
            "UNSPECIFIED",
            "HAS_ATTACHMENT",
            "HAS_PHOTO",
            "HAS_DRIVE",
            "HAS_DOCUMENT",
            "HAS_SPREADSHEET",
            "HAS_PRESENTATION",
            "HAS_YOUTUBE",
            "HAS_PDF"
          ],
          "type": "string"
        }
      },
      "id": "GmailAttachmentRestrict"
    },
    "SourceConfig": {
      "description": "Configurations for a source while processing a\nSearch or\nSuggest request.",
      "type": "object",
      "properties": {
        "source": {
          "description": "The source for which this configuration is to be used.",
          "$ref": "Source"
        },
        "scoringConfig": {
          "$ref": "SourceScoringConfig",
          "description": "The scoring configuration for the source."
        },
        "crowdingConfig": {
          "$ref": "SourceCrowdingConfig",
          "description": "The crowding configuration for the source."
        }
      },
      "id": "SourceConfig"
    },
    "DataSource": {
      "description": "Datasource is a logical namespace for items to be indexed.\nAll items must belong to a datasource.  This is the prerequisite before\nitems can be indexed into Cloud Search.",
      "type": "object",
      "properties": {
        "disableServing": {
          "description": "Disable serving any search or assist results.",
          "type": "boolean"
        },
        "displayName": {
          "type": "string",
          "description": "Required. Display name of the datasource\nThe maximum length is 300 characters."
        },
        "itemsVisibility": {
          "type": "array",
          "items": {
            "$ref": "GSuitePrincipal"
          },
          "description": "This field restricts visibility to items at the datasource level. Items\nwithin the datasource are restricted to the union of users and groups\nincluded in this field. Note that, this does not ensure access to a\nspecific item, as users need to have ACL permissions on the contained\nitems. This ensures a high level access on the entire datasource, and\nthat the individual items are not shared outside this visibility."
        },
        "shortName": {
          "description": "A short name or alias for the source.  This value will be used to match the\n'source' operator. For example, if the short name is *&lt;value&gt;* then\nqueries like *source:&lt;value&gt;* will only return results for this\nsource. The value must be unique across all datasources. The value must\nonly contain alphanumeric characters (a-zA-Z0-9). The value cannot start\nwith 'google' and cannot be one of the following: mail, gmail, docs, drive,\ngroups, sites, calendar, ha[...]",
          "type": "string"
        },
        "name": {
          "description": "Name of the datasource resource.\nFormat: datasources/{source_id}.\n\u003cbr /\u003eThe name is ignored when creating a datasource.",
          "type": "string"
        },
        "operationIds": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "IDs of the Long Running Operations (LROs) currently running for this\nschema."
        },
        "disableModifications": {
          "description": "If true, Indexing API rejects any modification calls to this datasource\nsuch as create, update, and delete.\nDisabling this does not imply halting process of previously\naccepted data.",
          "type": "boolean"
        },
        "indexingServiceAccounts": {
          "description": "List of service accounts that have indexing access.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "id": "DataSource"
    },
    "UpdateDataSourceRequest": {
      "type": "object",
      "properties": {
        "source": {
          "$ref": "DataSource"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      },
      "id": "UpdateDataSourceRequest"
    },
    "FacetResult": {
      "description": "Source specific facet response",
      "type": "object",
      "properties": {
        "operatorName": {
          "description": "Name of the operator chosen for faceting. @see\ncloudsearch.SchemaPropertyOptions",
          "type": "string"
        },
        "objectType": {
          "description": "Object type for which facet results are returned. Can be empty.",
          "type": "string"
        },
        "sourceName": {
          "description": "Source name for which facet results are returned. Will not be empty.",
          "type": "string"
        },
        "buckets": {
          "description": "FacetBuckets for values in response containing at least a single result.",
          "type": "array",
          "items": {
            "$ref": "FacetBucket"
          }
        }
      },
      "id": "FacetResult"
    },
    "ItemCountByStatus": {
      "properties": {
        "count": {
          "description": "Number of items matching the status code.",
          "format": "int64",
          "type": "string"
        },
        "statusCode": {
          "enum": [
            "CODE_UNSPECIFIED",
            "ERROR",
            "MODIFIED",
            "NEW_ITEM",
            "ACCEPTED"
          ],
          "description": "Status of the items.",
          "type": "string",
          "enumDescriptions": [
            "Input-only value.  Used with\nItems.list\nto list all items in the queue, regardless of status.",
            "Error encountered by Cloud Search while processing this item.\nDetails of the error are in\nrepositoryError.",
            "Item has been modified in the repository, and is out of date with\nthe version previously accepted into Cloud Search.",
            "Item is known to exist in the repository, but is not yet accepted by\nCloud Search.\nAn item can be in this state when\nItems.push\nhas been called for\nan item of this name that did not exist previously.",
            "API has accepted the up-to-date data of this item."
          ]
        }
      },
      "id": "ItemCountByStatus",
      "type": "object"
    },
    "ItemMetadata": {
      "description": "Available metadata fields for the item.",
      "type": "object",
      "properties": {
        "searchQualityMetadata": {
          "$ref": "SearchQualityMetadata",
          "description": "Additional search quality metadata of the item"
        },
        "hash": {
          "description": "Hashing value provided by the API caller.\nThis can be used with the\nitems.push\nmethod to calculate modified state.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "interactions": {
          "description": "A list of interactions for the item.  Interactions are used to improve\nSearch quality, but are not exposed to end users.\nThe maximum number of elements is 1000.",
          "type": "array",
          "items": {
            "$ref": "Interaction"
          }
        },
        "keywords": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Additional keywords or phrases that should match the item.\nUsed internally for user generated content.\nThe maximum number of elements is 100.\nThe maximum length is 8192 characters."
        },
        "mimeType": {
          "type": "string",
          "description": "The original mime-type of\nItemContent.content\nin the source repository.\nThe maximum length is 256 characters."
        },
        "title": {
          "description": "The title of the item.  If given, this will be the displayed title of the\nSearch result.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "createTime": {
          "description": "The time when the item was created in the source repository.",
          "format": "google-datetime",
          "type": "string"
        },
        "contentLanguage": {
          "description": "The BCP-47 language code for the item, such as \"en-US\" or \"sr-Latn\". For\nmore information, see\nhttp://www.unicode.org/reports/tr35/#Unicode_locale_identifier.\nThe maximum length is 32 characters.",
          "type": "string"
        },
        "sourceRepositoryUrl": {
          "description": "Link to the source repository serving the data.  &#83;earch results apply\nthis link to the title.\nThe maximum length is 2048 characters.",
          "type": "string"
        },
        "updateTime": {
          "description": "The time when the item was last modified in the source repository.",
          "format": "google-datetime",
          "type": "string"
        },
        "containerName": {
          "description": "The name of the container for this item.\nDeletion of the container item leads to automatic deletion of this\nitem.  Note: ACLs are not inherited from a container item.\nTo provide ACL inheritance for an item, use the\ninheritAclFrom\nfield. The maximum length is 1536 characters.",
          "type": "string"
        },
        "objectType": {
          "description": "The type of the item.  This should correspond to the name of an object\ndefinition in the schema registered for the data source.  For example, if\nthe schema for the data source contains an object definition with name\n'document', then item indexing requests for objects of that type should set\nobjectType to 'document'.\nThe maximum length is 256 characters.",
          "type": "string"
        }
      },
      "id": "ItemMetadata"
    },
    "IntegerPropertyOptions": {
      "description": "Options for integer properties.",
      "type": "object",
      "properties": {
        "orderedRanking": {
          "description": "Used to specify the ordered ranking for the integer. Can only be used if\nisRepeatable\nis false.",
          "type": "string",
          "enumDescriptions": [
            "There is no ranking order for the property. Results will not be adjusted\nby this property's value.",
            "This property is ranked in ascending order. Lower values indicate lower\nranking.",
            "This property is ranked in descending order. Lower values indicate\nhigher ranking."
          ],
          "enum": [
            "NO_ORDER",
            "ASCENDING",
            "DESCENDING"
          ]
        },
        "maximumValue": {
          "description": "The maximum value of the property. The minimum and maximum values for the\nproperty are used to rank results according to the\nordered ranking.\nIndexing requests with values greater than the maximum are accepted and\nranked with the same weight as items indexed with the maximum value.",
          "format": "int64",
          "type": "string"
        },
        "minimumValue": {
          "description": "The minimum value of the property. The minimum and maximum values for the\nproperty are used to rank results according to the\nordered ranking.\nIndexing requests with values less than the minimum are accepted and\nranked with the same weight as items indexed with the minimum value.",
          "format": "int64",
          "type": "string"
        },
        "operatorOptions": {
          "description": "If set, describes how the integer should be used as a search operator.",
          "$ref": "IntegerOperatorOptions"
        }
      },
      "id": "IntegerPropertyOptions"
    },
    "IndexItemOptions": {
      "type": "object",
      "properties": {
        "allowUnknownGsuitePrincipals": {
          "description": "Specifies if the index request should allow gsuite principals that do not\nexist or are deleted in the index request.",
          "type": "boolean"
        }
      },
      "id": "IndexItemOptions"
    },
    "StructuredDataObject": {
      "description": "A structured data object consisting of named properties.",
      "type": "object",
      "properties": {
        "properties": {
          "description": "The properties for the object.\nThe maximum number of elements is 1000.",
          "type": "array",
          "items": {
            "$ref": "NamedProperty"
          }
        }
      },
      "id": "StructuredDataObject"
    },
    "EnumPropertyOptions": {
      "id": "EnumPropertyOptions",
      "description": "Options for enum properties, which allow you to define a restricted set of\nstrings to match user queries, set rankings for those string values, and\ndefine an operator name to be paired with those strings so that users can\nnarrow results to only items with a specific value. For example, for items in\na request tracking system with priority information, you could define *p0* as\nan allowable enum value and tie this enum to the operator name *priority* so\nthat search users[...]",
      "type": "object",
      "properties": {
        "operatorOptions": {
          "description": "If set, describes how the enum should be used as a search operator.",
          "$ref": "EnumOperatorOptions"
        },
        "possibleValues": {
          "description": "The list of possible values for the enumeration property. All\nEnumValuePairs must provide a string value. If you specify an integer value\nfor one EnumValuePair, then all possible EnumValuePairs must provide an\ninteger value. Both the string value and integer value must be unique over\nall possible values. Once set, possible values cannot be removed or\nmodified. If you supply an ordered ranking and think you might insert\nadditional enum values in the future, leave g[...]",
          "type": "array",
          "items": {
            "$ref": "EnumValuePair"
          }
        },
        "orderedRanking": {
          "enum": [
            "NO_ORDER",
            "ASCENDING",
            "DESCENDING"
          ],
          "description": "Used to specify the ordered ranking for the enumeration that determines how\nthe integer values provided in the possible EnumValuePairs are used to rank\nresults. If specified, integer values must be provided for all possible\nEnumValuePair values given for this property. Can only be used if\nisRepeatable\nis false.",
          "type": "string",
          "enumDescriptions": [
            "There is no ranking order for the property. Results will not be adjusted\nby this property's value.",
            "This property is ranked in ascending order. Lower values indicate lower\nranking.",
            "This property is ranked in descending order. Lower values indicate\nhigher ranking."
          ]
        }
      }
    },
    "SourceResultCount": {
      "description": "Per source result count information.",
      "type": "object",
      "properties": {
        "hasMoreResults": {
          "description": "Whether there are more search results for this source.",
          "type": "boolean"
        },
        "source": {
          "$ref": "Source",
          "description": "The source the result count information is associated with."
        },
        "resultCountExact": {
          "description": "The exact result count for this source.",
          "format": "int64",
          "type": "string"
        },
        "resultCountEstimate": {
          "description": "The estimated result count for this source.",
          "format": "int64",
          "type": "string"
        }
      },
      "id": "SourceResultCount"
    },
    "GetCustomerIndexStatsResponse": {
      "properties": {
        "stats": {
          "description": "Summary of indexed item counts, one for each day in the requested range.",
          "type": "array",
          "items": {
            "$ref": "CustomerIndexStats"
          }
        }
      },
      "id": "GetCustomerIndexStatsResponse",
      "type": "object"
    },
    "QuerySource": {
      "description": "List of sources that the user can search using the query API.",
      "type": "object",
      "properties": {
        "displayName": {
          "description": "Display name of the data source.",
          "type": "string"
        },
        "source": {
          "$ref": "Source",
          "description": "Name of the source"
        },
        "operators": {
          "description": "List of all operators applicable for this source.",
          "type": "array",
          "items": {
            "$ref": "QueryOperator"
          }
        },
        "shortName": {
          "description": "A short name or alias for the source.  This value can be used with the\n'source' operator.",
          "type": "string"
        }
      },
      "id": "QuerySource"
    },
    "QueryInterpretation": {
      "type": "object",
      "properties": {
        "interpretationType": {
          "enumDescriptions": [
            "No natural language interpretation or the natural language interpretation\nis not used to fetch the search results.",
            "The natural language results is mixed with results from original query.",
            "The results only contain natural language results."
          ],
          "enum": [
            "NONE",
            "BLEND",
            "REPLACE"
          ],
          "type": "string"
        },
        "interpretedQuery": {
          "description": "The interpretation of the query used in search. For example, query \"email\nfrom john\" will be interpreted as \"from:john source:mail\"",
          "type": "string"
        }
      },
      "id": "QueryInterpretation"
    },
    "ErrorMessage": {
      "id": "ErrorMessage",
      "description": "Error message per source response.",
      "type": "object",
      "properties": {
        "source": {
          "$ref": "Source"
        },
        "errorMessage": {
          "type": "string"
        }
      }
    },
    "TextOperatorOptions": {
      "description": "Used to provide a search operator for text properties. This is optional.\nSearch operators let users restrict the query to specific fields relevant\nto the type of item being searched.",
      "type": "object",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ntext property. For example, if operatorName is *subject* and the\nproperty's name is *subjectLine*, then queries like\n*subject:&lt;value&gt;* will show results only where the value of the\nproperty named *subjectLine* matches *&lt;value&gt;*. By contrast, a\nsearch that uses the same *&lt;value&gt;* without an operator will return\nall items where *&lt;value&gt;* matches the value of any\ntext p[...]",
          "type": "string"
        },
        "exactMatchWithOperator": {
          "description": "If true, the text value will be tokenized as one atomic value in\noperator searches and facet matches. For example, if the operator name is\n\"genre\" and the value is \"science-fiction\" the query restrictions\n\"genre:science\" and \"genre:fiction\" will not match the item;\n\"genre:science-fiction\" will. Value matching is case-sensitive\nand does not remove special characters.\nIf false, the text will be tokenized. For example, if the value is\n\"science-fiction\" t[...]",
          "type": "boolean"
        }
      },
      "id": "TextOperatorOptions"
    },
    "ResultDisplayField": {
      "description": "Display Fields for Search Results",
      "type": "object",
      "properties": {
        "operatorName": {
          "description": "The operator name of the property.",
          "type": "string"
        },
        "label": {
          "type": "string",
          "description": "The display label for the property."
        },
        "property": {
          "$ref": "NamedProperty",
          "description": "The name value pair for the property."
        }
      },
      "id": "ResultDisplayField"
    },
    "ListQuerySourcesResponse": {
      "description": "List sources response.",
      "type": "object",
      "properties": {
        "nextPageToken": {
          "type": "string"
        },
        "sources": {
          "type": "array",
          "items": {
            "$ref": "QuerySource"
          }
        }
      },
      "id": "ListQuerySourcesResponse"
    },
    "Media": {
      "id": "Media",
      "description": "Media resource.",
      "type": "object",
      "properties": {
        "resourceName": {
          "description": "Name of the media resource.",
          "type": "string"
        }
      }
    },
    "FacetBucket": {
      "description": "A bucket in a facet is the basic unit of operation. A bucket can comprise\neither a single value OR a contiguous range of values, depending on the\ntype of the field bucketed.\nFacetBucket is currently used only for returning the response object.",
      "type": "object",
      "properties": {
        "count": {
          "description": "Number of results that match the bucket value. Counts are only returned\nfor searches when count accuracy is ensured. Can be empty.",
          "format": "int32",
          "type": "integer"
        },
        "percentage": {
          "description": "Percent of results that match the bucket value. This value is between\n(0-100]. Percentages are returned for all searches, but are an estimate.\nBecause percentages are always returned, you should render percentages\ninstead of counts.",
          "format": "int32",
          "type": "integer"
        },
        "value": {
          "$ref": "Value"
        }
      },
      "id": "FacetBucket"
    },
    "Filter": {
      "description": "A generic way of expressing filters in a query, which supports two\napproaches: \u003cbr/\u003e\u003cbr/\u003e\n**1. Setting a ValueFilter.** The name must match an operator_name defined in\nthe schema for your data source.\n\u003cbr/\u003e\n**2. Setting a CompositeFilter.** The filters are evaluated\nusing the logical operator. The top-level operators can only be either an AND\nor a NOT. AND can appear only at the top-most level. OR can appear only under\na top-level AND."[...]",
      "type": "object",
      "properties": {
        "compositeFilter": {
          "$ref": "CompositeFilter"
        },
        "valueFilter": {
          "$ref": "ValueFilter"
        }
      },
      "id": "Filter"
    },
    "IntegerOperatorOptions": {
      "id": "IntegerOperatorOptions",
      "description": "Used to provide a search operator for integer properties. This is\noptional. Search operators let users restrict the query to specific fields\nrelevant to the type of item being searched.",
      "type": "object",
      "properties": {
        "greaterThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ninteger property using the greater-than operator. For example, if\ngreaterThanOperatorName is *priorityabove* and the property's name is\n*priorityVal*, then queries like *priorityabove:&lt;value&gt;* will\nshow results only where the value of the property named *priorityVal* is\ngreater than *&lt;value&gt;*.\nThe operator name can only contain lowercase letters (a-z).\nThe maximum length is 32 c[...]",
          "type": "string"
        },
        "lessThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ninteger property using the less-than operator. For example, if\nlessThanOperatorName is *prioritybelow* and the property's name is\n*priorityVal*, then queries like *prioritybelow:&lt;value&gt;* will\nshow results only where the value of the property named *priorityVal* is\nless than *&lt;value&gt;*.\nThe operator name can only contain lowercase letters (a-z).\nThe maximum length is 32 characters[...]",
          "type": "string"
        },
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the\ninteger property. For example, if operatorName is *priority* and the\nproperty's name is *priorityVal*, then queries like\n*priority:&lt;value&gt;* will show results only where the value of the\nproperty named *priorityVal* matches *&lt;value&gt;*. By contrast, a\nsearch that uses the same *&lt;value&gt;* without an operator will return\nall items where *&lt;value&gt;* matches the value of any St[...]",
          "type": "string"
        }
      }
    },
    "Name": {
      "description": "A person's name.",
      "type": "object",
      "properties": {
        "displayName": {
          "description": "The read-only display name formatted according to the locale specified by\nthe viewer's account or the \u003ccode\u003eAccept-Language\u003c/code\u003e HTTP header.",
          "type": "string"
        }
      },
      "id": "Name"
    },
    "ResetSearchApplicationRequest": {
      "type": "object",
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      },
      "id": "ResetSearchApplicationRequest"
    },
    "FilterOptions": {
      "id": "FilterOptions",
      "description": "Filter options to be applied on query.",
      "type": "object",
      "properties": {
        "objectType": {
          "type": "string",
          "description": "If object_type is set, only objects of that type are returned. This should\ncorrespond to the name of the object that was registered within the\ndefinition of schema. The maximum length is 256 characters."
        },
        "filter": {
          "$ref": "Filter",
          "description": "Generic filter to restrict the search, such as `lang:en`, `site:xyz`."
        }
      }
    },
    "ProcessingError": {
      "type": "object",
      "properties": {
        "fieldViolations": {
          "description": "In case the item fields are invalid, this field contains the details\nabout the validation errors.",
          "type": "array",
          "items": {
            "$ref": "FieldViolation"
          }
        },
        "code": {
          "enum": [
            "PROCESSING_ERROR_CODE_UNSPECIFIED",
            "MALFORMED_REQUEST",
            "UNSUPPORTED_CONTENT_FORMAT",
            "INDIRECT_BROKEN_ACL",
            "ACL_CYCLE"
          ],
          "description": "Error code indicating the nature of the error.",
          "type": "string",
          "enumDescriptions": [
            "Input only value.  Use this value in Items.",
            "Item's ACL, metadata, or content is malformed or in invalid state.\nFieldViolations contains more details on where the problem is.",
            "Countent format is unsupported.",
            "Items with incomplete ACL information due to inheriting other\nitems with broken ACL or having groups with unmapped descendants.",
            "ACL inheritance graph formed a cycle."
          ]
        },
        "errorMessage": {
          "description": "Description of the error.",
          "type": "string"
        }
      },
      "id": "ProcessingError"
    },
    "EnumValues": {
      "type": "object",
      "properties": {
        "values": {
          "description": "The maximum allowable length for string values is 32 characters.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "id": "EnumValues",
      "description": "List of enum values."
    },
    "ListUnmappedIdentitiesResponse": {
      "type": "object",
      "properties": {
        "nextPageToken": {
          "type": "string",
          "description": "Token to retrieve the next page of results, or empty if there are no\nmore results in the list."
        },
        "unmappedIdentities": {
          "type": "array",
          "items": {
            "$ref": "UnmappedIdentity"
          }
        }
      },
      "id": "ListUnmappedIdentitiesResponse"
    },
    "ResultDisplayLine": {
      "description": "The collection of fields that make up a displayed line",
      "type": "object",
      "properties": {
        "fields": {
          "type": "array",
          "items": {
            "$ref": "ResultDisplayField"
          }
        }
      },
      "id": "ResultDisplayLine"
    },
    "DataSourceIndexStats": {
      "description": "Aggregation of items by status code as of the specified date.",
      "type": "object",
      "properties": {
        "itemCountByStatus": {
          "description": "Number of items aggregrated by status code.",
          "type": "array",
          "items": {
            "$ref": "ItemCountByStatus"
          }
        },
        "date": {
          "$ref": "Date",
          "description": "Date for which index stats were calculated. If the date of request is not\nthe current date then stats calculated on the next day are returned. Stats\nare calculated close to mid night in this case. If date of request is\ncurrent date, then real time stats are returned."
        }
      },
      "id": "DataSourceIndexStats"
    },
    "Item": {
      "description": "Represents a single object that is an item in the search index, such as a\nfile, folder, or a database record.",
      "type": "object",
      "properties": {
        "itemType": {
          "description": "Type for this item.",
          "type": "string",
          "enumDescriptions": [
            "",
            "An item that is indexed for the only purpose of serving information.\nThese items cannot be referred in\ncontainerName\nor inheritAclFrom\nfields.",
            "An item that gets indexed and whose purpose is to supply other items\nwith ACLs and/or contain other items.",
            "An item that does not get indexed, but otherwise has the same purpose\nas CONTAINER_ITEM."
          ],
          "enum": [
            "UNSPECIFIED",
            "CONTENT_ITEM",
            "CONTAINER_ITEM",
            "VIRTUAL_CONTAINER_ITEM"
          ]
        },
        "structuredData": {
          "description": "The structured data for the item that should conform to a registered\nobject definition in the schema for the data source.",
          "$ref": "ItemStructuredData"
        },
        "status": {
          "$ref": "ItemStatus",
          "description": "Status of the item.\nOutput only field."
        },
        "payload": {
          "description": "Additional state connector can store for this item.\nThe maximum length is 10000 bytes.",
          "format": "byte",
          "type": "string"
        },
        "name": {
          "type": "string",
          "description": "Name of the Item. Format:\ndatasources/{source_id}/items/{item_id}\n\u003cbr /\u003eThis is a required field.\nThe maximum length is 1536 characters."
        },
        "acl": {
          "description": "Access control list for this item.",
          "$ref": "ItemAcl"
        },
        "content": {
          "description": "Item content to be indexed and made text searchable.",
          "$ref": "ItemContent"
        },
        "metadata": {
          "description": "Metadata information.",
          "$ref": "ItemMetadata"
        },
        "version": {
          "description": "Required. The indexing system stores the version from the datasource as a\nbyte string and compares the Item version in the index\nto the version of the queued Item using lexical ordering.\n\u003cbr /\u003e\u003cbr /\u003e\nCloud Search Indexing won't index or delete any queued item with\na version value that is less than or equal to the version of the\ncurrently indexed item.\nThe maximum length for this field is 1024 bytes.",
          "format": "byte",
          "type": "string"
        },
        "queue": {
          "description": "Queue this item belongs to.\nThe maximum length is 100 characters.",
          "type": "string"
        }
      },
      "id": "Item"
    },
    "DebugOptions": {
      "description": "Shared request debug options for all cloudsearch RPC methods.",
      "type": "object",
      "properties": {
        "enableDebugging": {
          "description": "If you are asked by Google to help with debugging, set this field.\nOtherwise, ignore this field.",
          "type": "boolean"
        }
      },
      "id": "DebugOptions"
    },
    "ItemStructuredData": {
      "description": "Available structured data fields for the item.",
      "type": "object",
      "properties": {
        "object": {
          "$ref": "StructuredDataObject",
          "description": "The structured data object that should conform to a registered object\ndefinition in the schema for the data source."
        },
        "hash": {
          "type": "string",
          "description": "Hashing value provided by the API caller.\nThis can be used with the\nitems.push\nmethod to calculate modified state.\nThe maximum length is 2048 characters."
        }
      },
      "id": "ItemStructuredData"
    },
    "Interaction": {
      "description": "Represents an interaction between a user and an item.",
      "type": "object",
      "properties": {
        "interactionTime": {
          "description": "The time when the user acted on the item.  If multiple actions of the same\ntype exist for a single user, only the most recent action is recorded.",
          "format": "google-datetime",
          "type": "string"
        },
        "principal": {
          "$ref": "Principal",
          "description": "The user that acted on the item."
        },
        "type": {
          "enumDescriptions": [
            "Invalid value.",
            "This interaction indicates the user viewed the item.",
            "This interaction indicates the user edited the item."
          ],
          "enum": [
            "UNSPECIFIED",
            "VIEW",
            "EDIT"
          ],
          "type": "string"
        }
      },
      "id": "Interaction"
    },
    "StartUploadItemRequest": {
      "description": "Start upload file request.",
      "type": "object",
      "properties": {
        "connectorName": {
          "description": "Name of connector making this call.\n\u003cbr /\u003eFormat: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        }
      },
      "id": "StartUploadItemRequest"
    },
    "Value": {
      "description": "Definition of a single value with generic type.",
      "type": "object",
      "properties": {
        "integerValue": {
          "format": "int64",
          "type": "string"
        },
        "stringValue": {
          "type": "string"
        },
        "dateValue": {
          "$ref": "Date"
        },
        "doubleValue": {
          "format": "double",
          "type": "number"
        },
        "timestampValue": {
          "format": "google-datetime",
          "type": "string"
        },
        "booleanValue": {
          "type": "boolean"
        }
      },
      "id": "Value"
    },
    "Photo": {
      "description": "A person's photo.",
      "type": "object",
      "properties": {
        "url": {
          "type": "string",
          "description": "The URL of the photo."
        }
      },
      "id": "Photo"
    },
    "GmailFolderRestrict": {
      "description": "Gmail Folder restricts (i.e. in Drafts/Sent/Chats/User Generated Labels).",
      "type": "object",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "IN_SENT",
            "IN_DRAFT",
            "CHATS",
            "IN_TRASH",
            "USER_GENERATED_LABEL"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "in:sent",
            "in:draft",
            "label:chats",
            "in:trash",
            "label:\u003cuser generated\u003e"
          ]
        }
      },
      "id": "GmailFolderRestrict"
    },
    "ItemAcl": {
      "description": "Access control list information for the item. For more information see\nhttps://developers.google.com/cloud-search/docs/guides/index-your-data#acls",
      "type": "object",
      "properties": {
        "aclInheritanceType": {
          "enumDescriptions": [
            "The default value when this item does not inherit an ACL.\nUse NOT_APPLICABLE when\ninheritAclFrom\nis empty.  An item without ACL inheritance can still have ACLs supplied\nby its own readers and\ndeniedReaders fields.",
            "During an authorization conflict, the ACL of the child item determines\nits read access.",
            "During an authorization conflict, the ACL of the parent item\nspecified in the\ninheritAclFrom\nfield determines read access.",
            "Access is granted only if this item and the parent item specified in\nthe inheritAclFrom\nfield both permit read access."
          ],
          "enum": [
            "NOT_APPLICABLE",
            "CHILD_OVERRIDE",
            "PARENT_OVERRIDE",
            "BOTH_PERMIT"
          ],
          "description": "Sets the type of access rules to apply when an item inherits its ACL from a\nparent. This should always be set in tandem with the\ninheritAclFrom\nfield. Also, when the\ninheritAclFrom field\nis set, this field should be set to a valid AclInheritanceType.",
          "type": "string"
        },
        "owners": {
          "description": "Optional. List of owners for the item. This field has no bearing on\ndocument access permissions. It does, however, offer\na slight ranking boosts items where the querying user is an owner.\nThe maximum number of elements is 5.",
          "type": "array",
          "items": {
            "$ref": "Principal"
          }
        },
        "inheritAclFrom": {
          "description": "Name of the item to inherit the Access Permission List (ACL) from.\nNote: ACL inheritance *only* provides access permissions\nto child items and does not define structural relationships, nor does it\nprovide convenient ways to delete large groups of items.\nDeleting an ACL parent from the index only alters the access permissions of\nchild items that reference the parent in the\ninheritAclFrom\nfield. The item is still in the index, but may not\nvisible in search results[...]",
          "type": "string"
        },
        "deniedReaders": {
          "description": "List of principals who are explicitly denied access to the item in search\nresults. While principals are denied access by default, use denied readers\nto handle exceptions and override the list allowed readers.\nThe maximum number of elements is 100.",
          "type": "array",
          "items": {
            "$ref": "Principal"
          }
        },
        "readers": {
          "description": "List of principals who are allowed to see the item in search results.\nOptional if inheriting permissions from another item or if the item\nis not intended to be visible, such as\nvirtual\ncontainers.\nThe maximum number of elements is 1000.",
          "type": "array",
          "items": {
            "$ref": "Principal"
          }
        }
      },
      "id": "ItemAcl"
    },
    "RepositoryError": {
      "description": "Errors when the connector is communicating to the source repository.",
      "type": "object",
      "properties": {
        "httpStatusCode": {
          "description": "Error codes.  Matches the definition of HTTP status codes.",
          "format": "int32",
          "type": "integer"
        },
        "type": {
          "enum": [
            "UNKNOWN",
            "NETWORK_ERROR",
            "DNS_ERROR",
            "CONNECTION_ERROR",
            "AUTHENTICATION_ERROR",
            "AUTHORIZATION_ERROR",
            "SERVER_ERROR",
            "QUOTA_EXCEEDED",
            "SERVICE_UNAVAILABLE",
            "CLIENT_ERROR"
          ],
          "description": "Type of error.",
          "type": "string",
          "enumDescriptions": [
            "Unknown error.",
            "Unknown or unreachable host.",
            "DNS problem, such as the DNS server is not responding.",
            "Cannot connect to the repository server.",
            "Failed authentication due to incorrect credentials.",
            "Service account is not authorized for the repository.",
            "Repository server error.",
            "Quota exceeded.",
            "Server temporarily unavailable.",
            "Client-related error, such as an invalid request from the connector to\nthe repository server."
          ]
        },
        "errorMessage": {
          "description": "Message that describes the error. The maximum allowable length\nof the message is 8192 characters.",
          "type": "string"
        }
      },
      "id": "RepositoryError"
    },
    "Principal": {
      "description": "Reference to a user, group, or domain.",
      "type": "object",
      "properties": {
        "userResourceName": {
          "description": "This principal is a user identified using an external identity.\nThe name field must specify the user resource name with this format:\nidentitysources/{source_id}/users/{ID}",
          "type": "string"
        },
        "gsuitePrincipal": {
          "$ref": "GSuitePrincipal",
          "description": "This principal is a GSuite user, group or domain."
        },
        "groupResourceName": {
          "description": "This principal is a group identified using an external identity.\nThe name field must specify the group resource name with this format:\nidentitysources/{source_id}/groups/{ID}",
          "type": "string"
        }
      },
      "id": "Principal"
    },
    "ResultDebugInfo": {
      "description": "Debugging information about the result.",
      "type": "object",
      "properties": {
        "formattedDebugInfo": {
          "description": "General debug info formatted for display.",
          "type": "string"
        }
      },
      "id": "ResultDebugInfo"
    },
    "SortOptions": {
      "type": "object",
      "properties": {
        "operatorName": {
          "description": "Name of the operator corresponding to the field to sort on.\nThe corresponding property must be marked as\nsortable.",
          "type": "string"
        },
        "sortOrder": {
          "description": "Ascending is the default sort order",
          "type": "string",
          "enumDescriptions": [
            "",
            ""
          ],
          "enum": [
            "ASCENDING",
            "DESCENDING"
          ]
        }
      },
      "id": "SortOptions"
    },
    "PropertyDefinition": {
      "description": "The definition of a property within an object.",
      "type": "object",
      "properties": {
        "enumPropertyOptions": {
          "$ref": "EnumPropertyOptions"
        },
        "displayOptions": {
          "description": "Options that determine how the property is displayed in the Cloud Search\nresults page if it is specified to be displayed in the object's\ndisplay options\n.",
          "$ref": "PropertyDisplayOptions"
        },
        "datePropertyOptions": {
          "$ref": "DatePropertyOptions"
        },
        "isSortable": {
          "description": "Indicates that the property can be used for sorting. Cannot be true for\nproperties that are repeatable. Cannot be true for properties whose type\nis object or user identifier. IsReturnable must be true to set this option.\nOnly supported for Boolean, Date, Double, Integer, and Timestamp\nproperties.",
          "type": "boolean"
        },
        "isFacetable": {
          "description": "Indicates that the property can be used for generating facets. Cannot be\ntrue for properties whose type is object. IsReturnable must be true to set\nthis option.\nOnly supported for Boolean, Enum, and Text properties.",
          "type": "boolean"
        },
        "isReturnable": {
          "description": "Indicates that the property identifies data that should be returned in\nsearch results via the Query API. If set to *true*, indicates that Query\nAPI users can use matching property fields in results. However, storing\nfields requires more space allocation and uses more bandwidth for search\nqueries, which impacts performance over large datasets. Set to *true* here\nonly if the field is needed for search results. Cannot be true for\nproperties whose type is an object.",
          "type": "boolean"
        },
        "name": {
          "type": "string",
          "description": "The name of the property. Item indexing requests sent to the Indexing API\nshould set the property name\nequal to this value. For example, if name is *subject_line*, then indexing\nrequests for document items with subject fields should set the\nname for that field equal to\n*subject_line*. Use the name as the identifier for the object property.\nOnce registered as a property for an object, you cannot re-use this name\nfor another property within that object.\nThe name m[...]"
        },
        "booleanPropertyOptions": {
          "$ref": "BooleanPropertyOptions"
        },
        "timestampPropertyOptions": {
          "$ref": "TimestampPropertyOptions"
        },
        "doublePropertyOptions": {
          "$ref": "DoublePropertyOptions"
        },
        "textPropertyOptions": {
          "$ref": "TextPropertyOptions"
        },
        "isWildcardSearchable": {
          "description": "Indicates that users can perform wildcard search for this\nproperty. Only supported for Text properties. IsReturnable must be true to\nset this option. In a given datasource maximum of 5 properties can be\nmarked as is_wildcard_searchable.\n\nNote: This is an alpha feature and is enabled for whitelisted users only.",
          "type": "boolean"
        },
        "isRepeatable": {
          "description": "Indicates that multiple values are allowed for the property. For example, a\ndocument only has one description but can have multiple comments. Cannot be\ntrue for properties whose type is a boolean.\nIf set to false, properties that contain more than one value will cause the\nindexing request for that item to be rejected.",
          "type": "boolean"
        },
        "objectPropertyOptions": {
          "$ref": "ObjectPropertyOptions"
        },
        "integerPropertyOptions": {
          "$ref": "IntegerPropertyOptions"
        },
        "htmlPropertyOptions": {
          "$ref": "HtmlPropertyOptions"
        }
      },
      "id": "PropertyDefinition"
    },
    "Schema": {
      "description": "The schema definition for a data source.",
      "type": "object",
      "properties": {
        "operationIds": {
          "description": "IDs of the Long Running Operations (LROs) currently running for this\nschema. After modifying the schema, wait for operations to complete\nbefore indexing additional content.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "objectDefinitions": {
          "description": "The list of top-level objects for the data source.\nThe maximum number of elements is 10.",
          "type": "array",
          "items": {
            "$ref": "ObjectDefinition"
          }
        }
      },
      "id": "Schema"
    },
    "GSuitePrincipal": {
      "type": "object",
      "properties": {
        "gsuiteUserEmail": {
          "description": "This principal references a G Suite user account",
          "type": "string"
        },
        "gsuiteGroupEmail": {
          "description": "This principal references a G Suite group account",
          "type": "string"
        },
        "gsuiteDomain": {
          "description": "This principal represents all users of the G Suite domain of the\ncustomer.",
          "type": "boolean"
        }
      },
      "id": "GSuitePrincipal"
    },
    "TextPropertyOptions": {
      "description": "Options for text properties.",
      "type": "object",
      "properties": {
        "retrievalImportance": {
          "$ref": "RetrievalImportance",
          "description": "Indicates the search quality importance of the tokens within the\nfield when used for retrieval."
        },
        "operatorOptions": {
          "description": "If set, describes how the property should be used as a search operator.",
          "$ref": "TextOperatorOptions"
        }
      },
      "id": "TextPropertyOptions"
    },
    "SuggestResponse": {
      "id": "SuggestResponse",
      "description": "Response of the suggest API.",
      "type": "object",
      "properties": {
        "suggestResults": {
          "description": "List of suggestions.",
          "type": "array",
          "items": {
            "$ref": "SuggestResult"
          }
        }
      }
    },
    "PeopleSuggestion": {
      "description": "This field contains information about the person being suggested.",
      "type": "object",
      "properties": {
        "person": {
          "description": "Suggested person. All fields of the person object might not be populated.",
          "$ref": "Person"
        }
      },
      "id": "PeopleSuggestion"
    },
    "GmailIntelligentRestrict": {
      "description": "Gmail Intelligent restricts (i.e. smartlabels, important).",
      "type": "object",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "SOCIAL",
            "UPDATES",
            "FORUMS",
            "PROMOTIONS",
            "IMPORTANT",
            "FLIGHT_RESERVATION",
            "LODGING_RESERVATION",
            "CAR_RESERVATION",
            "BUS_RESERVATION"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "category:social",
            "category:updates",
            "category:forums",
            "category:promotions",
            "is:important",
            "label:^cob_sm_flightreservation",
            "label:^cob_sm_lodgingreservation",
            "label:^cob_sm_rentalcarreservation",
            "label:^cob_sm_busreservation"
          ]
        }
      },
      "id": "GmailIntelligentRestrict"
    },
    "IndexItemRequest": {
      "type": "object",
      "properties": {
        "mode": {
          "enum": [
            "UNSPECIFIED",
            "SYNCHRONOUS",
            "ASYNCHRONOUS"
          ],
          "description": "Required. The RequestMode for this request.",
          "type": "string",
          "enumDescriptions": [
            "Priority is not specified in the update request.\nLeaving priority unspecified results in an update failure.",
            "For real-time updates.",
            "For changes that are executed after the response is sent back to the\ncaller."
          ]
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        },
        "item": {
          "$ref": "Item",
          "description": "Name of the item.  Format:\ndatasources/{source_id}/items/{item_id}"
        },
        "connectorName": {
          "description": "Name of connector making this call.\n\u003cbr /\u003eFormat: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "indexItemOptions": {
          "$ref": "IndexItemOptions"
        }
      },
      "id": "IndexItemRequest"
    },
    "QueryInterpretationOptions": {
      "properties": {
        "disableNlInterpretation": {
          "description": "Flag to disable natural language (NL) interpretation of queries. Default is\nfalse, Set to true to disable natural language interpretation. NL\ninterpretation only applies to predefined datasources.",
          "type": "boolean"
        }
      },
      "id": "QueryInterpretationOptions",
      "description": "Options to interpret user query.",
      "type": "object"
    },
    "Snippet": {
      "properties": {
        "snippet": {
          "description": "The snippet of the document.\nThe snippet of the document. May contain escaped HTML character that\nshould be unescaped prior to rendering.",
          "type": "string"
        },
        "matchRanges": {
          "description": "The matched ranges in the snippet.",
          "type": "array",
          "items": {
            "$ref": "MatchRange"
          }
        }
      },
      "id": "Snippet",
      "description": "Snippet of the search result, which summarizes the content of the resulting\npage.",
      "type": "object"
    }
  },
  "protocol": "rest",
  "canonicalName": "Cloud Search",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud_search.debug": {
          "description": "New Service: https://www.googleapis.com/auth/cloud_search.debug"
        },
        "https://www.googleapis.com/auth/cloud_search.settings.indexing": {
          "description": "New Service: https://www.googleapis.com/auth/cloud_search.settings.indexing"
        },
        "https://www.googleapis.com/auth/cloud_search.indexing": {
          "description": "New Service: https://www.googleapis.com/auth/cloud_search.indexing"
        },
        "https://www.googleapis.com/auth/cloud_search.stats.indexing": {
          "description": "New Service: https://www.googleapis.com/auth/cloud_search.stats.indexing"
        },
        "https://www.googleapis.com/auth/cloud_search.settings.query": {
          "description": "New Service: https://www.googleapis.com/auth/cloud_search.settings.query"
        },
        "https://www.googleapis.com/auth/cloud_search.stats": {
          "description": "New Service: https://www.googleapis.com/auth/cloud_search.stats"
        },
        "https://www.googleapis.com/auth/cloud_search": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.query": {
          "description": "Search your organization's data in the Cloud Search index"
        },
        "https://www.googleapis.com/auth/cloud_search.settings": {
          "description": "New Service: https://www.googleapis.com/auth/cloud_search.settings"
        }
      }
    }
  },
  "rootUrl": "https://cloudsearch.googleapis.com/",
  "ownerDomain": "google.com",
  "name": "cloudsearch",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "title": "Cloud Search API",
  "ownerName": "Google",
  "resources": {
    "indexing": {
      "resources": {
        "datasources": {
          "resources": {
            "items": {
              "methods": {
                "deleteQueueItems": {
                  "id": "cloudsearch.indexing.datasources.items.deleteQueueItems",
                  "path": "v1/indexing/{+name}/items:deleteQueueItems",
                  "description": "Deletes all items in a queue. This method is useful for deleting stale\nitems.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:deleteQueueItems"
                },
                "get": {
                  "description": "Gets Item resource by item name.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                  "path": "v1/indexing/{+name}",
                  "id": "cloudsearch.indexing.datasources.items.get"
                },
                "unreserve": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:unreserve",
                  "id": "cloudsearch.indexing.datasources.items.unreserve",
                  "path": "v1/indexing/{+name}/items:unreserve",
                  "description": "Unreserves all items from a queue, making them all eligible to be\npolled.  This method is useful for resetting the indexing queue\nafter a connector has been restarted."
                },
                "index": {
                  "path": "v1/indexing/{+name}:index",
                  "id": "cloudsearch.indexing.datasources.items.index",
                  "description": "Updates Item ACL, metadata, and\ncontent. It will insert the Item if it\ndoes not exist.\nThis method does not support partial updates.  Fields with no provided\nvalues are cleared out in the Cloud Search index.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:index"
                },
                "poll": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:poll",
                  "path": "v1/indexing/{+name}/items:poll",
                  "id": "cloudsearch.indexing.datasources.items.poll",
                  "description": "Polls for unreserved items from the indexing queue and marks a\nset as reserved, starting with items that have\nthe oldest timestamp from the highest priority\nItemStatus.\nThe priority order is as follows: \u003cbr /\u003e\nERROR\n\u003cbr /\u003e\nMODIFIED\n\u003cbr /\u003e\nNEW_ITEM\n\u003cbr /\u003e\nACCEPTED\n\u003cbr /\u003e\nReserving items ensures that polling from other threads\ncannot create overlapping sets.\n\nAfter handling the reserved items, the c[...]"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                  "path": "v1/indexing/{+name}",
                  "id": "cloudsearch.indexing.datasources.items.delete",
                  "description": "Deletes Item resource for the\nspecified resource name."
                },
                "push": {
                  "path": "v1/indexing/{+name}:push",
                  "id": "cloudsearch.indexing.datasources.items.push",
                  "description": "Pushes an item onto a queue for later polling and updating.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:push"
                },
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items",
                  "id": "cloudsearch.indexing.datasources.items.list",
                  "path": "v1/indexing/{+name}/items",
                  "description": "Lists all or a subset of Item resources."
                },
                "upload": {
                  "description": "Creates an upload session for uploading item content. For items smaller\nthan 100 KiB, it's easier to embed the content\ninline within\nupdate.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:upload",
                  "path": "v1/indexing/{+name}:upload",
                  "id": "cloudsearch.indexing.datasources.items.upload"
                }
              }
            }
          },
          "methods": {
            "getSchema": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "id": "cloudsearch.indexing.datasources.getSchema",
              "path": "v1/indexing/{+name}/schema",
              "description": "Gets the schema of a data source."
            },
            "updateSchema": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "path": "v1/indexing/{+name}/schema",
              "id": "cloudsearch.indexing.datasources.updateSchema",
              "description": "Updates the schema of a data source.",
              "httpMethod": "PUT"
            },
            "deleteSchema": {
              "description": "Deletes the schema of a data source.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "path": "v1/indexing/{+name}/schema",
              "id": "cloudsearch.indexing.datasources.deleteSchema"
            }
          }
        }
      }
    },
    "operations": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.debug",
            "https://www.googleapis.com/auth/cloud_search.indexing",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing",
            "https://www.googleapis.com/auth/cloud_search.settings.query"
          ],
          "flatPath": "v1/operations/{operationsId}",
          "id": "cloudsearch.operations.get",
          "path": "v1/{+name}",
          "description": "Gets the latest state of a long-running operation.  Clients can use this\nmethod to poll the operation result at intervals as recommended by the API\nservice."
        }
      }
    },
    "query": {
      "methods": {
        "suggest": {
          "flatPath": "v1/query/suggest",
          "path": "v1/query/suggest",
          "id": "cloudsearch.query.suggest",
          "description": "Provides suggestions for autocompleting the query.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ]
        },
        "search": {
          "path": "v1/query/search",
          "id": "cloudsearch.query.search",
          "description": "The Cloud Search Query API provides the search method, which returns\nthe most relevant results from a user query.  The results can come from\nG Suite Apps, such as Gmail or Google Drive, or they can come from data\nthat you have indexed from a third party.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ],
          "flatPath": "v1/query/search"
        }
      },
      "resources": {
        "sources": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.query"
              ],
              "flatPath": "v1/query/sources",
              "path": "v1/query/sources",
              "id": "cloudsearch.query.sources.list",
              "description": "Returns list of sources that user can use for Search and Suggest APIs."
            }
          }
        }
      }
    },
    "debug": {
      "resources": {
        "datasources": {
          "resources": {
            "items": {
              "resources": {
                "unmappedids": {
                  "methods": {
                    "list": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud_search",
                        "https://www.googleapis.com/auth/cloud_search.debug"
                      ],
                      "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}/unmappedids",
                      "path": "v1/debug/{+parent}/unmappedids",
                      "id": "cloudsearch.debug.datasources.items.unmappedids.list",
                      "description": "List all unmapped identities for a specific item."
                    }
                  }
                }
              },
              "methods": {
                "searchByViewUrl": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "flatPath": "v1/debug/datasources/{datasourcesId}/items:searchByViewUrl",
                  "path": "v1/debug/{+name}/items:searchByViewUrl",
                  "id": "cloudsearch.debug.datasources.items.searchByViewUrl",
                  "description": "Fetches the item whose viewUrl exactly matches that of the URL provided\nin the request."
                },
                "checkAccess": {
                  "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}:checkAccess",
                  "id": "cloudsearch.debug.datasources.items.checkAccess",
                  "path": "v1/debug/{+name}:checkAccess",
                  "description": "Checks whether an item is accessible by specified principal.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ]
                }
              }
            }
          }
        },
        "identitysources": {
          "resources": {
            "unmappedids": {
              "methods": {
                "list": {
                  "description": "Lists unmapped user identities for an identity source.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "flatPath": "v1/debug/identitysources/{identitysourcesId}/unmappedids",
                  "path": "v1/debug/{+parent}/unmappedids",
                  "id": "cloudsearch.debug.identitysources.unmappedids.list"
                }
              }
            },
            "items": {
              "methods": {
                "listForunmappedidentity": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "flatPath": "v1/debug/identitysources/{identitysourcesId}/items:forunmappedidentity",
                  "path": "v1/debug/{+parent}/items:forunmappedidentity",
                  "id": "cloudsearch.debug.identitysources.items.listForunmappedidentity",
                  "description": "Lists names of items associated with an unmapped identity.",
                  "httpMethod": "GET"
                }
              }
            }
          }
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "flatPath": "v1/media/{mediaId}",
          "path": "v1/media/{+resourceName}",
          "description": "Uploads media for indexing.\n\nThe upload endpoint supports direct and resumable upload protocols and\nis intended for large items that can not be inlined during index requests. To\nindex large content:\n\n1. Call upload to begin\n   a session and get the item reference.\n1. Upload the content using the item reference's resource name.\n1. Call index with the item\n   reference as the content.\n\nFor additional information, see\n[Create a content connector using the REST[...]",
          "supportsMediaUpload": true,
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.indexing"
          ],
          "id": "cloudsearch.media.upload"
        }
      }
    },
    "stats": {
      "methods": {
        "getIndex": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "flatPath": "v1/stats/index",
          "id": "cloudsearch.stats.getIndex",
          "path": "v1/stats/index",
          "description": "Gets indexed item statistics aggreggated across all data sources. This\nAPI only returns statistics for previous dates; it doesn't return\nstatistics for the current day."
        }
      },
      "resources": {
        "index": {
          "resources": {
            "datasources": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "flatPath": "v1/stats/index/datasources/{datasourcesId}",
                  "path": "v1/stats/index/{+name}",
                  "id": "cloudsearch.stats.index.datasources.get",
                  "description": "Gets indexed item statistics for a single data source."
                }
              }
            }
          }
        }
      }
    },
    "settings": {
      "resources": {
        "datasources": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "path": "v1/settings/{+name}",
              "id": "cloudsearch.settings.datasources.get",
              "description": "Gets a datasource."
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/settings/datasources",
              "path": "v1/settings/datasources",
              "id": "cloudsearch.settings.datasources.list",
              "description": "Lists datasources."
            },
            "update": {
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "path": "v1/settings/{+name}",
              "id": "cloudsearch.settings.datasources.update",
              "description": "Updates a datasource."
            },
            "create": {
              "description": "Creates a datasource.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/settings/datasources",
              "path": "v1/settings/datasources",
              "id": "cloudsearch.settings.datasources.create"
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "id": "cloudsearch.settings.datasources.delete",
              "path": "v1/settings/{+name}",
              "description": "Deletes a datasource."
            }
          }
        },
        "searchapplications": {
          "methods": {
            "reset": {
              "description": "Resets a search application to default settings. This will return an empty\nresponse.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}:reset",
              "path": "v1/settings/{+name}:reset",
              "id": "cloudsearch.settings.searchapplications.reset"
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "flatPath": "v1/settings/searchapplications",
              "path": "v1/settings/searchapplications",
              "id": "cloudsearch.settings.searchapplications.list",
              "description": "Lists all search applications."
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "flatPath": "v1/settings/searchapplications",
              "path": "v1/settings/searchapplications",
              "id": "cloudsearch.settings.searchapplications.create",
              "description": "Creates a search application.",
              "httpMethod": "POST"
            },
            "get": {
              "description": "Gets the specified search application.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "path": "v1/settings/{+name}",
              "id": "cloudsearch.settings.searchapplications.get"
            },
            "update": {
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "path": "v1/settings/{+name}",
              "id": "cloudsearch.settings.searchapplications.update",
              "description": "Updates a search application."
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "path": "v1/settings/{+name}",
              "id": "cloudsearch.settings.searchapplications.delete",
              "description": "Deletes a search application."
            }
          }
        }
      }
    }
  },
  "version": "v1",
  "baseUrl": "https://cloudsearch.googleapis.com/",
  "servicePath": "",
  "description": "Cloud Search provides cloud-based search capabilities over G Suite data.  The Cloud Search API allows indexing of non-G Suite data into Cloud Search.",
  "kind": "discovery#restDescription"
}
