{
  "batchPath": "batch",
  "id": "genomics:v1",
  "documentationLink": "https://cloud.google.com/genomics",
  "revision": "20181127",
  "fullyEncodeReservedExpansion": true,
  "title": "Genomics API",
  "ownerName": "Google",
  "discoveryVersion": "v1",
  "resources": {
    "annotationsets": {
      "methods": {
        "get": {
          "flatPath": "v1/annotationsets/{annotationSetId}",
          "id": "genomics.annotationsets.get",
          "path": "v1/annotationsets/{annotationSetId}",
          "description": "Gets an annotation set. Caller must have READ permission for\nthe associated dataset.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics",
            "https://www.googleapis.com/auth/genomics.readonly"
          ]
        },
        "update": {
          "flatPath": "v1/annotationsets/{annotationSetId}",
          "path": "v1/annotationsets/{annotationSetId}",
          "id": "genomics.annotationsets.update",
          "description": "Updates an annotation set. The update must respect all mutability\nrestrictions and other invariants described on the annotation set resource.\nCaller must have WRITE permission for the associated dataset.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ]
        },
        "create": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/annotationsets",
          "path": "v1/annotationsets",
          "id": "genomics.annotationsets.create",
          "description": "Creates a new annotation set. Caller must have WRITE permission for the\nassociated dataset.\n\nThe following fields are required:\n\n  * datasetId\n  * referenceSetId\n\nAll other fields may be optionally specified, unless documented as being\nserver-generated (for example, the `id` field)."
        },
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/annotationsets/{annotationSetId}",
          "path": "v1/annotationsets/{annotationSetId}",
          "id": "genomics.annotationsets.delete",
          "description": "Deletes an annotation set. Caller must have WRITE permission\nfor the associated annotation set."
        },
        "search": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics",
            "https://www.googleapis.com/auth/genomics.readonly"
          ],
          "flatPath": "v1/annotationsets/search",
          "path": "v1/annotationsets/search",
          "id": "genomics.annotationsets.search",
          "description": "Searches for annotation sets that match the given criteria. Annotation sets\nare returned in an unspecified order. This order is consistent, such that\ntwo queries for the same content (regardless of page size) yield annotation\nsets in the same order across their respective streams of paginated\nresponses. Caller must have READ permission for the queried datasets."
        }
      }
    },
    "variants": {
      "methods": {
        "get": {
          "description": "Gets a variant by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics",
            "https://www.googleapis.com/auth/genomics.readonly"
          ],
          "flatPath": "v1/variants/{variantId}",
          "id": "genomics.variants.get",
          "path": "v1/variants/{variantId}"
        },
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/variants/{variantId}",
          "path": "v1/variants/{variantId}",
          "id": "genomics.variants.patch",
          "description": "Updates a variant.\n\nThis method supports patch semantics. Returns the modified variant without\nits calls."
        },
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/variants/{variantId}",
          "path": "v1/variants/{variantId}",
          "id": "genomics.variants.delete",
          "description": "Deletes a variant."
        },
        "import": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/devstorage.read_write",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/variants:import",
          "id": "genomics.variants.import",
          "path": "v1/variants:import",
          "description": "Creates variant data by asynchronously importing the provided information.\n\nThe variants for import will be merged with any existing variant that\nmatches its reference sequence, start, end, reference bases, and\nalternative bases. If no such variant exists, a new one will be created.\n\nWhen variants are merged, the call information from the new variant\nis added to the existing variant, and Variant info fields are merged\nas specified in\ninfoMergeConfig.\nAs a spec[...]"
        },
        "merge": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/variants:merge",
          "path": "v1/variants:merge",
          "id": "genomics.variants.merge",
          "description": "Merges the given variants with existing variants.\n\nEach variant will be\nmerged with an existing variant that matches its reference sequence,\nstart, end, reference bases, and alternative bases. If no such variant\nexists, a new one will be created.\n\nWhen variants are merged, the call information from the new variant\nis added to the existing variant. Variant info fields are merged as\nspecified in the\ninfoMergeConfig\nfield of the MergeVariantsRequest.\n\nPlease e[...]"
        },
        "create": {
          "flatPath": "v1/variants",
          "path": "v1/variants",
          "id": "genomics.variants.create",
          "description": "Creates a new variant.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ]
        },
        "search": {
          "flatPath": "v1/variants/search",
          "id": "genomics.variants.search",
          "path": "v1/variants/search",
          "description": "Gets a list of variants matching the criteria.\n\nImplements\n[GlobalAllianceApi.searchVariants](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/variantmethods.avdl#L126).",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics",
            "https://www.googleapis.com/auth/genomics.readonly"
          ]
        }
      }
    },
    "references": {
      "methods": {
        "get": {
          "flatPath": "v1/references/{referenceId}",
          "id": "genomics.references.get",
          "path": "v1/references/{referenceId}",
          "description": "Gets a reference.\n\nImplements\n[GlobalAllianceApi.getReference](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/referencemethods.avdl#L158).",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics",
            "https://www.googleapis.com/auth/genomics.readonly"
          ]
        },
        "search": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics",
            "https://www.googleapis.com/auth/genomics.readonly"
          ],
          "flatPath": "v1/references/search",
          "id": "genomics.references.search",
          "path": "v1/references/search",
          "description": "Searches for references which match the given criteria.\n\nImplements\n[GlobalAllianceApi.searchReferences](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/referencemethods.avdl#L146)."
        }
      },
      "resources": {
        "bases": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/genomics",
                "https://www.googleapis.com/auth/genomics.readonly"
              ],
              "flatPath": "v1/references/{referenceId}/bases",
              "path": "v1/references/{referenceId}/bases",
              "id": "genomics.references.bases.list",
              "description": "Lists the bases in a reference, optionally restricted to a range.\n\nImplements\n[GlobalAllianceApi.getReferenceBases](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/referencemethods.avdl#L221)."
            }
          }
        }
      }
    },
    "datasets": {
      "methods": {
        "list": {
          "flatPath": "v1/datasets",
          "path": "v1/datasets",
          "id": "genomics.datasets.list",
          "description": "Lists datasets within a project.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics",
            "https://www.googleapis.com/auth/genomics.readonly"
          ]
        },
        "setIamPolicy": {
          "flatPath": "v1/datasets/{datasetsId}:setIamPolicy",
          "path": "v1/{+resource}:setIamPolicy",
          "id": "genomics.datasets.setIamPolicy",
          "description": "Sets the access control policy on the specified dataset. Replaces any\nexisting policy.\n\nSee \u003ca href=\"/iam/docs/managing-policies#setting_a_policy\"\u003eSetting a\nPolicy\u003c/a\u003e for more information.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ]
        },
        "create": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/datasets",
          "id": "genomics.datasets.create",
          "path": "v1/datasets",
          "description": "Creates a new dataset."
        },
        "getIamPolicy": {
          "flatPath": "v1/datasets/{datasetsId}:getIamPolicy",
          "path": "v1/{+resource}:getIamPolicy",
          "id": "genomics.datasets.getIamPolicy",
          "description": "Gets the access control policy for the dataset. This is empty if the\npolicy or resource does not exist.\n\nSee \u003ca href=\"/iam/docs/managing-policies#getting_a_policy\"\u003eGetting a\nPolicy\u003c/a\u003e for more information.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ]
        },
        "patch": {
          "description": "Updates a dataset.\n\nThis method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/datasets/{datasetId}",
          "path": "v1/datasets/{datasetId}",
          "id": "genomics.datasets.patch"
        },
        "get": {
          "description": "Gets a dataset by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics",
            "https://www.googleapis.com/auth/genomics.readonly"
          ],
          "flatPath": "v1/datasets/{datasetId}",
          "path": "v1/datasets/{datasetId}",
          "id": "genomics.datasets.get"
        },
        "undelete": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/datasets/{datasetId}:undelete",
          "path": "v1/datasets/{datasetId}:undelete",
          "id": "genomics.datasets.undelete",
          "description": "Undeletes a dataset by restoring a dataset which was deleted via this API.\n\nThis operation is only possible for a week after the deletion occurred."
        },
        "testIamPermissions": {
          "flatPath": "v1/datasets/{datasetsId}:testIamPermissions",
          "path": "v1/{+resource}:testIamPermissions",
          "id": "genomics.datasets.testIamPermissions",
          "description": "Returns permissions that a caller has on the specified resource.\nSee \u003ca href=\"/iam/docs/managing-policies#testing_permissions\"\u003eTesting\nPermissions\u003c/a\u003e for more information.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ]
        },
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/datasets/{datasetId}",
          "path": "v1/datasets/{datasetId}",
          "id": "genomics.datasets.delete",
          "description": "Deletes a dataset and all of its contents (all read group sets,\nreference sets, variant sets, call sets, annotation sets, etc.)\nThis is reversible (up to one week after the deletion) via\nthe\ndatasets.undelete\noperation."
        }
      }
    },
    "variantsets": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/variantsets/{variantSetId}",
          "id": "genomics.variantsets.delete",
          "path": "v1/variantsets/{variantSetId}",
          "description": "Deletes a variant set including all variants, call sets, and calls within.\nThis is not reversible."
        },
        "create": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/variantsets",
          "path": "v1/variantsets",
          "id": "genomics.variantsets.create",
          "description": "Creates a new variant set.\n\nThe provided variant set must have a valid `datasetId` set - all other\nfields are optional. Note that the `id` field will be ignored, as this is\nassigned by the server."
        },
        "export": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/bigquery",
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/variantsets/{variantSetId}:export",
          "path": "v1/variantsets/{variantSetId}:export",
          "id": "genomics.variantsets.export",
          "description": "Exports variant set data to an external destination."
        },
        "search": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics",
            "https://www.googleapis.com/auth/genomics.readonly"
          ],
          "flatPath": "v1/variantsets/search",
          "id": "genomics.variantsets.search",
          "path": "v1/variantsets/search",
          "description": "Returns a list of all variant sets matching search criteria.\n\nImplements\n[GlobalAllianceApi.searchVariantSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/variantmethods.avdl#L49)."
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics",
            "https://www.googleapis.com/auth/genomics.readonly"
          ],
          "flatPath": "v1/variantsets/{variantSetId}",
          "id": "genomics.variantsets.get",
          "path": "v1/variantsets/{variantSetId}",
          "description": "Gets a variant set by ID."
        },
        "patch": {
          "description": "Updates a variant set using patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/variantsets/{variantSetId}",
          "path": "v1/variantsets/{variantSetId}",
          "id": "genomics.variantsets.patch"
        }
      }
    },
    "annotations": {
      "methods": {
        "create": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/annotations",
          "id": "genomics.annotations.create",
          "path": "v1/annotations",
          "description": "Creates a new annotation. Caller must have WRITE permission\nfor the associated annotation set.\n\nThe following fields are required:\n\n* annotationSetId\n* referenceName or\n  referenceId\n\n### Transcripts\n\nFor annotations of type TRANSCRIPT, the following fields of\ntranscript must be provided:\n\n* exons.start\n* exons.end\n\nAll other fields may be optionally specified, unless documented as being\nserver-generated (for example, the `id` field). The annotated\nra[...]"
        },
        "batchCreate": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/annotations:batchCreate",
          "path": "v1/annotations:batchCreate",
          "id": "genomics.annotations.batchCreate",
          "description": "Creates one or more new annotations atomically. All annotations must\nbelong to the same annotation set. Caller must have WRITE\npermission for this annotation set. For optimal performance, batch\npositionally adjacent annotations together.\n\nIf the request has a systemic issue, such as an attempt to write to\nan inaccessible annotation set, the entire RPC will fail accordingly. For\nlesser data issues, when possible an error will be isolated to the\ncorresponding batc[...]"
        },
        "search": {
          "flatPath": "v1/annotations/search",
          "id": "genomics.annotations.search",
          "path": "v1/annotations/search",
          "description": "Searches for annotations that match the given criteria. Results are\nordered by genomic coordinate (by reference sequence, then position).\nAnnotations with equivalent genomic coordinates are returned in an\nunspecified order. This order is consistent, such that two queries for the\nsame content (regardless of page size) yield annotations in the same order\nacross their respective streams of paginated responses. Caller must have\nREAD permission for the queried annotati[...]",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics",
            "https://www.googleapis.com/auth/genomics.readonly"
          ]
        },
        "get": {
          "flatPath": "v1/annotations/{annotationId}",
          "path": "v1/annotations/{annotationId}",
          "id": "genomics.annotations.get",
          "description": "Gets an annotation. Caller must have READ permission\nfor the associated annotation set.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics",
            "https://www.googleapis.com/auth/genomics.readonly"
          ]
        },
        "update": {
          "description": "Updates an annotation. Caller must have\nWRITE permission for the associated dataset.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/annotations/{annotationId}",
          "id": "genomics.annotations.update",
          "path": "v1/annotations/{annotationId}"
        },
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/annotations/{annotationId}",
          "id": "genomics.annotations.delete",
          "path": "v1/annotations/{annotationId}",
          "description": "Deletes an annotation. Caller must have WRITE permission for\nthe associated annotation set."
        }
      }
    },
    "operations": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/operations",
          "path": "v1/{+name}",
          "id": "genomics.operations.list",
          "description": "Lists operations that match the specified filter in the request.\nAuthorization requires the following [Google IAM](https://cloud.google.com/iam) permission&#58;\n\n* `genomics.operations.list`"
        },
        "get": {
          "flatPath": "v1/operations/{operationsId}",
          "path": "v1/{+name}",
          "id": "genomics.operations.get",
          "description": "Gets the latest state of a long-running operation.\nClients can use this method to poll the operation result at intervals as\nrecommended by the API service.\nAuthorization requires the following [Google IAM](https://cloud.google.com/iam) permission&#58;\n\n* `genomics.operations.get`",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ]
        },
        "cancel": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/operations/{operationsId}:cancel",
          "path": "v1/{+name}:cancel",
          "id": "genomics.operations.cancel",
          "description": "Starts asynchronous cancellation on a long-running operation.\nThe server makes a best effort to cancel the operation, but success is not\nguaranteed. Clients may use Operations.GetOperation\nor Operations.ListOperations\nto check whether the cancellation succeeded or the operation completed\ndespite cancellation.\nAuthorization requires the following [Google IAM](https://cloud.google.com/iam) permission&#58;\n\n* `genomics.operations.cancel`"
        }
      }
    },
    "referencesets": {
      "methods": {
        "search": {
          "flatPath": "v1/referencesets/search",
          "id": "genomics.referencesets.search",
          "path": "v1/referencesets/search",
          "description": "Searches for reference sets which match the given criteria.\n\nImplements\n[GlobalAllianceApi.searchReferenceSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/referencemethods.avdl#L71)",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics",
            "https://www.googleapis.com/auth/genomics.readonly"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics",
            "https://www.googleapis.com/auth/genomics.readonly"
          ],
          "flatPath": "v1/referencesets/{referenceSetId}",
          "id": "genomics.referencesets.get",
          "path": "v1/referencesets/{referenceSetId}",
          "description": "Gets a reference set.\n\nImplements\n[GlobalAllianceApi.getReferenceSet](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/referencemethods.avdl#L83)."
        }
      }
    },
    "readgroupsets": {
      "methods": {
        "export": {
          "description": "Exports a read group set to a BAM file in Google Cloud Storage.\n\nNote that currently there may be some differences between exported BAM\nfiles and the original BAM file at the time of import. See\nImportReadGroupSets\nfor caveats.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/devstorage.read_write",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/readgroupsets/{readGroupSetId}:export",
          "path": "v1/readgroupsets/{readGroupSetId}:export",
          "id": "genomics.readgroupsets.export"
        },
        "search": {
          "description": "Searches for read group sets matching the criteria.\n\nImplements\n[GlobalAllianceApi.searchReadGroupSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/readmethods.avdl#L135).",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics",
            "https://www.googleapis.com/auth/genomics.readonly"
          ],
          "flatPath": "v1/readgroupsets/search",
          "path": "v1/readgroupsets/search",
          "id": "genomics.readgroupsets.search"
        },
        "get": {
          "flatPath": "v1/readgroupsets/{readGroupSetId}",
          "path": "v1/readgroupsets/{readGroupSetId}",
          "id": "genomics.readgroupsets.get",
          "description": "Gets a read group set by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics",
            "https://www.googleapis.com/auth/genomics.readonly"
          ]
        },
        "patch": {
          "description": "Updates a read group set.\n\nThis method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/readgroupsets/{readGroupSetId}",
          "path": "v1/readgroupsets/{readGroupSetId}",
          "id": "genomics.readgroupsets.patch"
        },
        "import": {
          "description": "Creates read group sets by asynchronously importing the provided\ninformation.\n\nThe caller must have WRITE permissions to the dataset.\n\n## Notes on [BAM](https://samtools.github.io/hts-specs/SAMv1.pdf) import\n\n- Tags will be converted to strings - tag types are not preserved\n- Comments (`@CO`) in the input file header will not be preserved\n- Original header order of references (`@SQ`) will not be preserved\n- Any reverse stranded unmapped reads will be reverse c[...]",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/devstorage.read_write",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/readgroupsets:import",
          "path": "v1/readgroupsets:import",
          "id": "genomics.readgroupsets.import"
        },
        "delete": {
          "description": "Deletes a read group set.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/readgroupsets/{readGroupSetId}",
          "id": "genomics.readgroupsets.delete",
          "path": "v1/readgroupsets/{readGroupSetId}"
        }
      },
      "resources": {
        "coveragebuckets": {
          "methods": {
            "list": {
              "flatPath": "v1/readgroupsets/{readGroupSetId}/coveragebuckets",
              "path": "v1/readgroupsets/{readGroupSetId}/coveragebuckets",
              "id": "genomics.readgroupsets.coveragebuckets.list",
              "description": "Lists fixed width coverage buckets for a read group set, each of which\ncorrespond to a range of a reference sequence. Each bucket summarizes\ncoverage information across its corresponding genomic range.\n\nCoverage is defined as the number of reads which are aligned to a given\nbase in the reference sequence. Coverage buckets are available at several\nprecomputed bucket widths, enabling retrieval of various coverage 'zoom\nlevels'. The caller must have READ permiss[...]",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/genomics",
                "https://www.googleapis.com/auth/genomics.readonly"
              ]
            }
          }
        }
      }
    },
    "reads": {
      "methods": {
        "search": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics",
            "https://www.googleapis.com/auth/genomics.readonly"
          ],
          "flatPath": "v1/reads/search",
          "id": "genomics.reads.search",
          "path": "v1/reads/search",
          "description": "Gets a list of reads for one or more read group sets.\n\nReads search operates over a genomic coordinate space of reference sequence\n& position defined over the reference sequences to which the requested\nread group sets are aligned.\n\nIf a target positional range is specified, search returns all reads whose\nalignment to the reference genome overlap the range. A query which\nspecifies only read group set IDs yields all reads in those read group\nsets, including unmap[...]"
        }
      }
    },
    "callsets": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/callsets/{callSetId}",
          "id": "genomics.callsets.patch",
          "path": "v1/callsets/{callSetId}",
          "description": "Updates a call set.\n\nThis method supports patch semantics."
        },
        "get": {
          "description": "Gets a call set by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics",
            "https://www.googleapis.com/auth/genomics.readonly"
          ],
          "flatPath": "v1/callsets/{callSetId}",
          "path": "v1/callsets/{callSetId}",
          "id": "genomics.callsets.get"
        },
        "create": {
          "description": "Creates a new call set.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/callsets",
          "path": "v1/callsets",
          "id": "genomics.callsets.create"
        },
        "delete": {
          "description": "Deletes a call set.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics"
          ],
          "flatPath": "v1/callsets/{callSetId}",
          "path": "v1/callsets/{callSetId}",
          "id": "genomics.callsets.delete"
        },
        "search": {
          "description": "Gets a list of call sets matching the criteria.\n\nImplements\n[GlobalAllianceApi.searchCallSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/variantmethods.avdl#L178).",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/genomics",
            "https://www.googleapis.com/auth/genomics.readonly"
          ],
          "flatPath": "v1/callsets/search",
          "path": "v1/callsets/search",
          "id": "genomics.callsets.search"
        }
      }
    }
  },
  "protocol": "rest",
  "version": "v1",
  "baseUrl": "https://genomics.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/bigquery": {
          "description": "View and manage your data in Google BigQuery"
        },
        "https://www.googleapis.com/auth/devstorage.read_write": {
          "description": "Manage your data in Google Cloud Storage"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "View and manage your data across Google Cloud Platform services"
        },
        "https://www.googleapis.com/auth/genomics.readonly": {
          "description": "View Genomics data"
        },
        "https://www.googleapis.com/auth/genomics": {
          "description": "View and manage Genomics data"
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "description": "Uploads, processes, queries, and searches Genomics data in the cloud.",
  "servicePath": "",
  "rootUrl": "https://genomics.googleapis.com/",
  "basePath": "",
  "ownerDomain": "google.com",
  "name": "genomics"
}
