{
  "discoveryVersion": "v1",
  "version_module": true,
  "protocol": "rest",
  "canonicalName": "People Service",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/userinfo.profile": {
          "description": "See your personal info, including any personal info you've made publicly available"
        },
        "https://www.googleapis.com/auth/user.emails.read": {
          "description": "View your email addresses"
        },
        "https://www.googleapis.com/auth/user.addresses.read": {
          "description": "View your street addresses"
        },
        "https://www.googleapis.com/auth/contacts": {
          "description": "See, edit, download, and permanently delete your contacts"
        },
        "https://www.googleapis.com/auth/userinfo.email": {
          "description": "View your email address"
        },
        "https://www.googleapis.com/auth/user.phonenumbers.read": {
          "description": "View your phone numbers"
        },
        "https://www.googleapis.com/auth/contacts.readonly": {
          "description": "See and download your contacts"
        },
        "https://www.googleapis.com/auth/user.birthday.read": {
          "description": "View your complete date of birth"
        }
      }
    }
  },
  "rootUrl": "https://people.googleapis.com/",
  "ownerDomain": "google.com",
  "name": "people",
  "batchPath": "batch",
  "title": "People API",
  "ownerName": "Google",
  "resources": {
    "people": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly",
            "https://www.googleapis.com/auth/user.addresses.read",
            "https://www.googleapis.com/auth/user.birthday.read",
            "https://www.googleapis.com/auth/user.emails.read",
            "https://www.googleapis.com/auth/user.phonenumbers.read",
            "https://www.googleapis.com/auth/userinfo.email",
            "https://www.googleapis.com/auth/userinfo.profile"
          ],
          "flatPath": "v1/people/{peopleId}",
          "path": "v1/{+resourceName}",
          "id": "people.people.get",
          "description": "Provides information about a person by specifying a resource name. Use\n`people/me` to indicate the authenticated user.\n\u003cbr\u003e\nThe request throws a 400 error if 'personFields' is not specified."
        },
        "deleteContact": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "flatPath": "v1/people/{peopleId}:deleteContact",
          "path": "v1/{+resourceName}:deleteContact",
          "id": "people.people.deleteContact",
          "description": "Delete a contact person. Any non-contact data will not be deleted."
        },
        "getBatchGet": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly",
            "https://www.googleapis.com/auth/user.addresses.read",
            "https://www.googleapis.com/auth/user.birthday.read",
            "https://www.googleapis.com/auth/user.emails.read",
            "https://www.googleapis.com/auth/user.phonenumbers.read",
            "https://www.googleapis.com/auth/userinfo.email",
            "https://www.googleapis.com/auth/userinfo.profile"
          ],
          "flatPath": "v1/people:batchGet",
          "id": "people.people.getBatchGet",
          "path": "v1/people:batchGet",
          "description": "Provides information about a list of specific people by specifying a list\nof requested resource names. Use `people/me` to indicate the authenticated\nuser.\n\u003cbr\u003e\nThe request throws a 400 error if 'personFields' is not specified."
        },
        "updateContactPhoto": {
          "flatPath": "v1/people/{peopleId}:updateContactPhoto",
          "id": "people.people.updateContactPhoto",
          "path": "v1/{+resourceName}:updateContactPhoto",
          "description": "Update a contact's photo.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ]
        },
        "deleteContactPhoto": {
          "description": "Delete a contact's photo.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "flatPath": "v1/people/{peopleId}:deleteContactPhoto",
          "path": "v1/{+resourceName}:deleteContactPhoto",
          "id": "people.people.deleteContactPhoto"
        },
        "updateContact": {
          "flatPath": "v1/people/{peopleId}:updateContact",
          "path": "v1/{+resourceName}:updateContact",
          "id": "people.people.updateContact",
          "description": "Update contact data for an existing contact person. Any non-contact data\nwill not be modified.\n\nThe request throws a 400 error if `updatePersonFields` is not specified.\n\u003cbr\u003e\nThe request throws a 400 error if `person.metadata.sources` is not\nspecified for the contact to be updated.\n\u003cbr\u003e\nThe request throws a 400 error with an error with reason\n`\"failedPrecondition\"` if `person.metadata.sources.etag` is different than\nthe contact's etag, whi[...]",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ]
        },
        "createContact": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "flatPath": "v1/people:createContact",
          "id": "people.people.createContact",
          "path": "v1/people:createContact",
          "description": "Create a new contact and return the person resource for that contact."
        }
      },
      "resources": {
        "connections": {
          "methods": {
            "list": {
              "description": "Provides a list of the authenticated user's contacts merged with any\nconnected profiles.\n\u003cbr\u003e\nThe request throws a 400 error if 'personFields' is not specified.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/contacts",
                "https://www.googleapis.com/auth/contacts.readonly"
              ],
              "flatPath": "v1/people/{peopleId}/connections",
              "path": "v1/{+resourceName}/connections",
              "id": "people.people.connections.list"
            }
          }
        }
      }
    },
    "contactGroups": {
      "methods": {
        "create": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "flatPath": "v1/contactGroups",
          "path": "v1/contactGroups",
          "id": "people.contactGroups.create",
          "description": "Create a new contact group owned by the authenticated user."
        },
        "get": {
          "description": "Get a specific contact group owned by the authenticated user by specifying\na contact group resource name.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly"
          ],
          "flatPath": "v1/contactGroups/{contactGroupsId}",
          "path": "v1/{+resourceName}",
          "id": "people.contactGroups.get"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "flatPath": "v1/contactGroups/{contactGroupsId}",
          "path": "v1/{+resourceName}",
          "id": "people.contactGroups.update",
          "description": "Update the name of an existing contact group owned by the authenticated\nuser.",
          "httpMethod": "PUT"
        },
        "batchGet": {
          "flatPath": "v1/contactGroups:batchGet",
          "id": "people.contactGroups.batchGet",
          "path": "v1/contactGroups:batchGet",
          "description": "Get a list of contact groups owned by the authenticated user by specifying\na list of contact group resource names.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "flatPath": "v1/contactGroups/{contactGroupsId}",
          "path": "v1/{+resourceName}",
          "id": "people.contactGroups.delete",
          "description": "Delete an existing contact group owned by the authenticated user by\nspecifying a contact group resource name.",
          "httpMethod": "DELETE"
        },
        "list": {
          "id": "people.contactGroups.list",
          "path": "v1/contactGroups",
          "description": "List all contact groups owned by the authenticated user. Members of the\ncontact groups are not populated.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly"
          ],
          "flatPath": "v1/contactGroups"
        }
      },
      "resources": {
        "members": {
          "methods": {
            "modify": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/contacts"
              ],
              "flatPath": "v1/contactGroups/{contactGroupsId}/members:modify",
              "path": "v1/{+resourceName}/members:modify",
              "id": "people.contactGroups.members.modify",
              "description": "Modify the members of a contact group owned by the authenticated user.\n\u003cbr\u003e\nThe only system contact groups that can have members added are\n`contactGroups/myContacts` and `contactGroups/starred`. Other system\ncontact groups are deprecated and can only have contacts removed."
            }
          }
        }
      }
    }
  },
  "version": "v1",
  "baseUrl": "https://people.googleapis.com/",
  "servicePath": "",
  "description": "Provides access to information about profiles and contacts.",
  "kind": "discovery#restDescription",
  "basePath": "",
  "id": "people:v1",
  "documentationLink": "https://developers.google.com/people/",
  "revision": "20191031"
}
