{
  "version": "v1",
  "baseUrl": "https://photoslibrary.googleapis.com/",
  "kind": "discovery#restDescription",
  "description": "Manage photos, videos, and albums in Google Photos\n",
  "servicePath": "",
  "basePath": "",
  "revision": "20180508",
  "documentationLink": "https://developers.google.com/photos/",
  "id": "photoslibrary:v1",
  "discoveryVersion": "v1",
  "version_module": true,
  "protocol": "rest",
  "canonicalName": "Photos Library",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/photoslibrary.sharing": {
          "description": "Manage and add to shared albums on your behalf"
        },
        "https://www.googleapis.com/auth/photoslibrary": {
          "description": "View and manage your Google Photos library"
        },
        "https://www.googleapis.com/auth/photoslibrary.readonly": {
          "description": "View your Google Photos library"
        },
        "https://www.googleapis.com/auth/photoslibrary.appendonly": {
          "description": "Add to your Google Photos library"
        },
        "https://www.googleapis.com/auth/drive.photos.readonly": {
          "description": "View the photos, videos and albums in your Google Photos"
        },
        "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata": {
          "description": "Manage photos added by this app"
        }
      }
    }
  },
  "rootUrl": "https://photoslibrary.googleapis.com/",
  "ownerDomain": "google.com",
  "name": "photoslibrary",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "title": "Photos Library API",
  "ownerName": "Google",
  "resources": {
    "mediaItems": {
      "methods": {
        "batchCreate": {
          "description": "Creates one or more media items in a user's Google Photos library.\nIf an album id is specified, the media item(s) are also added to the album.\nBy default the media item(s) will be added to the end of the library or\nalbum.\n\nIf an album id and position are both defined, then the media items will\nbe added to the album at the specified position.\n\nIf multiple media items are given, they will be inserted at the specified\nposition.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.appendonly",
            "https://www.googleapis.com/auth/photoslibrary.sharing"
          ],
          "flatPath": "v1/mediaItems:batchCreate",
          "path": "v1/mediaItems:batchCreate",
          "id": "photoslibrary.mediaItems.batchCreate"
        },
        "search": {
          "path": "v1/mediaItems:search",
          "id": "photoslibrary.mediaItems.search",
          "description": "Searches for media items in a user's Google Photos library.\nIf no filters are set, then all media items in the user's library will be\nreturned.\n\nIf an album is set, all media items in the specified album will be\nreturned.\n\nIf filters are specified, anything that matches the filters from the user's\nlibrary will be listed.\n\nIf an album and filters are set, then this will result in an error.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.readonly",
            "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
          ],
          "flatPath": "v1/mediaItems:search"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.readonly",
            "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
          ],
          "flatPath": "v1/mediaItems/{mediaItemsId}",
          "path": "v1/mediaItems/{+mediaItemId}",
          "id": "photoslibrary.mediaItems.get",
          "description": "Returns the media item specified based on a given media item id."
        }
      }
    },
    "sharedAlbums": {
      "methods": {
        "list": {
          "description": "Lists all shared albums shown to a user in the 'Sharing' tab of the\nGoogle Photos app.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.readonly",
            "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
          ],
          "flatPath": "v1/sharedAlbums",
          "id": "photoslibrary.sharedAlbums.list",
          "path": "v1/sharedAlbums"
        },
        "join": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary.sharing"
          ],
          "flatPath": "v1/sharedAlbums:join",
          "path": "v1/sharedAlbums:join",
          "id": "photoslibrary.sharedAlbums.join",
          "description": "Joins a shared album on behalf of the Google Photos user."
        }
      }
    },
    "albums": {
      "methods": {
        "create": {
          "description": "Creates an album in a user's Google Photos library.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.appendonly",
            "https://www.googleapis.com/auth/photoslibrary.sharing"
          ],
          "flatPath": "v1/albums",
          "path": "v1/albums",
          "id": "photoslibrary.albums.create"
        },
        "share": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary.sharing"
          ],
          "flatPath": "v1/albums/{albumsId}:share",
          "path": "v1/albums/{+albumId}:share",
          "id": "photoslibrary.albums.share",
          "description": "Marks an album as 'shared' and accessible to other users. This action can\nonly be performed on albums which were created by the developer via the\nAPI."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.readonly",
            "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
          ],
          "flatPath": "v1/albums",
          "id": "photoslibrary.albums.list",
          "path": "v1/albums",
          "description": "Lists all albums shown to a user in the 'Albums' tab of the Google\nPhotos app.",
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.readonly",
            "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
          ],
          "flatPath": "v1/albums/{albumsId}",
          "id": "photoslibrary.albums.get",
          "path": "v1/albums/{+albumId}",
          "description": "Returns the album specified by the given album id."
        },
        "addEnrichment": {
          "flatPath": "v1/albums/{albumsId}:addEnrichment",
          "id": "photoslibrary.albums.addEnrichment",
          "path": "v1/albums/{+albumId}:addEnrichment",
          "description": "Adds an enrichment to a specified position in a defined album.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.appendonly",
            "https://www.googleapis.com/auth/photoslibrary.sharing"
          ]
        }
      }
    }
  }
}
