{
  "discoveryVersion": "v1",
  "protocol": "rest",
  "canonicalName": "Script",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/groups": {
          "description": "View and manage your Google Groups"
        },
        "https://www.googleapis.com/auth/script.deployments": {
          "description": "Create and update Google Apps Script deployments"
        },
        "https://www.googleapis.com/auth/forms.currentonly": {
          "description": "View and manage forms that this application has been installed in"
        },
        "https://www.googleapis.com/auth/script.processes": {
          "description": "View Google Apps Script processes"
        },
        "https://www.googleapis.com/auth/script.deployments.readonly": {
          "description": "View Google Apps Script deployments"
        },
        "https://www.googleapis.com/auth/admin.directory.group": {
          "description": "View and manage the provisioning of groups on your domain"
        },
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "See, edit, create, and delete your spreadsheets in Google Drive"
        },
        "https://www.googleapis.com/auth/forms": {
          "description": "View and manage your forms in Google Drive"
        },
        "https://www.google.com/m8/feeds": {
          "description": "See, edit, download, and permanently delete your contacts"
        },
        "https://www.googleapis.com/auth/documents": {
          "description": "View and manage your Google Docs documents"
        },
        "https://www.google.com/calendar/feeds": {
          "description": "See, edit, share, and permanently delete all the calendars you can access using Google Calendar"
        },
        "https://www.googleapis.com/auth/script.projects.readonly": {
          "description": "View Google Apps Script projects"
        },
        "https://www.googleapis.com/auth/script.projects": {
          "description": "Create and update Google Apps Script projects"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/admin.directory.user": {
          "description": "View and manage the provisioning of users on your domain"
        },
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        },
        "https://www.googleapis.com/auth/userinfo.email": {
          "description": "View your email address"
        },
        "https://www.googleapis.com/auth/script.metrics": {
          "description": "View Google Apps Script project's metrics"
        }
      }
    }
  },
  "rootUrl": "https://script.googleapis.com/",
  "ownerDomain": "google.com",
  "name": "script",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "title": "Apps Script API",
  "ownerName": "Google",
  "resources": {
    "processes": {
      "methods": {
        "list": {
          "flatPath": "v1/processes",
          "id": "script.processes.list",
          "path": "v1/processes",
          "description": "List information about processes made by or on behalf of a user,\nsuch as process type and current status.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/script.processes"
          ]
        },
        "listScriptProcesses": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/script.processes"
          ],
          "flatPath": "v1/processes:listScriptProcesses",
          "id": "script.processes.listScriptProcesses",
          "path": "v1/processes:listScriptProcesses",
          "description": "List information about a script's executed processes, such as process type\nand current status."
        }
      }
    },
    "scripts": {
      "methods": {
        "run": {
          "description": "Runs a function in an Apps Script project. The script project must be\ndeployed for use with the Apps Script API and the calling application must\nshare the same Cloud Platform project.\n\nThis method requires authorization with an OAuth 2.0 token that includes at\nleast one of the scopes listed in the\n[Authorization](#authorization-scopes) section; script projects that do not\nrequire authorization cannot be executed through this API. To find the\ncorrect scopes to in[...]",
          "httpMethod": "POST",
          "scopes": [
            "https://mail.google.com/",
            "https://www.google.com/calendar/feeds",
            "https://www.google.com/m8/feeds",
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.user",
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/forms",
            "https://www.googleapis.com/auth/forms.currentonly",
            "https://www.googleapis.com/auth/groups",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/userinfo.email"
          ],
          "flatPath": "v1/scripts/{scriptId}:run",
          "path": "v1/scripts/{scriptId}:run",
          "id": "script.scripts.run"
        }
      }
    },
    "projects": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects",
            "https://www.googleapis.com/auth/script.projects.readonly"
          ],
          "flatPath": "v1/projects/{scriptId}",
          "path": "v1/projects/{scriptId}",
          "id": "script.projects.get",
          "description": "Gets a script project's metadata."
        },
        "updateContent": {
          "description": "Updates the content of the specified script project.\nThis content is stored as the HEAD version, and is used when the script is\nexecuted as a trigger, in the script editor, in add-on preview mode, or as\na web app or Apps Script API in development mode. This clears all the\nexisting files in the project.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects"
          ],
          "flatPath": "v1/projects/{scriptId}/content",
          "path": "v1/projects/{scriptId}/content",
          "id": "script.projects.updateContent"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/script.projects"
          ],
          "flatPath": "v1/projects",
          "path": "v1/projects",
          "id": "script.projects.create",
          "description": "Creates a new, empty script project with no script files and a base\nmanifest file.",
          "httpMethod": "POST"
        },
        "getContent": {
          "description": "Gets the content of the script project, including the code source and\nmetadata for each script file.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects",
            "https://www.googleapis.com/auth/script.projects.readonly"
          ],
          "flatPath": "v1/projects/{scriptId}/content",
          "path": "v1/projects/{scriptId}/content",
          "id": "script.projects.getContent"
        },
        "getMetrics": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/script.metrics"
          ],
          "flatPath": "v1/projects/{scriptId}/metrics",
          "path": "v1/projects/{scriptId}/metrics",
          "id": "script.projects.getMetrics",
          "description": "Get metrics data for scripts, such as number of executions and\nactive users."
        }
      },
      "resources": {
        "deployments": {
          "methods": {
            "delete": {
              "description": "Deletes a deployment of an Apps Script project.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "id": "script.projects.deployments.delete",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}"
            },
            "get": {
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "id": "script.projects.deployments.get",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "description": "Gets a deployment of an Apps Script project.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments",
                "https://www.googleapis.com/auth/script.deployments.readonly"
              ]
            },
            "list": {
              "description": "Lists the deployments of an Apps Script project.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments",
                "https://www.googleapis.com/auth/script.deployments.readonly"
              ],
              "flatPath": "v1/projects/{scriptId}/deployments",
              "path": "v1/projects/{scriptId}/deployments",
              "id": "script.projects.deployments.list"
            },
            "update": {
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "id": "script.projects.deployments.update",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "description": "Updates a deployment of an Apps Script project."
            },
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "flatPath": "v1/projects/{scriptId}/deployments",
              "path": "v1/projects/{scriptId}/deployments",
              "id": "script.projects.deployments.create",
              "description": "Creates a deployment of an Apps Script project."
            }
          }
        },
        "versions": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects",
                "https://www.googleapis.com/auth/script.projects.readonly"
              ],
              "flatPath": "v1/projects/{scriptId}/versions/{versionNumber}",
              "path": "v1/projects/{scriptId}/versions/{versionNumber}",
              "id": "script.projects.versions.get",
              "description": "Gets a version of a script project."
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects",
                "https://www.googleapis.com/auth/script.projects.readonly"
              ],
              "flatPath": "v1/projects/{scriptId}/versions",
              "path": "v1/projects/{scriptId}/versions",
              "id": "script.projects.versions.list",
              "description": "List the versions of a script project."
            },
            "create": {
              "flatPath": "v1/projects/{scriptId}/versions",
              "id": "script.projects.versions.create",
              "path": "v1/projects/{scriptId}/versions",
              "description": "Creates a new immutable version using the current code, with a unique\nversion number.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects"
              ]
            }
          }
        }
      }
    }
  },
  "version": "v1",
  "baseUrl": "https://script.googleapis.com/",
  "servicePath": "",
  "description": "Manages and executes Google Apps Script projects.\n",
  "kind": "discovery#restDescription",
  "basePath": "",
  "documentationLink": "https://developers.google.com/apps-script/api/",
  "revision": "20190907",
  "id": "script:v1"
}
