{
  "id": "youtubeAnalytics:v2",
  "documentationLink": "https://developers.google.com/youtube/analytics",
  "revision": "20191016",
  "discoveryVersion": "v1",
  "version_module": true,
  "protocol": "rest",
  "canonicalName": "YouTube Analytics",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/youtube.readonly": {
          "description": "View your YouTube account"
        },
        "https://www.googleapis.com/auth/yt-analytics.readonly": {
          "description": "View YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/youtube": {
          "description": "Manage your YouTube account"
        },
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": {
          "description": "View monetary and non-monetary YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/youtubepartner": {
          "description": "View and manage your assets and associated content on YouTube"
        }
      }
    }
  },
  "rootUrl": "https://youtubeanalytics.googleapis.com/",
  "ownerDomain": "google.com",
  "name": "youtubeAnalytics",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "title": "YouTube Analytics API",
  "ownerName": "Google",
  "resources": {
    "reports": {
      "methods": {
        "query": {
          "flatPath": "v2/reports",
          "path": "v2/reports",
          "id": "youtubeAnalytics.reports.query",
          "description": "Retrieve your YouTube Analytics reports.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        }
      }
    },
    "groupItems": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "flatPath": "v2/groupItems",
          "path": "v2/groupItems",
          "id": "youtubeAnalytics.groupItems.delete",
          "description": "Removes an item from a group."
        },
        "insert": {
          "description": "Creates a group item.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "flatPath": "v2/groupItems",
          "path": "v2/groupItems",
          "id": "youtubeAnalytics.groupItems.insert"
        },
        "list": {
          "description": "Returns a collection of group items that match the API request parameters.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "flatPath": "v2/groupItems",
          "path": "v2/groupItems",
          "id": "youtubeAnalytics.groupItems.list"
        }
      }
    },
    "groups": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "flatPath": "v2/groups",
          "path": "v2/groups",
          "id": "youtubeAnalytics.groups.delete",
          "description": "Deletes a group."
        },
        "insert": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "flatPath": "v2/groups",
          "path": "v2/groups",
          "id": "youtubeAnalytics.groups.insert",
          "description": "Creates a group."
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "flatPath": "v2/groups",
          "id": "youtubeAnalytics.groups.list",
          "path": "v2/groups",
          "description": "Returns a collection of groups that match the API request parameters. For\nexample, you can retrieve all groups that the authenticated user owns,\nor you can retrieve one or more groups by their unique IDs."
        },
        "update": {
          "path": "v2/groups",
          "id": "youtubeAnalytics.groups.update",
          "description": "Modifies a group. For example, you could change a group's title.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "flatPath": "v2/groups"
        }
      }
    }
  },
  "version": "v2",
  "baseUrl": "https://youtubeanalytics.googleapis.com/",
  "servicePath": "",
  "description": "Retrieves your YouTube Analytics data.",
  "kind": "discovery#restDescription",
  "basePath": ""
}
